'use strict';
const LESSONS=[['qtime','QTime｜時間限制'],['future-hold','Future Hold｜預約攔截'],['part-route','Part 與 RouteId'],['recipes','LR、ER、Physical Recipe'],['flow-versions','Flow｜四種教法比較']];
const STEPS=[['S10','清洗'],['S20','成膜'],['S30','微影'],['S40','蝕刻'],['S50','量測'],['S60','結案']];
const state={minutes:20,hold:false,stop:'in',futureStep:1,futureReleased:false,lot:'L023',equipment:'ETCH-01',mismatch:false,variant:'a',journey:2};
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=(tag,h,p)=>`<div class="lesson-head"><span class="pill">${tag}</span><h1>${h}</h1><p class="lead">${p}</p></div>`;
const conceptArt=(key,caption)=>`<details class="concept-illustration" ${innerWidth>760?'open':''}><summary>情境插畫 · ${caption}</summary><figure class="variant-art"><img src="assets/mes-009/${key}.png" alt="${caption}，教學示意" data-zoom="assets/mes-009/${key}.png"><figcaption><span>下方用同一案例操作與核對條件。</span><button class="btn" data-zoom="assets/mes-009/${key}.png">放大完整圖</button></figcaption></figure></details>`;
const take=t=>`<div class="takeaway">${t}</div>`;
const table=(heads,rows)=>`<table class="field-table"><thead><tr>${heads.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const quiz=(id,q,answers,feedback)=>`<section class="quiz" data-quiz="${id}"><p class="eyebrow">換個情境想一想</p><h3>${q}</h3>${answers.map((a,i)=>`<button data-answer="${i}" aria-pressed="false">${a}</button>`).join('')}<div class="answer" role="status" data-feedback="${escapeHTML(JSON.stringify(feedback))}"></div></section>`;
const ticket=(head,rows)=>`<div class="ticket"><h3>${head}</h3><dl>${rows.map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')}</dl></div>`;
const track=(n,lot,hold=false)=>`<div class="route-track">${STEPS.map(([id,name],i)=>`<div class="station ${i<n?'done':i===n?(hold?'hold':'current'):''}">${i===n?`<span class="pin">${lot}${hold?' · Hold':''}</span>`:''}<strong>${id}</strong><span>${name}</span><small>${i<n?'✓ 完成':i===n?'目前':'未到'}</small></div>`).join('')}</div>`;
function qtime(){return title('01 / TIME CONSTRAINT','QTime：這段時間，最多能等多久？','先認出「起算事件」和「截止事件」，再看時限。它約束的是一段事件間隔，不是整個 Lot 的製造時間。')+conceptArt('qtime','起點、等待與截止事件')+
`<div class="visual"><p class="visual-label">可追算案例 · LOT L023 · 假設最大時限 30 分鐘</p><h2>10:00 清洗完成，何時必須進入下一站？</h2><div class="clock-panel"><div class="event"><div class="wafer"></div><strong>S10 清洗 Move Out</strong><b class="time">10:00</b><small>起算事件已發生</small></div><div class="clock"><div class="dial" id="q-dial"><div><b id="q-remaining">10</b><span id="q-caption">分鐘可用</span></div></div><span class="timer-label">同一段 QTime，不因等待而重設</span></div><div class="event"><div class="wafer" id="q-end-wafer"></div><strong id="q-end">S20 成膜 Move In</strong><b class="time">10:30</b><small>本例截止時間</small></div></div><div class="timeline" id="q-timeline"><i></i></div><div class="ticks"><span>10:00 起算</span><span>10:30 截止</span><span>10:45</span></div><div class="control"><label for="q-minutes">把現在時間移到 <output id="q-now">10:20</output></label><input id="q-minutes" type="range" min="0" max="45" value="${state.minutes}" step="1"><div class="actions"><button data-minute="20">10:20</button><button data-minute="30">10:30</button><button data-minute="45">10:45</button></div><label for="q-stop">比較不同的停止事件</label><select id="q-stop"><option value="in">規則 A：S20 Move In（進站）</option><option value="out">規則 B：S20 Move Out（出站）</option></select><label class="checkline"><input id="q-hold" type="checkbox"> 這段期間 Lot 被 Hold</label><div id="q-result" class="result" role="status"></div></div>${take('QTime = 起訖事件 + 允許間隔；只知道「30 分鐘」還不夠。')}</div>`+
`<section class="section"><h2>為什麼要限制這段時間？</h2><p>有些製程完成後，表面或材料狀態會隨時間改變。下一段製程若拖太久，原先假設的加工條件可能不再成立。QTime 把這種風險變成可監控的時間條件；實際原因與門檻由製程規格決定。</p><div class="three"><article class="paper"><span class="num">DEFINE</span><h3>先定義兩個事件</h3><p>可能是前站出站到後站進站，也可能跨越數站、到指定站出站才停止。不能一律當成排隊時間。</p></article><article class="paper"><span class="num">MEASURE</span><h3>從已發生的時間算</h3><p>本例 10:00 起算，30 分鐘後是 10:30。10:20 進站與 10:35 出站，對兩種規則會有不同判定。</p></article><article class="paper"><span class="num">ACT</span><h3>超時交給規定處置</h3><p>查目前事件、剩餘時間與下一站能力。超時依廠規覆核、Hold 或重工；不自行改時間，也不因解除 Hold 就重設。</p></article></div></section>`+
table(['查什麼','本例','避免誤用'],[['起點與終點','S10 Move Out → S20 Move In','同一站也要分進站／出站'],['限制與單位','最大 30 分鐘；本例允許等於 30','實際可能有最短／最長或多段限制'],['起算時間、事件是否到達','10:00；是否已有 S20 Move In','資料延遲不能當成事件沒發生'],['超時處置／例外規則','依製程規格','加急不代表可跳過規則']])+
quiz('qtime','10:20 進站、10:35 出站。哪個資訊能決定是否超時？',['只看 10:20 已經進站','確認 QTime 的停止事件是進站還是出站'],['若停止事件是出站，10:20 進站仍未結束計時。要先讀完整規則。','正確。若以進站停止，本例 20 分鐘符合；若以出站停止，35 分鐘超過 30 分鐘。'])+
`<p class="source">概念來源：<a href="https://patents.google.com/patent/US9748088B2/en" target="_blank" rel="noopener">半導體製造的 Queue Time 間隔限制</a>。30 分鐘、S10/S20 與邊界判斷皆為教學假設，不是實際製程規格。</p>`;}
function updateQ(){const m=state.minutes,remaining=30-m;document.querySelector('#q-minutes').value=m;document.querySelector('#q-now').textContent=`10:${String(m).padStart(2,'0')}`;document.querySelector('#q-stop').value=state.stop;document.querySelector('#q-hold').checked=state.hold;document.querySelector('#q-remaining').textContent=Math.abs(remaining);document.querySelector('#q-caption').textContent=remaining>=0?'分鐘可用':'分鐘超時';document.querySelector('#q-dial').style.setProperty('--angle',`${Math.min(360,m/30*360)}deg`);document.querySelector('#q-dial').style.setProperty('--blue',m>30?'#c85642':'#176bce');document.querySelector('#q-timeline').style.setProperty('--position',`${m/45*100}%`);document.querySelector('#q-end-wafer').className='wafer'+(state.stop==='out'?' coated':'');document.querySelector('#q-end').textContent=state.stop==='in'?'S20 成膜 Move In':'S20 成膜 Move Out';const el=document.querySelector('#q-result');el.className=`result ${m>30?'bad':m===30?'warn':''}`;el.textContent=(m>30?`指定的停止事件若仍未發生，已超時 ${m-30} 分鐘；應依規定處置。`:m===30?'現在正好到截止；本例只有停止事件在此刻或更早發生才符合。':`指定的停止事件若尚未發生，還剩 ${remaining} 分鐘。`)+(state.stop==='out'?' 此規則要到出站才停止；進站不會結束計時。':' 此規則以進站停止。')+(state.hold?' 本例 Hold 期間仍計時，起點維持 10:00。':'');}
function future(){return title('02 / SCHEDULED HOLD','Future Hold：先約好，到指定位置再攔住','現在登記一個「未來的攔截條件」。條件尚未到達時是待觸發；到指定事件才建立有效的 Hold。')+conceptArt('future','登記、途中與到站攔截')+
`<div class="visual"><p class="visual-label">教學規則 · L023 在 S20 登記，抵達 S50 進站前觸發</p><h2>批次可以先往前走，但不能漏掉目標站的檢查</h2><div class="stage-brackets"><span>Stage A 準備</span><span>Stage B 圖形</span><span>Stage C 確認</span></div><div id="future-route"></div><div class="status-pair"><div><span>Future Hold 登記</span><b id="future-pending"></b><small>目標：F-DEMO v1 / S50 / 進站前</small></div><div><span>目前有效 Hold</span><b id="future-active"></b><small id="future-detail"></small></div></div><div class="actions"><button id="future-next">前進一站</button><button id="future-release">解除這筆 Hold</button><button id="future-reset">重演情境</button></div><div id="future-result" class="result" role="status"></div>${take('Future Hold 是預先設定的觸發條件；不代表 Lot 現在已經被 Hold。')}</div>`+
`<section class="section"><div class="two"><article class="paper"><h3>為什麼不直接現在 Hold？</h3><p>工程師想在 S50 量測前核對檢驗結果，但前面作業仍可依規則完成。Future Hold 把攔截安排在需要判斷的位置，減少過早停止的等待。</p><p>若異常需要立刻停止，應使用適用的即時 Hold 流程；不能把 Future Hold 當成立即攔截。</p></article><article class="paper"><h3>「未來」不一定是鐘錶時間</h3><p>重點通常是指定 Route、Operation／Step 與進站或出站事件。到達哪個邊界、重工再次經過是否重觸發、改 Route 後如何處理，都要查系統規則。</p><p>登記成功後，也要能查到規則身分、目標與生效狀態，不能只留一段備註。</p></article></div></section>`+
table(['狀態','看得見的證據','下一步'],[['待觸發','Future Hold 記錄存在；尚未到目標事件','持續核對目標與路徑'],['已觸發','有效 Hold 記錄、原因與觸發時間','依權限及處置程序覆核'],['已解除此筆','Release 記錄與原因','還要確認其他 Hold、QTime、設備與配方條件']])+
quiz('future','Lot 已在 S50，檢驗 Hold 解除了，但仍有設備相關 Hold。可以進站嗎？',['可以，已解除剛才那筆 Hold','仍要確認其他有效 Hold 與進站條件'],['解除一筆不會自動解除其他原因的 Hold。','正確。Hold 是可以並存的限制；解除指定記錄不等於取得所有加工許可。'])+
`<p class="source">實作參考：<a href="https://help.sap.com/docs/SAP_MANUFACTURING_EXECUTION/e1adc70af32241619335c8768a892edb/eabb912a895c4b729d766bd0e00c029e.html" target="_blank" rel="noopener">SAP ME Future Hold</a> 以到指定 Operation 的 In Queue 為觸發例。本頁「S50 進站前」為教學設定；廠內實際觸發點需另核對。</p>`;}
function updateFuture(){const triggered=state.futureStep>=4;document.querySelector('#future-route').innerHTML=track(state.futureStep,'L023',triggered&&!state.futureReleased);document.querySelector('#future-pending').textContent=triggered?'已觸發':'待觸發';document.querySelector('#future-active').textContent=triggered?(state.futureReleased?'此筆已解除':'檢驗結果待確認'):'本例尚無';document.querySelector('#future-detail').textContent=triggered?'原因：量測前覆核檢驗結果':'尚未到達 S50 的觸發事件';document.querySelector('#future-release').disabled=!triggered||state.futureReleased;document.querySelector('#future-next').disabled=triggered;const r=document.querySelector('#future-result');r.className=`result ${triggered&&!state.futureReleased?'warn':''}`;r.textContent=triggered?(state.futureReleased?'已解除此筆；下一步仍須核對其他有效限制。本演示到此停止，不假設自動進站。':'已到 S50 進站前：Future Hold 生效，先完成覆核，不能直接開始量測。'):'登記存在但尚未觸發。本例沒有其他阻擋條件，因此可以繼續前往目標站。';}
function part(){return title('03 / PRODUCT & ROUTE','Part 說「做什麼」，RouteId 說「走哪條路」','Lot 是這次實際生產的一批；它引用產品定義與路徑。相同產品可以有多批 Lot，相同路徑也可能被多個產品共用。')+conceptArt('part','產品、路徑與兩批 Lot')+
`<p class="spec">命名範圍：本頁暫以 <b>Part = 產品／料號定義</b> 說明。你們內部的 Part 層級、版本欄位與 RouteId 格式，仍需依資料字典確認。</p><div class="visual"><h2>把產品、路徑和這一批的身分分開看</h2><div class="relation">${ticket('Part · 產品定義',[['Part','P-DEMO'],['回答','要做哪種產品？'],['包含概念','規格／版本／允許路徑']])}<div class="arrow">→<small>本例選用</small></div>${ticket('Route · 路徑定義',[['RouteId','F-DEMO'],['Revision','v1'],['順序','S10 → … → S60']])}<div class="arrow reverse">←<small>Lot 引用</small></div><div id="part-ticket"></div></div><div class="actions"><button data-lot="L023" aria-pressed="true">看 L023</button><button data-lot="L024" aria-pressed="false">換成 L024</button></div><div id="part-route"></div><p class="note">上方是定義與引用關係；下方是所選 Lot 的執行位置。換 Lot 不會改寫路徑。</p>${take('產品身分、路徑身分、批次位置，是三個不同的問題。')}</div>`+
`<div class="two section"><article class="paper"><h3>Part 是什麼？</h3><p>在這個教學模型中，它用來識別產品或料號及其規格定義。P-DEMO 可以生產很多批，每批都有獨立的 LotId、晶圓清單與製程歷史。</p><p>不要把 Part 當成單片 Wafer，也不要把 PartId 當 LotId。產品版本改變時，需查適用規格與允許路徑是否一起變更。</p></article><article class="paper"><h3>RouteId 是什麼？</h3><p>它識別一條路徑定義。Flow 描述製程如何走；RouteId 是系統用來指到該定義的識別資訊。實際可能還需要 Revision 或其他版本鍵。</p><p>同叫 F-DEMO 的 v1、v2 不應視為完全相同；也不能從 RouteId 推斷 Lot 現在在哪站，尤其存在分支、重工或臨時路徑時。</p></article></div>`+
table(['你的問題','要找的資訊'],[['這批要做哪一種產品？','Lot → Part／產品版本'],['這批依哪個製程版本走？','Lot → RouteId ＋ Revision／生效版本'],['這批目前走到哪裡？','Lot 的目前路徑、Operation／Step、狀態'],['這批以前走過哪些路？','路徑指派、變更與執行歷史；不是只查目前主檔']])+
quiz('part','L023 使用 F-DEMO v1；主檔新增 v2。L023 是否已自動改走 v2？',['主檔比較新，所以直接視為 v2','查 L023 的實際版本指派與變更記錄'],['新增版本與遷移執行中的 Lot 是兩件事，不能由主檔最新版本推斷。','正確。先確認這批引用哪個版本，以及遷移是否被核准並實際生效。'])+
`<p class="source">本節為依使用者名詞建立的教學映射，未取得廠內 Part／RouteId 資料字典。畫面 ID 為虛構，箭頭不宣稱固定一對一關係。</p>`;}
function updatePart(){const n=state.lot==='L023'?4:1;document.querySelector('#part-ticket').innerHTML=ticket('Lot · 實際批次',[['LotId',state.lot],['Part','P-DEMO'],['Route','F-DEMO v1'],['目前',STEPS[n][0]+' 等待']]);document.querySelector('#part-route').innerHTML=track(n,state.lot);document.querySelectorAll('[data-lot]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.lot===state.lot)));}
function recipes(){return title('04 / RECIPE MAPPING','同一句「Recipe」，可能指三個不同層級','LR 描述邏輯上的加工要求，ER 把要求連到適用設備，Physical Recipe 是設備實際加工所用的配方。查到名稱後，還要核對它屬於哪一層。')+conceptArt('recipes','從邏輯要求到實際執行')+
`<p class="spec"><b>教學映射，待廠內定義確認：</b>這裡用 LR → ER → Physical Recipe 解釋角色；不假設各層在你們的系統中一定是獨立資料表、固定一對一，或一定經過下載才執行。</p><div class="visual"><p class="visual-label">LOT L023 · P-DEMO · F-DEMO v1 · S40 蝕刻</p><h2>同一個加工要求，換設備可能要換實際配方</h2><div class="relation">${ticket('LR · Logical Recipe',[['LR','LR-ETCH-A'],['角色','邏輯加工要求'],['本例','S40 選用此要求']])}<div class="arrow">→<small>選擇適配</small></div><div id="er-ticket"></div><div class="arrow">→<small>對應執行</small></div><div id="physical-ticket"></div></div><div class="control"><label for="recipe-equipment">選擇本次設備</label><select id="recipe-equipment"><option>ETCH-01</option><option>ETCH-02</option></select><label class="checkline"><input type="checkbox" id="recipe-mismatch"> 模擬回報的是舊版本 v6</label><div class="recipe-match"><div><span class="visual-label">EXPECTED · 核准對應</span><b id="recipe-expected"></b><span>應執行版本 v7</span></div><div><span class="visual-label">REPORTED · 加工回報示意</span><b id="recipe-reported"></b><span id="recipe-version"></span></div></div><div class="result" id="recipe-result" role="status"></div></div>${take('LR 對不對、設備適不適用、實際跑的配方對不對，要分層核對。')}</div>`+
`<div class="three section"><article class="paper"><span class="num">INTENT</span><h3>LR：Logical Recipe</h3><p>邏輯配方把此作業需要的加工要求抽象化，便於流程引用與設備適配。它不等於某一台設備上的完整參數檔。</p><p>本例 S40 指向 LR-ETCH-A；還要結合產品、設備與規則選擇適用的配方。</p></article><article class="paper"><span class="num">MAPPING</span><h3>ER：EQP Recipe</h3><p>設備配方層負責表達適用設備與配方對應。本例 ETCH-01 和 ETCH-02 使用不同 ER，實作同一個 LR 的要求。</p><p>ER 與 Physical Recipe 的界線依系統而異；不要先假設 ER 名称就是設備實際檔名。</p></article><article class="paper"><span class="num">EXECUTION</span><h3>Physical Recipe</h3><p>實際加工時使用的設備配方內容或程序，可能有配方 ID、版本及參數集，也可能由下載、設備既有內容或受控展開產生。</p><p>要知道「這次跑了什麼」，看本次執行回報／稽核記錄；只有預期對應不足以證明已執行內容。</p></article></div>`+
table(['查詢層級','需要連在一起看的資訊'],[['流程選用','Lot、Part、Route 版本、Operation／Step、LR'],['設備適配','設備／Chamber、ER、核准狀態、有效期間與映射版本'],['實際執行','Run／Job 身分、設備、Physical Recipe ID、回報版本與執行時間'],['更細的內容一致性','若有支援，核對受控 checksum、參數集或 recipe audit；不能假設每個系統都有']])+
quiz('recipes','LR 和 ER 名稱都正確，但加工回報是同名配方的舊版本。可以視為正確加工嗎？',['名稱一樣即可','先核對核准版本與實際執行記錄'],['相同名稱不保證內容或版本相同；也不能只用目前映射取代當時的執行證據。','正確。若在加工前發現應依規則阻止啟動；若加工後才發現，應追溯影響批次並按異常程序處置。'])+
`<p class="source">本節依使用者提供的 LR／ER／Physical Recipe 名稱建構概念模型。設備、版本、配方代號均為教學示意；未使用可供實際加工的參數。內部物件關係仍待資料字典確認。</p>`;}
function updateRecipe(){const two=state.equipment==='ETCH-02',er=two?'ER-ETCH-02-A':'ER-ETCH-01-A',physical=two?'ETCH_A_TOOL2':'ETCH_A_TOOL1';document.querySelector('#er-ticket').innerHTML=ticket('ER · EQP Recipe',[['ER',er],['適用設備',state.equipment],['對應','LR-ETCH-A']]);document.querySelector('#physical-ticket').innerHTML=ticket('Physical · 實際配方',[['配方 ID',physical],['核准版本','v7'],['套用對象',state.equipment]]);document.querySelector('#recipe-equipment').value=state.equipment;document.querySelector('#recipe-mismatch').checked=state.mismatch;document.querySelector('#recipe-expected').textContent=physical;document.querySelector('#recipe-reported').textContent=physical;document.querySelector('#recipe-version').textContent='回報版本 '+(state.mismatch?'v6':'v7');const r=document.querySelector('#recipe-result');r.className='result'+(state.mismatch?' bad':'');r.textContent=state.mismatch?'不一致：名稱相同，版本不同。加工前發現應依規則阻止啟動；加工後回報才發現則追溯與異常處置。':'本例 ID 與版本一致；這只完成配方比對，仍需核對設備資格、產品適用性及其他加工條件。';}
const compactLot=(n,lot)=>`<div class="compact-lot"><h3>${lot} · 目前 ${STEPS[n][0]}</h3><div class="compact-progress">${STEPS.map(([id],i)=>`<span class="${i<n?'done':i===n?'current':''}">${id}</span>`).join('')}</div><p>綠色已完成 · 藍色目前 · 灰色未到</p></div>`;
const VARIANTS={original:{name:'原版｜製程實物',img:'assets/mes-v3/stage-v2.png',good:'先從清洗、成膜、微影、蝕刻等實物和剖面認識六站，再用括號理解三個 Stage。',limit:'製程細節很多；第一次只想分清三個名詞時，可能會先被加工畫面吸引。',line:'Step 是一站，Stage 是一段，Flow 是整條路徑。'},a:{name:'A｜階層放大',img:'assets/mes-009/flow-a.png',good:'適合第一次分清三個名詞：由整條 Flow 放大到 Stage B，再看其中的 Step S40。',limit:'強項是層級關係；還需要另一個例子說明 Lot 位置如何隨執行更新。',line:'Flow 看全程；Stage 看段落；Step 看單站。'},b:{name:'B｜跟著 Lot 走',img:'assets/mes-009/flow-b.png',good:'適合會查 Lot 狀態的人：路徑是固定參考，Lot 指標往前移，完成、目前、未到各有意義。',limit:'本例只畫直線主流程。分支、重工、跳站與 Hold 需要再加各自規則。',line:'Flow 提供路徑；Lot 的目前位置由執行事件更新。'},c:{name:'C｜定義對照進度',img:'assets/mes-009/flow-c.png',good:'適合開始查 MES 資料的人：共用的 Route 定義與兩批 Lot 的進度分開看，避免把路徑誤當履歷。',limit:'同路徑的對照較抽象；若還不熟 Lot，建議先看原版或 A。',line:'同一條 Flow 可供多批 Lot 使用；每批的目前 Step 各自不同。'}};
function variants(){return title('05 / CHOOSE AN EXPLANATION','Stage、Step、Flow：選一種你想用的教法','原版保留，再提供三種不同的理解路徑。比較的是教學切入點；本頁選擇不會覆寫正式課程。')+
`<div class="variant-tabs" role="group" aria-label="選擇說明版本">${Object.entries(VARIANTS).map(([k,v])=>`<button data-variant="${k}" aria-pressed="${state.variant===k}"><b>${v.name}</b><span>${{original:'看實物與製程變化',a:'由大到小看包含關係',b:'看一批 Lot 如何前進',c:'分開定義與執行狀態'}[k]}</span></button>`).join('')}</div><div id="variant-content"></div><div class="actions"><button id="save-variant">記下我偏好的這一版</button><span class="saved" id="variant-saved" role="status"></span></div>`+
table(['版本','主要回答','適合拿來接什麼內容'],[['原版','各站做什麼？三段如何分組？','實體製程與 Stage 分組'],['A 階層放大','Step、Stage、Flow 誰包含誰？','首次介紹名詞'],['B 跟著 Lot 走','現在在哪？完成與未到差在哪？','Move In／Move Out、Hold'],['C 定義對照進度','同一條路徑，為何批次狀態不同？','Part、RouteId、版本與資料查詢']])+
quiz('flow','兩批 Lot 使用同一個 F-DEMO v1，一批在 S20，一批在 S50。它們的 Flow 不同嗎？',['位置不同，所以 Flow 必然不同','先看路徑指派；目前 Step 不同不代表 Flow 不同'],['這裡不同的是執行進度。路徑定義與批次位置要分開看。','正確。本例共用同一路徑版本，各批的已完成站與目前位置不同。']);}
function mobileStory(k){if(k==='a')return `<div class="hierarchy-box"><strong>Flow · F-DEMO v1</strong><p>整條路徑：準備 → 圖形 → 確認</p><div class="hierarchy-box"><strong>Stage B · 圖形</strong><p>一段工作：S30 微影 → S40 蝕刻</p><div class="hierarchy-box"><strong>Step S40 · 蝕刻</strong><p>這一站執行圖形轉移作業。</p></div></div></div>`;if(k==='c')return `<p><b>共同定義：</b>F-DEMO v1，S10 → S20 → S30 → S40 → S50 → S60。</p>${compactLot(4,'Lot L023')}${compactLot(1,'Lot L024')}`;return `<p>Stage A：S10、S20；Stage B：S30、S40；Stage C：S50、S60。</p>${track(k==='original'?4:2,'L023')}`;}
function updateVariant(){const v=VARIANTS[state.variant];document.querySelectorAll('[data-variant]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.variant===state.variant)));document.querySelector('#variant-content').innerHTML=`<figure class="variant-art"><img src="${v.img}" alt="${v.name}：${v.line}" data-zoom="${v.img}"><figcaption><span>${v.name} · AI 教學插畫，非實際製程配置</span><button class="btn" data-zoom="${v.img}">放大完整圖</button></figcaption></figure><div class="mobile-story"><h3>手機閱讀版 · 同一張圖的主線</h3>${mobileStory(state.variant)}</div><div class="variant-explain"><div><h3>這一版怎麼講</h3><p>${v.good}</p></div><div><h3>要補充的地方</h3><p>${v.limit}</p></div></div>${take(v.line)}`;let saved;try{saved=localStorage.getItem('mes-flow-preferred-version')}catch{}document.querySelector('#variant-saved').textContent=saved&&VARIANTS[saved]?`已記錄偏好：${VARIANTS[saved].name}（僅本機）`:'';}
function render(){const key=location.hash.slice(1)||'qtime',idx=LESSONS.findIndex(([id])=>id===key);if(idx<0){location.replace('#qtime');return;}document.title=LESSONS[idx][1]+'｜MES 教學';document.querySelector('#lesson-nav').innerHTML=LESSONS.map(([id,name])=>`<a href="#${id}" ${id===key?'aria-current="page"':''}>${name}</a>`).join('');document.querySelector('#content').innerHTML=({qtime,'future-hold':future,'part-route':part,recipes,'flow-versions':variants}[key])()+`<div class="footer-nav">${idx?`<a href="#${LESSONS[idx-1][0]}">← ${LESSONS[idx-1][1]}</a>`:'<a href="flow.html#stage">← 回到 Flow 課程</a>'}${idx<LESSONS.length-1?`<a href="#${LESSONS[idx+1][0]}">${LESSONS[idx+1][1]} →</a>`:'<a href="freshness.html">資料新鮮度 →</a>'}</div>`;({qtime:updateQ,'future-hold':updateFuture,'part-route':updatePart,recipes:updateRecipe,'flow-versions':updateVariant}[key])();window.scrollTo(0,0);}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-zoom]');if(!b)return;if(b.dataset.minute!==undefined){state.minutes=Number(b.dataset.minute);updateQ();}if(b.id==='future-next'){if(state.futureStep<4)state.futureStep++;updateFuture();}if(b.id==='future-release'){if(state.futureStep===4)state.futureReleased=true;updateFuture();}if(b.id==='future-reset'){state.futureStep=1;state.futureReleased=false;updateFuture();}if(b.dataset.lot){state.lot=b.dataset.lot;updatePart();}if(b.dataset.variant){state.variant=b.dataset.variant;updateVariant();}if(b.id==='save-variant'){try{localStorage.setItem('mes-flow-preferred-version',state.variant);document.querySelector('#variant-saved').textContent=`已記錄偏好：${VARIANTS[state.variant].name}（僅本機，未替換正式課程）`;}catch{document.querySelector('#variant-saved').textContent='瀏覽器未允許儲存；本次比較仍可繼續。';}}if(b.dataset.answer!==undefined){const parent=b.closest('.quiz'),out=parent.querySelector('.answer');parent.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));out.className='answer result'+(Number(b.dataset.answer)===0?' warn':'');out.textContent=JSON.parse(out.dataset.feedback)[Number(b.dataset.answer)];}if(b.dataset.zoom){document.querySelector('#zoom-image').src=b.dataset.zoom;document.querySelector('#original-link').href=b.dataset.zoom;document.querySelector('#image-dialog').showModal();}if(b.id==='close-image')document.querySelector('#image-dialog').close();});
document.addEventListener('input',e=>{if(e.target.id==='q-minutes'){state.minutes=Number(e.target.value);updateQ();}});
document.addEventListener('change',e=>{if(e.target.id==='q-stop'){state.stop=e.target.value;updateQ();}if(e.target.id==='q-hold'){state.hold=e.target.checked;updateQ();}if(e.target.id==='recipe-equipment'){state.equipment=e.target.value;updateRecipe();}if(e.target.id==='recipe-mismatch'){state.mismatch=e.target.checked;updateRecipe();}});
window.addEventListener('hashchange',render);render();
