/* One curriculum, multiple ways to enter it. Links preserve existing lessons. */
window.MES_CATALOG=(()=>{
 const t=(id,label)=>({href:'topic.html?topic='+id,label,topic:id});
 const l=(href,label)=>({href,label});
 const units=[
 {id:0,title:'開始：選擇你的學習路線',question:'我要從零學習，還是解決眼前的問題？',prereq:[],outcome:'分清課程、工作任務與 ER 參考，找到自己的起點。',intro:'這門課教你判讀半導體製造資料。先認出對象，再確認時間，最後選擇足以回答問題的證據。所有操作都是教學情境。',lessons:[],check:['一進網站就要理解全部 ER 嗎？',['先從問題及必要概念開始，隨時可查 ER','必須背熟所有表名'],0,'完整 ER 是查詢座標；入門課會逐步建立讀圖需要的概念。']},
 {id:1,title:'物件、身分與位置',question:'W07 在哪裡，又屬於哪一批？',prereq:[0],outcome:'分清 Wafer、Lot、FOUP、Slot；查歷史時帶上時間。',intro:'Lot 管理一批晶圓，FOUP 承載晶圓；換容器與拆批是不同的事。位置資料要和觀察時刻一起讀。',lessons:[l('index.html#fab','走進 Fab'),l('index.html#wafer','Wafer 是哪一片'),l('index.html#foup','FOUP 容器'),l('index.html#slot','Slot 位置'),l('index.html#lot','Lot 生產歸屬'),t('load','同 FOUP 多 Lot 與25片互動'),t('material','以 FOUP 查裝載'),l('index.html#explore','操作身分與位置'),l('index.html#check','基礎自測')],check:['FOUP 換裝之後，能把目前的 Lot 當成昨日搬送的 Lot 嗎？',['可以，FOUP ID相同','不行，需對應當時裝載'],1,'容器身分相同，不保證不同時刻裝的是同一批。']},
 {id:2,title:'產品與加工路線',question:'這批應該怎麼走，目前在哪一站？',prereq:[1],outcome:'分清 PART、Flow 定義及 Lot 實際進度，理解版本。',intro:'先看產品使用哪個 Flow，再看 Module、Stage、Step。這份定義描述應走的路；歷程才說明這批實際做過什麼。',lessons:[t('part','PART 對應 Flow 與版本'),l('flow.html#flow','Flow 的最小模型'),t('stage','Module → Stage → Step'),l('flow.html#step','這一次作業的位置'),l('flow.html#lot-flow','Lot 套用流程'),t('flowkey','Lot 與 Flow 資料關係'),l('flow.html#versions','流程進版與適用範圍')],check:['發布新 Flow，是否足以證明所有在製 Lot 都已切新版？',['是','否，還要看適用與切版證據'],1,'PART記錄流程版本；不能僅由發布新版推定所有在製Lot已換版。']},
 {id:3,title:'一站如何加工',question:'這批在本站能交給哪台設備？',prereq:[1,2],outcome:'分清設備、Port、Chamber、加工資格和 Lot 狀態。',intro:'機群是設備集合。WPH 描述預期產出標準，後面用於理解預估；多重分群留到資料分析。這裡先分清「可以加工」與「正在加工」。',lessons:[l('operations.html#tool','從載具到腔體'),t('equipment','設備的資料角色'),t('port','Load Port'),t('chamber','Chamber 加工腔體'),t('pd','PD 站點細部定義'),t('recipe','LR、ER 與 Physical Recipe'),t('recipegroup','機台加工許可'),t('available','本站可用機台'),l('operations.html#port','身分核對'),l('operations.html#recipe','配方與設備資格'),t('eqpstatus','設備狀態与時間'),t('lotstatus','Lot RQHBE'),l('operations.html#chamber','逐片結果與整批完成'),l('operations.html#handoff','完成事件與結果核對'),l('support.html#cw','CW 的材料用途'),t('eqpkey','EQP_ID 的關係上下文')],check:['Port UP 和 Lot Q 同時出現，必然矛盾嗎？',['不矛盾：Port有貨，Lot仍等加工','矛盾：UP一定表示該Lot在加工'],0,'UP必須看對象；Port有貨不足以證明Lot已進機。']},
 {id:4,title:'預派、搬送與暫存',question:'安排去哪裡，與現在在哪裡有何不同？',prereq:[1,3],outcome:'沿時間追 FOUP，分清預派、搬送及進機。',intro:'預派讓機台預先知道下一批；FOUP透過搬送到設備附近。OHB是暫置架，OHT負責搬送，Port是交接位置。',lessons:[t('predispatch','Lot 預派'),t('prehistory','预派歷史'),l('operations.html#transport','搬送與暫存'),t('stock','Default Stocker'),t('ohb','設備附近 OHB'),t('bmir','OHB空位呼叫RTD'),t('portmode','Port UP／LOST'),t('location','位置關係'),t('mcs','MCS Macro／Micro 命令'),t('transfer','presum傳送摘要')],check:['RTD 選出下一批放 OHB 的貨，代表已經到架上嗎？',['代表已上架','只代表選貨結果，需再查搬送及到位'],1,'選貨、搬送、實際到位是不同層次的證據。']},
 {id:5,title:'管制與例外',question:'有可用機台，為什麼仍不能繼續？',prereq:[2,3],outcome:'辨別管制設定、觸發條件與實際紀錄。',intro:'等候可能來自不同原因。Hold、Future Hold、Product Hold、QTime各有對象與條件；Bank是長期暫置，不能把全部等待混成同一種事件。',lessons:[l('operations.html#state','Lot與設備限制'),t('future','Future Hold'),t('producthold','Product Hold'),t('qtime','QTime 起迄事件'),t('srts','Sampling rule與比例'),l('flow.html#branching','分流與Hold'),l('flow.html#rework','核准的重工路徑'),l('support.html#subroute','Sub Route追加量測'),l('support.html#monitor','MON／PM／EMS')],check:['某產品設了指定站點 Hold，能說所有相關 Lot 此刻都已 Hold 嗎？',['不能，需看是否到站觸發及實際紀錄','可以，有設定就全數已Hold'],0,'設定與生效事件要分開；尚未到指定站點的Lot不可直接判定已被攔住。']},
 {id:6,title:'重建批貨歷程',question:'這批在指定期間究竟做了哪些事？',prereq:[1,3,4,5],outcome:'重建事件、保留拆合批譜系，分清 Move 與搬送。',intro:'每次進機形成Move事件；完成後推進是另一個觀察點。本站完成、教學Flow完成與Lot E已出貨，範圍不同。',lessons:[t('actions','批貨所有動作歷史'),t('lotstep','Lot Step歷史'),t('move','進機Move計數'),l('support.html#move','操作事件與重複資料'),l('flow.html#execution','执行与歷程'),l('flow.html#split-merge','拆批與合批'),t('contents','FOUP內容物歷史'),l('operations.html#lab','六個現場情境'),l('flow.html#lab','十個Flow情境')],check:['同批重工再次進同一站，Move應如何理解？',['站名一樣只算一次','兩次獨立進機是兩個事件；重送資料另需去重依據'],1,'事件身分不同於站名。不能以不同站數替代進機事件數，也不能把重送再計一次。']},
 {id:7,title:'未來站點何時到',question:'預估到站時間從哪裡來？',prereq:[2,6],outcome:'解釋 Flow 與 IE WPH 如何提供預估依據。',intro:'先認識WPH是每小時預期晶圓產出標準，再沿Flow理解逐站累計。預估受假設影響，不能當作已發生事件。',lessons:[t('wph','機群 WPH 定義'),t('forecast','未來 Flow 到站預估'),t('stream','Stream 舊功能與 LDS 替代')],check:['預計14:00到某站，代表14:00必然已到站嗎？',['是','否，需實際事件與時間證據'],1,'預測描述未來估算，查實際到站仍需要執行或位置證據。']},
 {id:8,title:'機群、時間與資料分析',question:'報表在說哪些設備、哪個時間？',prereq:[3,6],outcome:'選擇來源與時間，辨別多重分群及關聯放大。',intro:'先定義統計對象，再選最新、每小時歷史或每日07:20快照。完整ER保留來源關係；連線不保證唯一鍵或一對多。',lessons:[t('bay','機台 Bay位置'),t('owner','機群與管理單位'),t('group','機台與Chamber分群'),t('virtual','SQL虛擬機群'),t('oee','KER最新與每小時歷史'),t('wip','每天07:20快照'),l('freshness.html#architecture','來源架構與新鮮度'),l('freshness.html#decision','按工作需求選來源'),l('freshness.html#ai','異常後的資料時間'),l('freshness.html#history','歷史與現在'),l('freshness.html#join','欄位來源與時間對齊'),l('freshness.html#contract','資料契約'),l('er-atlas.html?view=questions','沿真實ER找證據'),l('tasks.html#group-report','多群與報表練習')],check:['G1有A，G2有A與B，兩群成員加總3代表3台機台嗎？',['是','不是；3個成員關係，聯集2台機台'],1,'先分清計數對象。多群比率也不能因此直接相加或平均。']},
 {id:9,title:'完成一個工作任務',question:'我能交付有證據、有時間的答案嗎？',prereq:[1,2,3,4,5,6,8],outcome:'說明已知、缺少證據、合理來源及下一步。',intro:'用新的條件檢查自己是否理解。遇到不足的來源，能清楚回答尚無足夠證據，也是資料判讀能力。',lessons:[l('tasks.html#not-running','Lot為什麼尚未進機'),l('tasks.html#find-carrier','FOUP當時在哪裡'),l('tasks.html#lot-history','Lot歷史與Move'),l('tasks.html#product-hold','產品攔截是否生效'),l('tasks.html#group-report','機群報表如何判讀')],check:['資料尚未涵蓋查詢期間，沒有查到事件就代表沒有事件嗎？',['不代表，應說明涵蓋缺口','代表事件數為零'],0,'未取得資料與事件不存在不同；結論要交代資料涵蓋及限制。']}
 ];
 const topicUnits={};units.forEach(u=>u.lessons.forEach(x=>{if(x.topic)topicUnits[x.topic]=u.id}));Object.assign(topicUnits,{lot:1,carrier:1,flow:2,portdata:null,retired:null});
 const routes={newcomer:{label:'新手完整路線',units:[0,1,2,3,4,5,6,7,8,9]},field:{label:'現場重點路線',units:[1,2,3,4,5,6,9]},data:{label:'資料分析路線',units:[1,2,3,6,7,8,9]}};
 const aliases={part:'Product PART 產品 mainpd_id Route',stage:'Module 黃光 Stage Step',portmode:'Port UP LOST 有貨 沒貨',wip:'KER_WIP_Y_BTH 07:20 每天 快照',mcs:'Macro Micro carrier transfer OHT 傳送',pd:'Process Definition PD',group:'KER 機群 Chamber',qtime:'Queue time Qtime 時間限制'};
 function locate(url){const u=new URL(url,location.href),file=u.pathname.split('/').pop();if(file==='er-atlas.html'&&u.searchParams.get('view')!=='questions')return null;if(file==='topic.html'){const n=topicUnits[u.searchParams.get('topic')];return n==null?null:units[n]}if(file==='learning.html'){const n=u.searchParams.get('unit');return n!==null?units[Number(n)]:null}return units.find(x=>x.lessons.some(l=>{const v=new URL(l.href,location.href);return v.pathname===u.pathname&&v.hash.split('?')[0]===u.hash.split('?')[0]}))||units.find(x=>x.lessons.some(l=>new URL(l.href,location.href).pathname===u.pathname));}
 function nextUnit(id,direction=1){let role='newcomer';try{role=JSON.parse(localStorage.getItem('mes-route'))||role}catch{}const order=routes[role]?.units.includes(id)?routes[role].units:routes.newcomer.units;return units[order[order.indexOf(id)+direction]]||null;}
 return {units,topicUnits,routes,aliases,locate,nextUnit};
})();
