'use strict';
// Each scene teaches one relationship. Wafer geometry and route identities remain data driven.
const wafer=(id,kind='')=>`<span class="silicon ${kind?`is-${kind}`:''}"><strong>${id||'空'}</strong></span>`;
const waferSet=(ids,done=[])=>`<div class="wafer-set">${ids.map(id=>`<div>${wafer(id,done.includes(id)?'good':'')}<small>${done.includes(id)?'✓ 本次完成':'晶圓身分'}</small></div>`).join('')}</div>`;
const scene=(id,title,body,conclusion)=>`<figure class="teaching-scene" data-scene="${id}" aria-label="${title}"><div class="scene-head"><h2>${title}</h2><small>教學示意 · 非量產操作規範</small></div>${body}<figcaption class="scene-verdict">${conclusion}</figcaption></figure>`;
const receipt=(id,state='Pass')=>`<span class="receipt ${state==='Fail'?'fail':/待|未|不足|需|尚/.test(state)?'missing':/Pass|完成|吻合|核准|已記錄|已保存|保留/.test(state)?'':'neutral'}">${id} · ${state}</span>`;
const route=(ids,current='',done=[],lot='L023',cls='')=>`<div class="route-track ${cls}">${ids.map(id=>`<div class="route-stop ${id===current?'current':done.includes(id)?'done':''}"><span class="route-dot">${done.includes(id)?'✓':id==='R10'?'↻':id.slice(1)}</span><strong>${id}</strong><small>${STEPS.find(s=>s.id===id)?.name||({R10:'重工清洗',S45:'新增檢查'}[id])||''}</small>${id===current?`<span class="lot-pin">● ${lot}</span>`:''}</div>`).join('')}</div>`;
const EXERCISES={
 port:{q:'換一個現場：Slot 07 顯示有片，但 Wafer ID 讀不到。可以把它當成 W07 嗎？',options:[['先重讀／依程序人工核對','可行。先保留「有片、身分未知」兩項原始證據，再用核准方法核實。多一道確認需要時間，但不能用片數補出身分。'],['直接判成錯片並換掉','證據還不夠。讀不到可能是讀取問題，也可能是身分問題；先隔離疑點、核對實物，不能憑空指定替代晶圓。']]},
 recipe:{q:'ETCH03 暫時無法使用；ETCH04 空著，而且配方名稱相同。這批急件要怎麼安排？',options:[['先查 ETCH04／腔體資格與配方版本','可行。若本站、產品、腔體及版本的核准條件全部一致，才可依程序改派。空閒與名稱相同只是候選條件，不是資格證據。'],['等待原設備恢復','若替代設備尚未取得資格，等待或申請工程確認都合理。代價是交期延後；不能為了快而省略版本與資格核對。']]},
 chamber:{q:'兩片成功返回，第三片 W08 仍在腔體中。此刻發生設備警報，你先做什麼？',options:[['保留三片位置及各自結果，啟動設備異常處置','合理。依現場安全程序處理 W08；前兩片成功證據保留，W08 結果仍待判。不能把整批標成功，也不能因整批故障抹掉前兩片紀錄。'],['整批重做，才能得到一致結果','尚不能如此決定。需先確認每片已接受的加工和重做風險，由工程決定整批或部分重工；多加工一次可能改變結果。']]},
 state:{q:'品質已確認沒有異常，工程 Hold 尚未解除。急件可以送入 Ready 的設備嗎？',options:[['先處理仍有效的工程 Hold','對。Q01 與 E02 是兩個獨立原因。Q01 的解除紀錄不能替 E02 作證；等工程批准後仍要做開工資格確認。'],['請主管加急處理工程確認','也是可行的加速方式。加速的是審查與排程，不是跳過限制；設備 Ready 仍不會自動解除 Lot Hold。']]},
 handoff:{q:'機台把同一個 Run 的 Done 又送了一次；W08 的結果仍未收到。要不要再做一次 Track-out？',options:[['依 Run／Visit 身分去重，補查 W08 結果','合理。同一事件不應重複計數或推兩站；先查設備原始紀錄及傳輸狀態。重送能修通訊缺口，但不能創造沒有的結果。'],['把第二次 Done 當作 W08 的結果','不可。Done 是 Run 事件，不是 W08 的逐片結果。混用證據會把資料缺漏藏起來。']]},
 stage:{q:'同一 Stage 裡有 S30 與 S40。S30 完成、S40 還在等待，這一段要回報什麼？',options:[['Stage B 進行中，必要 Step 完成 1／2','正確。分組是工作範圍，不會因進入或完成第一個 Step 就整段完成。還要保留 S40 的等待原因。'],['回報 Stage B 已進入，另列 S40 待做','若報表明確區分「已進入」與「已完成」，這樣也合理；不能把進入率當完成率。']]},
 step:{q:'R10 與 S10 都呼叫 CLEAN，且配方相同。能把 S10 的 Pass 當成 R10 已完成嗎？',options:[['不能，R10 建立自己的 Visit','對。同一 Operation／Recipe 可以重用，但前面的作業可能已改變晶圓。R10 是另一個位置、另一個執行時點，需要本次證據。'],['申請工程判斷是否可免做 R10','可提出申請，但必須有明確規則與替代證據，不能自行把 S10 的舊結果複製到 R10。這是例外處置，不是兩個位置相同。']]},
 'lot-flow':{q:'L023 的三片從 F012 換到 F018，L024 仍留在 F020。需要為 L023 重新套用 Flow 嗎？',options:[['更新承載關係，保留 L023 的 Flow 與進度','對。單純換載具沒有新增流程執行實例。仍須核對晶圓與槽位，且不改 L024 的獨立位置。'],['若同時改產品，先重新核對流程資格','合理的附加條件。換載具本身不改 Flow；若產品、成員或作業要求也改了，另依規則審查，不能混成一筆位置更新。']]},
 execution:{q:'S40 已加工完，但 MES 交易回覆逾時。操作員看到畫面還在 S40，要不要重新加工？',options:[['先用 Lot／Visit 查交易與設備紀錄','對。畫面沒更新可能是回覆遺失，不代表沒加工。查清已提交或待提交，再依程序重試交易；重新加工可能造成重複製程。'],['立即再送一次製程指令','不應依畫面逾時判斷。要分開「加工」與「交易」的重試，且以同一 Visit 關聯證據避免重複。']]},
 branching:{q:'量測值正好是 102，但儀器校驗已過期。可以直接採用圖中的合格分支嗎？',options:[['先確認結果有效性；不直接放行','對。98–102 的示例規則只在有效、完整量測下成立。數值在範圍內不能補儀器資格，先依品質程序覆核或重測。'],['安排有效設備重測','合理，但要先保留本次無效／待判的紀錄。重測增加等待及量測工作量，換來可以支持分支的證據。']]},
 rework:{q:'這批已用完一次核准重工，S50 複測還是 Fail。下一步是什麼？',options:[['保留第二次 Fail，轉工程處置','對。此次核准只涵蓋一次迴圈，不能沿用批准無限重跑。工程可能判報廢或另核准處置，需留下新依據。'],['如果很急，再跑同一重工一次','急件不是新的批准。多一次加工有製程風險；不應把第 2 次 Fail 清掉來重設次數。']]},
 'split-merge':{q:'兩個子批都到 S50，A 沒有 Hold，B 的品質 Hold 還在。是合批還是保持分開？',options:[['先保持分開，處理 B 的 Hold','正確。本例要求位置、版本及限制都相容。相同 S50 只通過其中一項；合批不能讓 B 的限制消失。'],['若產線另有核准的合批規則，依規則審查','有條件合理，但須明訂 Hold 如何繼承、哪些動作被限制及逐片追溯。本課未提供這條替代規則，不能自行放行。']]},
 versions:{q:'v2 的新增 S45 是品質必做項，而 L023 仍引用 v1。可以只發布新版就等它自動補做嗎？',options:[['不行，需評估並核准 L023 的遷移或其他處置','對。發布改的是定義；Lot 的既有參照仍是 v1。要核對所在位置、等效歷程與補做點，明確記錄誰批准。'],['先列出所有受影響的 v1 在製批次','這是合理的第一步。再按各批位置評估，可能有可遷移、需 Hold 或需其他處置的不同群組；不能只改全域版本字串。']]},
 'operations-lab':{q:'同一批同時遇到讀取不穩與設備等待，你會優先處理哪件事？',options:[['先核對身分，同時查可用設備','可並行查設備；身分未確認前不能開工。保留原始讀值，避免改派後把錯片一起帶到下一台。'],['先完成設備資格查詢，再核對身分','只要尚未放行加工，順序也可依人力調整。最後兩組證據都要成立；快一步查詢不能替另一組資格背書。']]},
 'flow-lab':{q:'急件只剩量測，但也已超過前段時間限制。要加速，應改哪件事？',options:[['加急工程處置並安排量測資源','合理。加速人的確認與資源安排；超時證據保留，不改開始時間，也不省略必要量測。'],['先列出時間、位置與 Hold，再評估替代路徑','也是合理順序。若有核准替代路徑，需驗證適用條件與追溯；本課沒有授權操作者任意跳站。']]},
};
function exercise(id){const e=EXERCISES[id];return `<section class="lesson-exercise" data-exercise="${id}"><h2>換個條件，你會怎麼判斷？</h2><p>${e.q}</p><div class="exercise-choices">${e.options.map(([label],i)=>`<button type="button" data-answer="${i}" aria-pressed="false">${label}</button>`).join('')}</div><div class="exercise-response" role="status" aria-live="polite"></div></section>`;}
function portScene(){return scene('port','片數相同，Slot 07 卻對不上',`<p class="scene-note">同一個 F012 在 ETCH03／LP1。逐槽對照預期與本次讀值；橘色列是要追查的位置。</p><div class="identity-grid"><div></div><div class="colhead">預期身分<small>Lot L023 的資料</small></div><div class="colhead">本次讀值<small>保留原始讀取</small></div>${['06','07','08'].map((n,i)=>`<div class="slot-label ${i===1?'mismatch':''}">Slot<b>${n}</b></div><div class="${i===1?'mismatch':''}">${wafer('W'+n)}<span class="match-label">預期 W${n}</span></div><div class="${i===1?'mismatch':''}">${wafer(i===1?'W99':'W'+n,i===1?'bad':'good')}<span class="${i===1?'diff-id':'match-label'}">${i===1?'≠ W07，需核對':'✓ 相符'}</span></div>`).join('')}</div><div class="focus-rule"><span>預期 3 片</span><b>＝</b><span>讀到 3 片</span><b>≠</b><span class="stop">身分全部正確</span></div>`,'先停在身分核對：重讀或人工確認 Slot 07。查清之前，不放行、不改寫預期 W07。');}
const portLesson=operationLessons.find(l=>l.id==='port');
portLesson.body=()=>portScene()+article('先定位差異，再選擇核對方式',`<p>Load Port（裝載埠）是載具交接的位置。到位訊息只證明 F012 到了 LP1；Mapping（槽位對照）回答哪些槽位有片；Wafer ID 讀取才提供晶圓身分。本例假設這三種資訊都能取得。</p><p>如果只是讀取不穩，依程序重讀能減少不必要的換料；如果實物真的不同，交由現場追查載具、批次及移片紀錄。兩種處置都先保留原始差異，不能拿預期值覆蓋讀值。</p>`)+exercise('port')+take('先確認「哪一片、在哪一槽」，才能繼續檢查本批的設備與配方資格。');
document.addEventListener('click',event=>{const b=event.target.closest('[data-answer]');if(!b)return;const box=b.closest('[data-exercise]');box.querySelectorAll('[data-answer]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));box.querySelector('.exercise-response').textContent=EXERCISES[box.dataset.exercise].options[Number(b.dataset.answer)][1];});

function station(slots,chamber,done=[]){return `<div class="station-line"><div><p class="object-label">FOUP F012 · 槽位展開示意 · 3 槽</p><div class="carrier-body"><div class="wafer-set">${Object.entries(slots).map(([slot,id])=>`<div>${wafer(id,!id?'empty':done.includes(id)?'good':'')}<small>Slot ${slot}</small></div>`).join('')}</div></div></div><div class="transfer-arrow" aria-label="晶圓往返交接">⇄</div><div><p class="object-label">ETCH03 · CH-A</p><div class="chamber-body">${wafer(chamber,chamber?'':'empty')}<div style="margin-top:10px;font-size:14px">${chamber?'目前在腔體':'目前無晶圓'}</div></div></div></div>`;}
const SCENE_FRAMES={
 chamber:[
  {label:'① W06 加工中',slots:{'06':null,'07':'W07','08':'W08'},chamber:'W06',done:[],status:'Processing',note:'Slot 06 已空；W06 只出現在 CH-A，沒有同時出現在兩處。'},
  {label:'② 片間等待',slots:{'06':'W06','07':'W07','08':'W08'},chamber:null,done:['W06'],status:'Processing',note:'W06 返回原槽。CH-A 暫時空，但本次 Lot 作業仍有兩片未完成。'},
  {label:'③ W07 加工中',slots:{'06':'W06','07':null,'08':'W08'},chamber:'W07',done:['W06'],status:'Processing',note:'這次空的是 Slot 07。W06 的成功保留；W08 還沒進入腔體。'},
  {label:'④ 全片返回',slots:{'06':'W06','07':'W07','08':'W08'},chamber:null,done:['W06','W07','W08'],status:'待資料確認',note:'三片都返回，僅證明實體加工完成；必要結果齊全、MES 交易成功後才能到 S50。'}
 ],
 state:[
  {label:'① 兩項 Hold',holds:['Q01 品質','E02 工程'],note:'設備 Ready；L023 仍被兩個原因限制，不能開工。'},
  {label:'② 品質解除',holds:['E02 工程'],note:'Q01 已解除，E02 仍有效。只處理一個原因不會清掉全部限制。'},
  {label:'③ 工程也解除',holds:[],note:'Lot 回到等待開工的 S40；仍要核對身分、Recipe 與設備資格。沒有自動加工或過站。'}
 ],
 execution:[
  {label:'① 等待開工',current:'S40',done:['S10','S20','S30'],status:'Queued',receipts:[],note:'本次 Visit 尚未開始；Current 指向應執行的 S40。'},
  {label:'② 開工',current:'S40',done:['S10','S20','S30'],status:'Processing',receipts:['Visit #1 開始'],note:'記錄 ETCH03、Recipe v2 與開始時間。Current 仍在 S40。'},
  {label:'③ 機台完成',current:'S40',done:['S10','S20','S30'],status:'待資料確認',receipts:['W06 Pass','W07 Pass','W08 待收'],note:'W08 結果缺少，無法提交成功的本站完成交易。機台 Done 不使指標前進。'},
  {label:'④ 完成交易',current:'S50',done:['S10','S20','S30','S40'],status:'Queued',receipts:['W06 Pass','W07 Pass','W08 Pass','S40 Visit #1 Pass'],note:'結果齊全、條件通過，保存 Visit 後才取得下一個位置 S50。'}
 ],
 split:[{label:'① 進度不同',aligned:false},{label:'② B 返回 S50',aligned:true}]
};
const controls=(id,items)=>`<div class="scene-controls" role="group" aria-label="切換作業快照">${items.map((f,i)=>`<button data-frame="${id}" data-frame-index="${i}" aria-pressed="${i===0}">${f.label}</button>`).join('')}</div>`;
function chamberFrame(i){const f=SCENE_FRAMES.chamber[i];return station(f.slots,f.chamber,f.done)+`<div class="scene-kpis"><div><small>本次成功返回</small><strong>${f.done.length}／3 片</strong></div><div><small>Lot 的 S40 作業</small><strong>${f.status}</strong></div><div><small>目前流程位置</small><strong>S40</strong></div></div><p class="scene-note">${f.note}</p>`;}
function stateFrame(i){const f=SCENE_FRAMES.state[i];return `<div class="traveler-pair"><div class="equipment-status"><h3>Equipment · ETCH03</h3><div class="chamber-body">${wafer(null,'empty')}<div class="object-label">CH-A · 目前無 Run</div></div><p class="scene-note"><span class="state-badge">Ready</span> 設備可接受合格工作</p></div><div class="traveler"><h3>Lot · L023 · S40</h3>${waferSet(['W06','W07','W08'])}<span class="state-badge ${f.holds.length?'warn':''}">${f.holds.length?'Hold':'Queued · 待開工'}</span><div class="interlock">${['Q01 品質','E02 工程'].map(h=>`<div class="${f.holds.includes(h)?'blocked':''}"><strong>${f.holds.includes(h)?'▣':'✓'} ${h}</strong><small>${f.holds.includes(h)?'仍有效，阻止執行':'已解除，留有紀錄'}</small></div>`).join('')}</div><p>${f.note}</p></div></div>`;}
function executionFrame(i){const f=SCENE_FRAMES.execution[i];return `<p class="scene-note">固定定義：F-DEMO v1；藍色標記是 L023 的目前位置。</p>${route(['S30','S40','S50'],f.current,f.done,'L023','execution-track')}<div class="scene-kpis"><div><small>Current</small><strong>${f.current}</strong></div><div><small>RunState</small><strong>${f.status}</strong></div></div><div class="receipt-set">${f.receipts.map(t=>receipt(t,t.includes('待收')?'待收':'已記錄')).join('')}</div><p class="scene-note">${f.note}</p>`;}
function splitFrame(i){const aligned=SCENE_FRAMES.split[i].aligned;return `<div class="genealogy-parent"><h3>父批 L023 · 原 3 片</h3>${waferSet(['W06','W07','W08'])}<small>拆批後保留譜系；停止作為活躍批次</small></div><div class="genealogy-branches"><div><h3>L023-A</h3>${waferSet(['W06','W07'])}<span class="lot-pin">S50 · 等待量測</span></div><div><h3>L023-B</h3>${waferSet(['W08'])}<span class="lot-pin">${aligned?'S50 · 等待量測':'R10 · 重工支線'}</span></div></div><div class="join-gate ${aligned?'ready':''}"><strong>${aligned?'✓ 本例可核准合為 L023-M':'尚不能合批：S50 ≠ R10'}</strong>${aligned?'同產品、版本、位置，皆等待且無 Hold；三片身分不重疊。':'先讓 B 完成核准重工並回 S50，再核對其餘合批條件。'}</div><p class="scene-note">活躍晶圓數 = A 的 2 片 + B 的 1 片 = 3。父批只保留歷史，不另外多算 3 片。</p>`;}
const frameRenderers={chamber:chamberFrame,state:stateFrame,execution:executionFrame,split:splitFrame};
document.addEventListener('click',event=>{const b=event.target.closest('[data-frame]');if(!b)return;const id=b.dataset.frame;const fig=b.closest('.teaching-scene');fig.querySelectorAll('[data-frame]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));fig.querySelector('[data-frame-body]').innerHTML=frameRenderers[id](Number(b.dataset.frameIndex));});

const REMADE={
 recipe:{course:'operations',scene:()=>scene('recipe','開工資格：三把鑰匙都要吻合',`<div class="step-passport"><div class="step-stamp"><span>F-DEMO v1</span><b>S40</b><span>ETCH · 蝕刻</span></div><div class="passport-fields"><div><small>這批的需求</small><strong>L023 · P-DEMO</strong></div><div><small>核准設備／腔體</small><strong>ETCH03／CH-A</strong></div><div><small>要求的 Recipe</small><strong>ETCH-DEMO／v2</strong></div><div><small>本次執行身分</small><strong>S40 · Visit #1</strong></div></div></div><div class="run-lane"><div class="run-event"><time>候選 A</time><div><strong>ETCH03 + v1 → 版本不符</strong><div class="receipt-set">${receipt('設備資格','Pass')}${receipt('v1 ≠ v2','Fail')}</div></div></div><div class="run-event"><time>候選 B</time><div><strong>CVD02 + v2 → 設備不符</strong><div class="receipt-set">${receipt('成膜 ≠ 蝕刻','Fail')}${receipt('配方字串','相同也不足')}</div></div></div><div class="run-event"><time>候選 C</time><div><strong>ETCH03／CH-A + v2 → 資格吻合</strong><div class="receipt-set">${receipt('本站資格','Pass')}${receipt('版本 v2','Pass')}</div></div></div></div>`,'Recipe 名稱不等於核准版本；機台空閒不等於有資格。按 Lot 的本站要求逐項核對。'),text:`<p>Step 是「要做哪一次作業」，Operation 是作業種類，Recipe（配方）是設備執行的方法與參數版本。S40 呼叫 ETCH，不代表能隨意挑一個同名配方。</p><p>配方內還可能有抽氣、穩定、加工與吹掃等子步驟；那是一次設備程序，不會把 Lot 從 S40 連跳四站。資格必須對到產品、設備／腔體與核准版本；本例不提供真實參數。</p>`,heading:'把流程位置與設備內部程序分開'},
 chamber:{course:'operations',scene:()=>scene('chamber','跟著 W06 → W07 → W08，逐片看位置',controls('chamber',SCENE_FRAMES.chamber)+`<div data-frame-body aria-live="polite">${chamberFrame(0)}</div>`,'同一時刻每片只有一個有效位置。Chamber 暫時空，不表示 Lot 的這次作業已完成。'),text:`<p>本例是單片加工：一次只有一片在 CH-A。展開「資料對照與狀態練習」，切換四個時刻，可以看到空槽跟著取出的晶圓改變。綠框只表示該片在本次作業完成；沒有綠框的其他片不能借用它的結果。</p><p>需要按 Wafer ID 收齊各自結果；如果中途故障，先保存每片已完成、未開始或待判的狀態，再由工程決定後續。本次三片都返回後，也還要核對資料與 MES 交易。</p>`,heading:'為什麼要保存每片，而不只保存一個 Done？'},
 state:{course:'operations',scene:()=>scene('state','Ready 是設備的狀態；Hold 是這批的限制',controls('state',SCENE_FRAMES.state)+`<div data-frame-body aria-live="polite">${stateFrame(0)}</div>`,'解除一個原因只移除一個限制。全部解除後仍留在 S40，等待正常開工。'),text:`<p>同一現場有不同對象：Equipment 是否可接工作、Lot 是否允許執行、Wafer／Run 加工到哪裡。把三者都縮成一個「正常／異常」，會失去判斷依據。</p><p>本例 Q01 是品質複核、E02 是工程確認。品質人員解除 Q01，不會代替工程人員完成 E02；設備 Ready 更不能代替任何一個批准。反過來，解除 Hold 也不會把中斷的加工改成 Pass。</p>`,heading:'一個狀態，必須先說明它屬於誰'},
 handoff:{course:'operations',scene:()=>scene('handoff','三片返回之後，還要把證據交接完整',`<div class="run-lane"><div class="run-event"><time>10:00</time><div><strong>S40 · Visit #1 開始</strong><p>綁定 L023、ETCH03／CH-A、Recipe v2 與本次 3 片。</p></div></div><div class="run-event"><time>10:06</time><div><strong>機台 Done · 3 片返回</strong>${waferSet(['W06','W07','W08'],['W06','W07','W08'])}<div class="receipt-set">${receipt('W06')}${receipt('W07')}${receipt('W08','待收')}</div><span class="state-badge warn">Current 仍為 S40</span></div></div><div class="run-event"><time>10:07</time><div><strong>補齊 W08 原始結果</strong><div class="receipt-set">${receipt('W06')}${receipt('W07')}${receipt('W08')}</div><p>核對片數、身分及本次 Visit，不借用其他批的結果。</p></div></div><div class="run-event"><time>10:08</time><div><strong>MES 完成交易成功</strong>${route(['S40','S50'],'S50',['S40'])}<p>S40 的結果已保存；L023 在 S50 等待量測。</p></div></div></div>`,'Done、逐片結果、MES 完成交易是不同證據。資料齊全並完成交易後，才推進下一站。'),text:`<p>Track-in 是本例開始一次作業的交易；Track-out 是本站條件通過後的完成交易。本課假設 Track-out 成功時同時推進下一站，其他 MES 可能把 Complete、Track-out 與 Move-next 分開。</p><p>通訊缺漏時，優先按 Run／Visit 查原始紀錄並重送必要資料；不能把第二次 Done 當新片數，也不能因画面沒更新就重新加工。同一結果重送應辨識為同一事件，避免重複推進。</p>`,heading:'實體作業與資料交易，各自有自己的完成條件'},
 stage:{course:'flow',scene:()=>scene('stage','L023 做完 S40：一段完成，整條還沒完成',`<p class="scene-note">這是做完 S40、已到 S50 等待的快照。外層是 F-DEMO v1；三段色帶是不同目的的 Stage。</p><div class="route-groups">${[['A · 準備',['S10','S20']],['B · 圖形',['S30','S40']],['C · 確認',['S50','S60']]].map(([name,ids])=>`<section class="route-group"><h3>Stage ${name}</h3>${route(ids,'S50',['S10','S20','S30','S40'])}</section>`).join('')}</div><div class="progress-pair"><div><h3>只問 Stage B</h3><div class="meter-line"><progress max="2" value="2" aria-label="Stage B 完成 2 站，共 2 站"></progress><strong>2／2</strong></div><p>S30、S40 都完成，圖形這一段完成。</p></div><div><h3>問整條 Flow</h3><div class="meter-line"><progress max="6" value="4" aria-label="Flow 完成 4 站，共 6 站"></progress><strong>4／6</strong></div><p>S50、S60 還沒完成，不能回報整批結案。</p></div></div>`,'先說清完成的範圍：Step 是一站，Stage 是一段，Flow 是整條路徑。'),text:`<p>Stage 用共同目的把 Step 分組，幫助新手先看全局。例如「圖形」包含微影與蝕刻，兩者協力完成一段工作；它不是一台設備，也不是只做一次加工。</p><p>本例每個 Stage 的必要 Step 全部完成才算該階段完成。實際 Fab 可能另有 Stage 級資格、排程或完成規則；要看公司資料定義。展開資料對照後的 4／6 是站數示例，不是工時、良率或產品完成百分比。</p>`,heading:'先掌握分組目的，再展開必要作業'},
 step:{course:'flow',scene:()=>scene('step','同樣是 CLEAN，S10 與 R10 是不同位置',`<div class="step-passport"><div class="step-stamp"><span>F-DEMO v1</span><b>S40</b><span>一次流程位置</span></div><div class="passport-fields"><div><small>所屬分組</small><strong>Stage B · 圖形</strong></div><div><small>作業種類 Operation</small><strong>ETCH</strong></div><div><small>設備群</small><strong>ETCH</strong></div><div><small>Recipe 版本</small><strong>ETCH-DEMO／v2</strong></div></div></div><div class="traveler-pair"><div class="traveler"><h3>最初的清洗</h3>${route(['S10','S20'],'S10',[])}<div class="receipt-set">${receipt('S10 Visit #1')}</div><p>位置 S10 呼叫 CLEAN，這份 Pass 只屬於這次執行。</p></div><div class="traveler teal"><h3>後來的核准重工</h3>${route(['R10','S50'],'R10',[])}<div class="receipt-set">${receipt('R10 Visit #1','待收')}</div><p>同樣呼叫 CLEAN；晶圓已經歷其他作業，需新的執行證據。</p></div></div>`,'Operation 可以共用；Flow 版本＋Step 位置＋Visit，才能指到正確的一次執行。'),text:`<p>Occurrence 是「出現位置」。同一種 Operation 可在一條路上出現多次，每次位置有自己的前後條件。Visit 則是 Lot 實際走訪該位置的一次紀錄：回到 S50 複測時，位置仍是 S50，但新增 Visit #2。</p><p>三層問題要分開：Step 問本批現在應做哪站；Operation 問作業種類；Recipe 問設備如何執行。只用「清洗」作識別，會把不同時間和目的的結果混在一起。</p>`,heading:'位置與走訪次數，為什麼要同時保存？'},
 'lot-flow':{course:'flow',scene:()=>scene('lot-flow','一份流程定義，兩批獨立的旅程',`<div class="binding-definition"><h3>F-DEMO · v1 · 已核准</h3><p>P-DEMO 適用；起點 S10，必要路徑與分支規則固定在此版本。</p></div><div class="binding-stem">↙ 分別參照同一版本 ↘</div><div class="traveler-pair"><div class="traveler"><h3>● L023</h3><p>FlowRef：F-DEMO v1</p>${route(['S30','S40','S50'],'S40',['S30'])}${waferSet(['W06','W07','W08'])}<p>Current：S40 · Queued<br>載具 F012；進度只屬於 L023。</p></div><div class="traveler teal"><h3>◆ L024</h3><p>FlowRef：F-DEMO v1</p>${route(['S10','S20','S30'],'S10',[],'L024')}${waferSet(['W21','W22'])}<p>Current：S10 · Queued<br>載具 F020；尚未開始第一站。</p></div></div>`,'套用時保存產品、核准 Flow 版本與起點；之後每批各自更新 Current、狀態與 Visit。'),text:`<p>Flow 定義像共用作業路線；Lot 執行實例是某一批與這份路線的連結。建批時先核對產品適用性及發布狀態，再建立起點與初始狀態。圖中兩批參照相同 v1，卻有不同 Current，說明進度沒有存進共用定義裡。</p><p>換 FOUP 改的是承載位置。L023 搬到 F018 不會重設為 S10，也不會改動 L024。拆批則會建立新的 Lot 身分及譜系，是另一種有成員規則的交易。</p>`,heading:'把共用定義、批次進度與載具位置分開'},
 execution:{course:'flow',scene:()=>scene('execution','同一條路不變，L023 的位置要憑證據前進',controls('execution',SCENE_FRAMES.execution)+`<div data-frame-body aria-live="polite">${executionFrame(0)}</div>`,'開工改執行狀態；完成交易才改目前位置。前次歷程一直保留。'),text:`<p>Current 是目前應執行的位置摘要，Visit 是這次做了什麼的證據。從 Queued 到 Processing，Current 仍為 S40；只有本站必要結果齊全並通過規則，才提交完成並取得 S50。</p><p>資料庫更新需要保持一致：結果、完成狀態與下一站不能只成功一半。這裡展示交易語意，不預設你的 MES 用一張表或哪種鎖。若回覆逾時，要先查同一 Visit 的提交結果，不直接再加工。</p>`,heading:'目前位置是摘要，歷程解釋它如何形成'},
 branching:{course:'flow',scene:()=>scene('branching','同樣從 S50 出發，先看證據是否有效',`<div class="decision-origin">${waferSet(['W08'])}<h3>S50 · 量測判斷</h3><p class="scene-note">可追算教學規則：有效線寬 98–102 nm（含邊界）合格；單位與門檻是本課假設，不是實廠規格。</p><div class="measure-range"><div class="measure-band"></div><div class="measure-pin" style="--at:40%">100</div><div class="measure-pin" style="--at:90%">105</div></div></div><div class="branch-paths"><div class="branch-path"><h3>有效、完整，值 100</h3><strong>合格 → S60</strong><p>100 在允收區間，保存結果後依規則前往結案。</p></div><div class="branch-path warn"><h3>有效、完整，值 105</h3><strong>不合格 → Hold</strong><p>105 超出範圍，Current 保留 S50；工程評估，不自動重工。</p></div><div class="branch-path wait"><h3>缺值／無效結果</h3><strong>未能判定 → 補查</strong><p>不能當成 Pass 或 Fail；在 S50 補足有效證據。</p></div></div>`,'先驗證資料，再判斷範圍，最後選去向。「不知道」不是不合格，更不是合格。'),text:`<p>分支規則要有輸入、判斷條件與合法去向。圖中的三種情況是同一判斷點的替代結果，不是三批互相流入，也不是先 Pass 再 Fail 的串接過程。</p><p>缺資料可先查傳輸或重測；有效不合格則交工程處置。兩者都可能讓這批等待，但原因、責任與需要的證據不同。是否能重工、報廢或特採，須依核准規則。</p>`,heading:'結果不完整與結果不合格，需要不同的接手動作'},
 rework:{course:'flow',scene:()=>scene('rework','返回 S50 時，增加 Visit，不抹掉 Fail',`<div class="loop-road"><div class="loop-point"><h3>S50 · 第一次量測</h3>${wafer('W08')}<div class="receipt-set" style="justify-content:center">${receipt('Visit #1','Fail')}</div><span class="state-badge warn">L023 · 品質 Hold</span></div><div class="transfer-arrow">→</div><div class="loop-point"><h3>核准 RW-001 → R10</h3>${wafer('W08')}<p>重工清洗 · 最多 1 次<br>指定返回 S50</p></div><div class="loop-return">R10 完成後，返回 S50 建立 Visit #2</div></div><div class="branch-paths" style="grid-template-columns:repeat(2,minmax(0,1fr))"><div class="branch-path"><h3>Visit #2 = Pass</h3><strong>依規則 → S60</strong><div class="receipt-set">${receipt('#1','Fail')}${receipt('#2','Pass')}</div></div><div class="branch-path warn"><h3>Visit #2 = Fail</h3><strong>停止迴圈 → 工程處置</strong><div class="receipt-set">${receipt('#1','Fail')}${receipt('#2','Fail')}</div></div></div>`,'重工批准要帶路徑、次數與返回點。新結果和原始失敗並存，不能以重工清空歷史。'),text:`<p>重工包含四件事：保存原始失敗、批准適用的處置、執行受控支線、回指定位置重新驗證。本例 R10 呼叫 CLEAN，但不主張清洗能修復任意不合格；這裡只用它教路徑管理。</p><p>批次仍是 L023。S50 Visit #1 = Fail、R10 Visit #1 與 S50 Visit #2 都留在同一批的歷程。再失敗時不能把 Current 隨手改回 R10，否則迴圈上限與批准範圍失去意義。</p>`,heading:'重工是受控的新增歷程，而不是倒轉畫面'},
 'split-merge':{course:'flow',scene:()=>scene('split-merge','分的是 Lot 身分，三片晶圓不會變六片',controls('split',SCENE_FRAMES.split)+`<div data-frame-body aria-live="polite">${splitFrame(0)}</div>`,'先守住成員不重複，再比對版本、位置、狀態與限制。到同一站仍不代表一定能合批。'),text:`<p>本例 A 保留 W06、W07，B 帶 W08 走核准重工。拆批後原 L023 保留父子譜系，兩個活躍子批各自管理進度；是否同時換載具是另一件事。</p><p>整批等待可減少拆合批交易與管理成本；只讓異常片分流可避免其他片跟著等待，但需要逐片追溯、父子關係及合批資格。沒有可用的拆批規則時，不能只在畫面把晶圓拖出去。</p><p>本例合批需同產品、Flow 版本、Current、等待狀態且沒有 Hold。B 回 S50 後才可以進行其他條件核對；合成 L023-M 後，每片仍可反查原父批與子批。</p>`,heading:'什麼時候整批等，什麼時候值得拆開？'},
 versions:{course:'flow',scene:()=>scene('versions','發布 v2 與遷移 L023，是兩件事',`<div class="version-lane"><strong>已在製 L023 · 仍引用 v1</strong>${route(['S40','S50','S60'],'S50',['S40'],'L023')}</div><div class="version-lane"><strong>新版 v2 · 多了一個 S45 檢查</strong>${route(['S40','S45','S50','S60'],'S45',['S40'],'遷移後 L023')}</div><div class="migration-arrow"><strong>核准遷移的映射：</strong>v1／S50 → v2／S45<br>前提：本例已完成 S40、尚未開始 S50；工程確認歷程等效並核准補做新增檢查。</div><div class="receipt-set">${receipt('舊 v1 歷程','保留')}${receipt('v2 參照','新記錄')}${receipt('遷移批准','需保存')}</div><p class="scene-note">第二條是核准遷移後的另一個時刻，不是發布就自動改變。新投入 L024 依產品設定套用已核准 v2，從 S10 開始。</p>`,'發布更新可用定義；遷移才更新特定 Lot 的參照與位置。沒有批准，不自動換路線。'),text:`<p>維持 v1 能避免在製批次的作業要求突然改變，但若新增檢查是必要品質處置，需主動查受影響批次，不能只發布 v2。遷移則需要比較舊位置、新位置、已做作業的等效性與待補證據。</p><p>同樣地，跳站與時間限制都不是任意改欄位。必要 S50 不能因急件省略；Q-time（兩個指定事件間的最長等待時間）也不因 Hold 自動停止。練習以 S20 完成到 S30 開始上限 30 分鐘示範，超時保留原時間，由工程處置。</p>`,heading:'改版要處理在製批次的實際位置與成本'}
};
for(const [id,c] of Object.entries(REMADE)){const lesson=(c.course==='operations'?operationLessons:flowLessons).find(l=>l.id===id);lesson.body=()=>c.scene()+article(c.heading,c.text)+exercise(id);}

REMADE.step.scene=()=>scene('step','作業種類相同，完成證據不能互相借用',`<div class="binding-definition"><h3>Operation：CLEAN · 清洗</h3><p>同一種可重用作業；下面是 L023 的兩個不同時刻。</p></div><div class="binding-stem">同一 Operation，分別被不同位置呼叫</div><div class="traveler-pair"><div class="traveler"><h3>較早：S10 已完成</h3>${route(['S10','S20'],'S20',['S10'])}<div class="receipt-set">${receipt('S10 · Visit #1')}</div><p>準備階段的清洗已完成，當時進入 S20。這份結果屬於 S10。</p></div><div class="traveler teal"><h3>較晚：核准進入 R10</h3>${route(['R10','S50'],'R10',[])}<div class="receipt-set">${receipt('R10 · Visit #1','待收')}</div><p>之後已經歷其他作業；R10 是重工位置，需建立新的清洗證據。</p></div></div><div class="focus-rule"><span>S10 #1 Pass</span><b>≠</b><span>R10 #1 已完成</span></div>`,'用 Flow 版本＋Step 位置＋Visit 定位一次執行；只看 CLEAN 名稱會混淆不同歷程。');
REMADE.stage.text+=`<p>回報整段進度時用 Stage，能減少閱讀大量站點的負擔；追查停滯或缺少證據時展開 Step。只報「Stage B 進行中」不足以知道卡在 S30 還是 S40；只列所有 Step 又會讓新手失去工作目的。兩種層級各自回答不同問題。</p>`;
REMADE.step.text+=`<p>依 Operation 統計可比較同類作業的工作量；依 Step／Visit 查詢才能追到某批某次執行。前者方便彙總，後者需要保存更多關聯，卻能避免把不同時間的結果混用。</p>`;

function labScene(s,key,scenarioId,instruction){
 const heading=key==='operations'?'現場快照：物件在哪裡，還缺什麼？':'批次旅程：位置、限制與歷程';
 let body='';
 if(key==='operations'){
  if(scenarioId==='arrival'){
   const stops=['STK01','OHT01','ETCH03／LP1'];
   body=`<div class="route-track">${stops.map((id,i)=>`<div class="route-stop ${s.location===id?'current':''}"><span class="route-dot">${i+1}</span><strong>${id}</strong><small>${['暫存','搬送中','核准裝載埠'][i]}</small>${s.location===id?'<span class="lot-pin">F012 在這裡</span>':''}</div>`).join('')}</div><div class="carrier-body">${waferSet(s.waferIds)}</div><p class="scene-note">同一 F012 的位置改變；三片成員與 L023／S40 保持不變。</p>`;
  }else if(scenarioId==='reconcile'){
   body=`<p class="scene-note">F012 · 預期槽位與本次讀取分開；未讀到不等於空槽。</p><div class="identity-grid"><div></div><div class="colhead">預期</div><div class="colhead">本次讀取</div>${Object.entries(s.slots).map(([slot,id],i)=>{const read=s.scan[i].split('=')[1],match=read===id;return `<div class="slot-label ${match?'':'mismatch'}">Slot ${slot}</div><div class="${match?'':'mismatch'}">${wafer(id)}</div><div class="${match?'':'mismatch'}">${read==='未讀到'?'<strong class="diff-id">？ 未讀到</strong>':wafer(read,match?'good':'bad')}<small>${match?'✓ 相符':'需核對'}</small></div>`;}).join('')}</div>`;
  }else if(scenarioId==='recipe'){
   body=`<div class="step-passport"><div class="step-stamp"><span>L023</span><b>S40</b><span>ETCH</span></div><div><div class="receipt-set">${receipt('需求 ETCH-DEMO/v2','核准')}</div><div class="receipt-set">${receipt('目前 '+s.recipe,s.recipe.endsWith('/v2')?'版本吻合':'Fail')}</div><p class="scene-note">${s.status.includes('資格已確認')?'設備與腔體資格也已确认；可進入開工程序。':'版本吻合後，仍需確認 ETCH03／CH-A 的設備資格。'}</p></div></div>`;
  }else{
   const completed=scenarioId==='run'||scenarioId==='fault'?s.waferIds.slice(0,Number.parseInt(s.count||'0')):[];
   body=station(s.slots,s.chamber,completed);
   if(scenarioId==='run'||scenarioId==='fault')body+=`<div class="receipt-set">${s.waferIds.map(id=>receipt(id,s.missing?.includes(id)?'待收':completed.includes(id)?'本次完成':s.chamber===id?'腔體內，結果待判':'未完成')).join('')}</div>`;
  }
 }else if(s.lots){
  body=`<p class="scene-note">父批 ${s.lot} 保留譜系，不再作為活躍批次。</p><div class="genealogy-branches">${s.lots.map(l=>`<div><h3>${l.id}</h3>${waferSet(l.wafers)}<span class="lot-pin">${l.current} · Queued</span></div>`).join('')}</div><div class="join-gate ${s.lots[0].current===s.lots[1].current?'ready':''}"><strong>${s.lots[0].current===s.lots[1].current?'位置已對齊，可核對合批條件':'位置不同，不能立刻合批'}</strong>活躍成員 2 + 1 = 3；每片只屬於一個子批。</div>`;
 }else if(s.flow==='尚未套用'){
  body=`<div class="binding-definition"><h3>P-DEMO → 已核准 F-DEMO v1</h3><p>先核對產品與發布狀態</p></div><div class="binding-stem">↓ 合格後才建立執行參照</div><div class="traveler"><h3>L023 · Created</h3>${waferSet(s.waferIds)}<span class="state-badge warn">尚未套用 Flow；Current 未建立</span></div>`;
 }else{
  const ids=s.current==='R10'?['R10','S50']:s.flow.endsWith('v2')?['S10','S20','S30','S40','S45','S50','S60']:['S10','S20','S30','S40','S50','S60'];
  body=`<p class="scene-note">${s.flow} · ${s.lot} 的位置與完成紀錄</p>${route(ids,s.current,s.done,s.lot)}${s.current==='R10'?`<div class="migration-arrow">R10 完成後返回 S50。${s.visits?.includes('S50 #1 = Fail')?'原 S50 Fail 保留。':'S10 舊 Pass 不能取代 R10 本次證據。'}</div>`:''}${s.current==='結束'?'<div class="join-gate ready"><strong>✓ 六站都有完成紀錄 · 本教學 Flow 完成，非 Lot E 出貨</strong></div>':''}`;
 }
 if(s.hold.length)body+=`<div class="interlock">${s.hold.map(h=>`<div class="blocked"><strong>▣ ${h}</strong><small>仍有效 · 需各自處置</small></div>`).join('')}</div>`;
 if(s.qtime!==undefined)body+=`<div class="meter-line"><strong>已過 ${s.qtime} 分鐘</strong></div><div class="qtime-track" aria-label="0 至 60 分鐘刻度；已過 ${s.qtime} 分鐘，上限 30 分鐘"><span style="width:${s.qtime/60*100}%;background:${s.qtime>30?'#ba6d32':'#278775'}"></span><i>30 分上限</i><small>0</small><small>60 分</small></div><p class="scene-note">S20 完成 → S30 開始；30 分鐘為本例上限。${s.qtime>30?'已超時，原始時間仍保留。':'尚在時間範圍內；其他資格仍需符合。'}</p>`;
 if(s.visits)body+=`<div class="lab-evidence"><strong>歷程證據</strong><div class="receipt-set">${s.visits.split('；').map(v=>receipt(v,v.includes('Fail')?'Fail':v.includes('尚未')?'待收':'已保存')).join('')}</div></div>`;
 if(s.otherLot)body+=`<div class="lab-evidence"><strong>另一批不跟著改動</strong><p>${s.otherLot}</p></div>`;
 if(s.migration)body+=`<div class="migration-arrow">${s.migration}<br>原版本歷程保留；本批要先補 S45。</div>`;
 if(s.genealogy)body+=`<div class="lab-evidence"><strong>逐片來源仍可反查</strong><p>${s.genealogy}</p>${waferSet(s.waferIds)}</div>`;
 return scene(key+'-lab',heading,body,`${s.lot} · ${s.current} · ${s.status}${s.count?' · 本次完成 '+s.count:''}<br>${instruction}`).replace('class="teaching-scene"','class="teaching-scene lab-story"');
}
for(const key of ['operations','flow']){
 const lesson=(key==='operations'?operationLessons:flowLessons).find(l=>l.id==='lab');
 lesson.lead='先看現場／旅程快照，再選動作。每個選擇會更新同一份狀態，並保留事件與拒絕原因；重設可比較另一條路。';
 lesson.body=()=>`<div id="scenario-lab"></div>${exercise(key+'-lab')}`;
}
