'use strict';
const lessons=[
{id:'2671',title:'Lot 在哪裡？先分清批次、盒子與設備',short:'Lot 與載具',intro:'Lot 是追蹤生產的一批晶圓；FOUP 是裝晶圓的實體盒子。記錄它們之間的關係，才能把「這批貨」轉成現場可找到的位置。',links:[['index.html#lot','Lot 與 FOUP'],['operations.html#port','Port 交接']],cases:[
{q:'L023 現在裝在哪個 FOUP？',physical:'現場人員要找的是裝著這批晶圓的盒子。Lot 的身分與盒子的身分各自存在；換盒不等於換了一批貨。',record:['追蹤對象|Lot L023','裝載關係（示例）|FOUP F012'],take:'先找 Lot 與 FOUP 的裝載關係，再查這個 FOUP 所在位置。',nodes:['lot','cast-link','cast','slot'],rows:[['批次','Siview.Frlot','描述 Lot；批次身分不等於載具編號。'],['裝在哪個盒子','Siview.Frcast_lot ↔ Siview.Frcast','原圖以「放在」連結 Lot 與 FOUP。這是先追裝載關係的線索。'],['FOUP 內容物歷史','Siview.fhwlths','記錄在各時間點 FOUP 放了哪些 Wafer；每次 Split／Merge 進 FOUP 時更新，查詢時須對應時間。']],limit:'圖未提供完整鍵值及有效起迄，不能假設用 Lot_ID 連完就必然只有一筆、或把舊裝載關係當目前位置。'},
{q:'預派到機台，就代表已到站嗎？',physical:'「預計去哪一台」是安排；「盒子已在機台旁」是位置；「Lot 已開始加工」又是另一個事件。三者不能互相代替。',record:['預派機台（示例）|ETCH-03','現場交接（示例）|尚待確認'],take:'有預派資料，只能支持預派關係；接著核對位置、交接與加工事件。',nodes:['cast','predispatch','eqp','location'],rows:[['預派','SIVIEW.CSFRPREDISPATCH','表示派工系統預先安排 Lot 的目標機台；Lot 是主要對象，FOUP 是輔助關聯。'],['所在設備','Siview.CSFHDOPHS ↔ Siview.freqp','原圖另以「位於」建立關係；應與預派分開看。'],['Port／Lot','Siview.Port ↔ Siview.Freqp_Lot','原圖標「EI 在」；這是廠內關係標籤，不能自行展開 EI 的交易定義。']],limit:'原圖未證明 EI、實體抵達與加工開始的事件邊界；目前位置需另查資料時間。'}],quiz:['Lot 已被派工系統預派 ETCH-03，能否直接告訴同事「正在加工」？','可以，預派就是開始','不能，還要確認位置與加工事件',1,'預派是目標安排；要確認加工，需能支持該作業已開始的有效事件或狀態。']},
{id:'2672',title:'現在的位置，與曾經發生的事',short:'歷史與 Move',intro:'同一批 Lot 可以有很多動作、很多次過站，以及多筆搬送記錄。這些表回答的工作問題不同，直接串接也可能把同一件事重複展開。',links:[['support.html#move','Move 計數'],['advanced.html#qtime','QTime']],cases:[
{q:'一批貨重工後，Move 要算幾次？',physical:'L023 正常過站一次，再重工過站一次。兩次是不同的過站事件，即使批次身分相同，Move 仍算兩次。',record:['不同 Lot|1 批 L023','已成立過站事件|2 個 Lot Move'],take:'Move 計 Lot 過站事件；重工計入，同一事件重送不增加事件數。',nodes:['lot','move-link','move','history','all-actions'],rows:[['批次身分','Siview.Frlot','用於識別你追蹤的那批貨。'],['過站歷史','F12DM.DM_Move_Step_bth','圖上透過 Lot_id 對應機台 Move；計數前要核對事件唯一性與成立規則。'],['所有動作','Siview.FHOPEHS_S','圖上「Lot 所有動作」比過站更廣，不能每一列都直接加成 Move。']],limit:'將多筆動作歷史與多筆 Move 只按 Lot 連接可能增加列數。需先確定各表粒度、事件鍵及所需時間範圍。'},
{q:'想追 QTime，還是追搬送延誤？',physical:'Lot 在受時間限制的站點等待，與 FOUP 被搬運途中延誤，是兩個可能相關但不同的問題。先找站點時間，再以載具與搬送工作追運輸過程。',record:['製程問題|Lot／站點／時間限制','搬送問題|Carrier／搬送工作'],take:'製程歷史以 Lot 與站點追；搬送歷史另沿 Carrier 與工作記錄追。',nodes:['step','qtime-link','qtime','cast','mcs-transfer','mcs-history'],rows:[['站點與 Qtime','F12DM.DM_Lot_step_st ↔ F12DM.DM_Qrest_Hist_BTH','原圖列 Lot_ID、Ope_no 作為關聯線索；循環／重工時還需識別正確那一次執行。'],['MES 搬送歷史','Mfg_Carrier_te_ut','圖中以 Carrier_id 連到 FOUP。'],['MCS 搬送歷史','carrier_job_history@mcsdb / transfer_job_history@mcsdb','圖中列 Carrier_id、transfer_job_id；查明是哪一個搬送工作。']],limit:'不能把搬送完成直接等同 Move Out；QTime 的開始／停止事件也必須依廠內定義確認。'}],quiz:['只按 Lot 把多筆 Move 與所有動作連接，列數變多。該怎麼辦？','直接把查到的列數當 Move','先確認事件鍵與資料粒度，再計算',1,'Join 的列數不一定等於現場事件數。先釐清一列代表什麼，避免重複計數。']},
{id:'2673',title:'Lot 走到哪裡，與流程定義分開看',short:'Flow 與 Part',intro:'Flow 說明允許的路徑與站點，Lot 說明某批貨的執行脈絡。Part、PD、LR 和機台對應，則提供產品與加工定義的線索。',links:[['flow.html#lot-flow','Lot 套用 Flow'],['advanced.html#part-route','Part／RouteId'],['advanced.html#future-hold','Future Hold']],cases:[
{q:'同一個 Flow，兩批 Lot 能在不同站嗎？',physical:'L023 與 L024 可使用同一流程定義，但一批仍在前站，另一批已到後站。共同的路徑不代表共同的進度。',record:['流程定義（示例）|同一條路徑','執行位置（示例）|L023：S50／L024：S40'],take:'流程定義提供路徑；目前站點必須回到那批 Lot 的有效執行資料確認。',nodes:['lot','flow-link','flow','part','part-link','stage-link','stage'],rows:[['Lot 與 Flow','Siview.frlot ↔ F12DM.DM_Flow_step_Bt','原圖以 Part、Mainpd_id 標示 Flow 定義關係，不代表圖已列出完整目前站點查法。'],['Part 與 PD','Siview.frprodspec / Siview.frpd','分別在圖中標為 PART 定義及 Flow PD；具體版本、鍵與廠內命名需查字典。'],['Stage 與 Module','F12dm.dm_tbl_info_stage','提供站點分段的定義線索；Stage 名稱不等於 Lot 的即時位置。']],limit:'不能把所有 Flow 定義列當成這批 Lot 已執行的歷史；圖未列出的 RouteId 與 Mainpd_id 等價關係也不能自行假定。'},
{q:'預估到站時間，就是已到站嗎？',physical:'排程推估 L023 稍後到 S60，並不表示它現在已離開 S50。未來路徑、到站預估與真正過站要用不同證據支持。',record:['到站預估（示例）|10:30 到 S60','實際過站|尚待事件確認'],take:'Forecast 用來預期；實際到站與過站用有效的現況或事件記錄確認。',nodes:['lot','forecast-link','forecast','stream-link','stream','future','future-link'],rows:[['未來路徑','F12dm.dm_tbl_lot_forecast','原圖標示「未來的 Flow」，不當成已發生歷史。'],['到站時間','Stream_fcst_lot_st','原圖標 Stream 到站時間；需確認預估更新時間與適用批次／站點。'],['Future Hold','Siview.frlot_futurehold','未來指定條件的 Hold 安排，與現在是否已 Hold 分開查。']],limit:'圖中也列 SRTS 抽測跳站設定，但沒有提供完整跳站條件；不能只看設定表存在就說該 Lot 必然跳站。'}],quiz:['預估顯示 L023 10:30 到 S60，是否可宣告 S50 已完成？','不可以，需確認實際過站事件','可以，Flow 已列出 S60',0,'路徑、預估時間與真實事件各有責任。不能用未來安排補足缺少的完成事件。']},
{id:'2674',title:'一台機台，有多個需要分開看的層次',short:'EQP 與 Chamber',intro:'設備、Load Port、Chamber 與其細部資料描述不同對象。找到了機台，不代表已找到特定 Chamber 的狀態或加工資格。',links:[['operations.html#chamber','Chamber'],['support.html#monitor','Daily MON／EMS']],cases:[
{q:'主機可用，指定 Chamber 就能加工嗎？',physical:'一台設備可能有多個 Chamber；主機層級資料不能代替指定腔體的狀態。Daily MON 與其他條件也需對準適用的設備範圍。',record:['主機身分（示例）|EQP-01','加工資源（示例）|Chamber C2'],take:'查詢要對準實際加工的資源層级，別把主機狀態套到所有 Chamber。',nodes:['eqp','chamber-link','chamber','detail-link','chamber-detail'],rows:[['主機','Siview.Freqp','原圖中心 EQP。'],['Chamber 狀況','Siview.csfrprcrsc / SIVIEW.FHCSCHS','原圖另列 Chamber 狀況，不能用主機結果替代。'],['Chamber 細部','Siview.frprcrsc','圖中細部關係列 eqp_id、procrsc_id；查資料時要辨識正確資源。']],limit:'這張圖未提供 EMS 的表或放行規則。已知 Daily MON 逾期會阻擋加工，但不能由這張 ER 圖推導解除條件。'},
{q:'要找機台在哪一區，還是 FOUP 放在哪？',physical:'設備所在廠區位置、Load Port 的交接位置，以及 OHB／儲位的配置是不同層次。「機台在哪」不等於「盒子現在在哪」。',record:['設備位置問題|哪個 Bay／管理歸屬','載具位置問題|目前在哪個交接或儲放位置'],take:'設備位置與載具位置分開追，再確認它們在同一時間點的對應。',nodes:['eqp','bay-link','bay','owner','port','udata','ohb-eqp','ohb-status'],rows:[['機台位置／管理','MFG_EQP_BAY_BT / MFG_EQP_OWNER_BT','原圖分別連向機台位置、機群與課別。'],['Load Port','SIVIEW.FRPORT / SIVIEW.FRPORT_UDATA','交接位置與細部資料；圖列 D_THESYSTEMKEY，不自行改成別的鍵。'],['OHB 配置與狀況','Siview.csfrohb_eqp / Siview.csfrohb / SIVIEW.CSFROHB_CFG','圖把設備對應、狀況與 BMIR 設定分開；具體 OHB／BMIR 業務字典需依廠內定義。']],limit:'有配置關係不代表當下實體佔用；這張圖也沒有保證 Port、OHB 與載具位置會同步刷新。'}],quiz:['EQP 查詢正常，但 C2 狀態尚未確認，能否放行指定 C2 作業？','可以，主機正常即可','仍需查 C2 與適用的監控／加工條件',1,'主機、加工資源與放行條件是不同層次；要對準這次實際使用的 Chamber。']},
{id:'2675',title:'WIP 與 OEE：先問時間，再問統計對象',short:'WIP 與 OEE',intro:'這張圖把批次、機群、機台及期間統計接起來。讀之前先問：這筆是現在的記錄、固定時點快照，還是一段期間的彙總？',links:[['freshness.html','資料新鮮度'],['support.html#move','Lot Move']],cases:[
{q:'每天 07:20 的 WIP，能代表現在嗎？',physical:'KER_WIP_Y_BTH 每天早上07:20保存機群狀況與相關KPI；快照可回看當時資料，不能直接當作目前即時狀況。',record:['使用者確認的快照時間|每天 07:20','現在的位置|另查有效現況'],take:'每日快照回答當時的機群與KPI；現在的行動需要符合時效的資料。',nodes:['wip-history','wip-link','lot','move','history'],rows:[['圖中 WIP','KER_WIP_BT','原圖中心標 Lot；名字本身不保證刷新頻率。'],['固定時點 WIP','KER_WIP_Y_BTH','使用者確認：每天早上07:20保存機群狀況與KPI。'],['過站／動作歷史','F12DM.DM_Move_Step_bth / Siview.FHOPEHS_S','追快照之後發生的事件，仍需核對資料截止時間。']],limit:'ER 圖沒有各表的更新延遲；即使都能在同一查詢環境取得，也不能假設 freshness 一樣。'},
{q:'機台現在 UP，代表整天 AVL 都高嗎？',physical:'UP 是你們廠內「正在加工」的狀態；Lost 是機台閒置。AVL 是一定期間的 Availability 比率，單一時刻不能代替整段期間。',record:['當下狀態（廠內）|UP：正在加工／Lost：閒置','期間指標|AVL：期間 Availability'],take:'先分清機台或機群、時點或期間，才比較資料；OEE、AVL 與 Eff 不直接畫等號。',nodes:['eqp','status-link','status','eqp-oee-link','eqp-oee','group-oee','group-history','virtual'],rows:[['機台狀況','KER_EQP_STATUS_BT','圖中用 EQP_ID 對應目前機況。'],['機台／機群 OEE','Ker_Eqp_Aaa_Oee_Ut / ker_dm_bt / Ker_Dm_Hourly_Bth','圖分機台歷史、機群目前、機群歷史；比較前要對齊粒度與期間。'],['機群／虛擬群組','KER_EMP_EQP_GRP_CAP_UT / KER_VR_EQP_GRP_DETAIL_BT','原圖列 EQP_GRP 與 DYNAMIC_SQL。需先確定群組包含哪些機台，避免重複統計。']],limit:'AVL 的分子／分母、Eff 的公式，以及 MON／PM 如何歸類尚未確認。本頁不計算假設公式，也不宣稱 OEE 表能直接提供 AVL。'}],quiz:['同一時刻機台是 UP，能否推出當天 AVL=100%？','不能，仍需整段期間及計算定義','能，UP 就代表全時可用',0,'當下狀態不代表期間比率；AVL 公式需依廠內定義，不能從 OEE 表名推算。']},
{id:'2676',title:'從設備往下找：哪個 Port、哪個盒子、哪批 Lot？',short:'設備到 Lot',intro:'這張簡圖適合把第一課的物件串起來：設備有交接位置與加工資源，載具則透過裝載關係連到 Lot。',links:[['index.html#fab','現場實物與資料'],['operations.html#handoff','交接與完成']],cases:[
{q:'同在一台設備，Port 與 Chamber 是同一件事嗎？',physical:'Port 是載具與設備交接的入口；Chamber 是加工資源。FOUP 在 Port，不代表其中所有晶圓都已進入 Chamber。',record:['交接入口|PORT_ID','加工資源|CHAMBER ID'],take:'設備下的不同分支代表不同對象；不要把交接位置當成加工位置。',nodes:['eqp','eqp-id','port','chamber'],rows:[['設備','FREQP / EQP_ID','以設備身分建立查詢起點。'],['交接位置','FRPORT / PORT_ID','回答是哪個 Port；圖中的 FRPORT_UDATA 是另一個細部資料對象。'],['加工資源','FRPRCRSC / CHAMBER ID','回答是哪個 Chamber；此簡圖沒有逐片傳送路徑。']],limit:'此圖沒有 Lot 內逐片 Wafer 的位置追蹤；不能由 FOUP 已在 Port 推論所有 Wafer 同時加工。'},
{q:'看見盒子，如何找出是哪批貨？',physical:'現場看見載具，要透過裝載關係找批次；再看這批貨的製程狀態。載具身分、Lot 身分及 Lot 製程狀態是不同資料。',record:['實體載具（示例）|FOUP F012','批次（示例）|Lot L023'],take:'盒子 → 裝載關係 → Lot → 製程狀態；每一步要查對時間與身分。',nodes:['cast','cast-lot','lot','status'],rows:[['載具','FRCAST / CAST_ID','對應圖中的載具身分。'],['載具與 Lot','FRCAST_LOT','原圖中的關係節點；仍需字典確認實際 Join 欄位。'],['Lot 製程狀態','FRLOT → LOT Process Status','圓形標籤表示要看的狀態意義，不足以證明狀態欄位就叫 LOT Process Status。']],limit:'不能把 ER 的說明文字直接當實際欄位名稱；狀態值、更新時間及裝載變動都需核對。'}],quiz:['圖中的「LOT Process Status」可直接當 SQL 欄位名嗎？','可以，圖上有寫就是欄位','不可以，還要查欄位字典',1,'圖示可幫助理解狀態的意義，但沒有證明實際 schema 的欄位拼字。']},
{id:'2677',title:'配方與機台的對應，不等於實際加工紀錄',short:'PD、ER 與設備',intro:'這張圖能看出 PD、ER 與機台之間的關係，以及設備位置和狀態的資料來源。真正執行了哪份 Physical Recipe，仍要由加工紀錄確認。',links:[['advanced.html#recipes','LR／ER／Physical Recipe'],['operations.html#recipe','加工前配方核對']],cases:[
{q:'有 ER 與機台對應，就證明這批使用過它嗎？',physical:'定義可對應哪些機台，是配置；某批晶圓這一次實際用哪個 Recipe 加工，是執行事實。必須把這次 Lot、設備和加工時間對起來。',record:['配置問題|Recipe 與哪些設備對應','執行問題|這次加工實際使用哪份 Recipe'],take:'配方對應支持配置判讀；Actual Recipe 需另找該次加工的執行證據。',nodes:['recipe','recipe-key','recipe-eqp','er','lr','eqp-id'],rows:[['ER 線索','FRMRCP → ER','原圖明示 ER 關聯；ER 的參數與版本字典未列出。'],['Recipe 與設備','FRMRCP_EQP / SYSTEMKEY / EQP_ID','對應關係不代表已執行，也不代表當下具備所有加工資格。'],['LR／EQP 關係','DM_FLOW_LR_EQP_BT','圖由 ER 連到這張表；未提供一對一基數或完整轉換規則。']],limit:'這七張 ER 圖沒有完整呈現 Physical Recipe 的實際執行紀錄；不能宣稱 LR、ER、Physical Recipe 必然同名或一對一。'},
{q:'PD 對到機台後，還能再查什麼？',physical:'先找到定義關聯的設備，再分別查設備在哪與目前狀態。符合配置、能找到設備，以及現在可以加工，仍是三個不同問題。',record:['位置|哪個區域／位置','狀態|這台設備目前如何'],take:'配置找到候選設備；位置幫你找到它；狀態與適用條件才支持下一步判斷。',nodes:['pd','pd-key','pd-eqp','eqp-id','bay','location','eqp','status'],rows:[['PD 對設備','FRPD / FRPD_EQP / MODULEPD_ID','原圖列 systemkey 與 EQP_ID 路徑；不在這裡自行定義 PD 等於哪一層 Route。'],['設備位置','MFG_EQP_BAY_BT','連向 EQP LOCATION PHASE，對應空間／廠區位置的線索。'],['設備狀態','FREQP','連向 EQP STATUS；現況可用於判讀，但仍要看時間與作業資格。']],limit:'有設備狀態不是完整 Auto Control 授權。設備、Recipe、產品、監控與 Hold 的適用條件必須各自確認。'}],quiz:['FRMRCP_EQP 有對應機台，可否把它當作 Lot 實際加工 Recipe 的證據？','不可以，還需這次加工的執行紀錄','可以，配置存在就代表已使用',0,'配置與執行事實分開；要證明實際使用，需對應該次加工的 Lot、設備、時間與 Recipe。']}
];
const $=id=>document.getElementById(id);let active,caseIndex=0,originalBox,svgDoc,scale=1,generation=0;
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function focusMap(all=false,nodeId=null){if(!svgDoc)return;const svg=svgDoc.documentElement,ids=nodeId?[nodeId]:active.cases[caseIndex].nodes;svgDoc.querySelectorAll('#nodes>g').forEach(g=>{g.style.opacity=all||ids.includes(g.id)?'1':'.28';const shape=g.querySelector('.shape');if(shape)shape.style.stroke=all?'':ids.includes(g.id)?'#126eca':'';});let box=originalBox;if(!all){const boxes=ids.map(id=>svgDoc.getElementById(id)?.getBBox()).filter(Boolean);if(boxes.length){const x=Math.min(...boxes.map(b=>b.x))-45,y=Math.min(...boxes.map(b=>b.y))-45;box=[x,y,Math.max(...boxes.map(b=>b.x+b.width))-x+45,Math.max(...boxes.map(b=>b.y+b.height))-y+45];}}svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.setAttribute('viewBox',box.join(' '));scale=1;zoom();$('map-caption').textContent=nodeId?'逐點讀圖：'+svgDoc.getElementById(nodeId).querySelector('text').textContent+'。這是局部節點；點「聚焦這個問題」查看整段關係。':all?'完整原圖：矩形是圖中資料對象，菱形標關係／鍵的線索；沒有標出的基數與條件不補猜。':'目前聚焦：'+active.cases[caseIndex].q+'　藍色為相關節點；原圖連線保留。';}
function zoom(){const o=$('er-object');o.style.width=scale*100+'%';o.style.height=scale*100+'%';$('zoom-value').textContent=Math.round(scale*100)+'%';}
function nodeButtons(){if(!svgDoc)return;const c=active.cases[caseIndex];$('node-buttons').innerHTML=c.nodes.map(id=>{const n=svgDoc.getElementById(id);return n?`<button data-node="${id}">${esc(n.querySelector('text').textContent)}</button>`:''}).join('');document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>focusMap(false,b.dataset.node));}
function renderCase(){const c=active.cases[caseIndex];document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.case===caseIndex));$('case-content').innerHTML=`<section class="meaning"><p class="eyebrow">現場意義 → 資料判讀</p><h2>${esc(c.q)}</h2><p class="physical">${esc(c.physical)}</p><div class="record">${c.record.map(r=>{const [label,value]=r.split('|');return `<div><small>${esc(label)}</small><strong>${esc(value)}</strong></div>`}).join('')}</div><p class="provenance">以上編號與情境為教學示例，沒有連接真實 MES。</p><div class="arrow-note">${esc(c.take)}</div></section><h2>把現場問題對到資料</h2><div class="mapping">${c.rows.map(([title,table,meaning])=>`<article><h3>${esc(title)}</h3><div><code>${esc(table)}</code><p>${esc(meaning)}</p></div></article>`).join('')}</div><div class="caution"><strong>查詢前還要確認</strong><p>${esc(c.limit)}</p></div>`;nodeButtons();focusMap(false,innerWidth<800||active.id==='2674'?c.nodes[0]:null);}
function render(){const token=++generation;active=lessons.find(l=>l.id===location.hash.slice(1))||lessons[0];caseIndex=0;svgDoc=null;$('map-nav').innerHTML=lessons.map(l=>`<a href="#${l.id}" ${l===active?'aria-current="page"':''}>${l.short}</a>`).join('');const original=new URLSearchParams(location.search).get('view')==='original';for(const [id,view] of [['original-part','original'],['questions-part','questions']]){const a=$(id);a.href=`?view=${view}#${active.id}`;if(original===(view==='original'))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');}if(original){renderOriginal();return;}$('content').innerHTML=`<p class="eyebrow">FAB × DATA / ER ${active.id}</p><h1>${active.title}</h1><p class="intro">${active.intro}</p><p class="provenance">依已校字 ER ${active.id} 導讀 · 表名取自原圖，業務邊界另作說明</p><div class="question-tabs">${active.cases.map((c,i)=>`<button data-case="${i}" aria-pressed="${i===0}">${c.q}</button>`).join('')}</div><div id="case-content" aria-live="polite"></div><section class="map-panel"><h2>沿著原圖找證據</h2><div class="map-tools"><button id="focus-map">聚焦這個問題</button><button id="all-map">看完整圖</button><button id="zoom-out" aria-label="縮小">−</button><output id="zoom-value">100%</output><button id="zoom-in" aria-label="放大">＋</button><a href="ER/NEW/${active.id}.svg" target="_blank" rel="noopener">另開 SVG</a><a href="ER/NEW/${active.id}.svg" download>下載</a><a href="ER/NEW/index.html#${active.id}">對照原照片</a></div><div class="node-row"><strong>逐點讀圖</strong><div id="node-buttons"></div></div><div class="map-scroll"><object id="er-object" type="image/svg+xml" aria-label="ER ${active.id} 可縮放關係圖"><a href="ER/NEW/${active.id}.svg">開啟原圖</a></object></div><div class="map-caption" id="map-caption">載入關係圖…</div></section><section class="quiz"><p class="eyebrow">換個情境判斷</p><h2>${active.quiz[0]}</h2><button data-answer="0">${active.quiz[1]}</button><button data-answer="1">${active.quiz[2]}</button><div class="feedback" role="status" id="feedback"></div></section><div class="related">${active.links.map(([url,label])=>`<a href="${url}">回到教學：${label} →</a>`).join('')}</div><p class="caution">讀任何一張表都先問：一列代表什麼？記錄哪個時間？更新延遲多少？原圖尚未列出各表 freshness，不能直接套用 Native 或 Mart 的等級。<a href="freshness.html">回看資料新鮮度 →</a></p>`;
document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{caseIndex=+b.dataset.case;renderCase()});document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{$('feedback').textContent=(+b.dataset.answer===active.quiz[3]?'判斷正確。':'再分清資料的責任。')+active.quiz[4]});$('focus-map').onclick=()=>focusMap();$('all-map').onclick=()=>focusMap(true);$('zoom-in').onclick=()=>{scale=Math.min(4,scale+.5);zoom()};$('zoom-out').onclick=()=>{scale=Math.max(1,scale-.5);zoom()};const object=$('er-object');object.onload=()=>{if(token!==generation)return;try{svgDoc=object.contentDocument;if(!svgDoc?.documentElement||svgDoc.documentElement.tagName.toLowerCase()!=='svg')throw Error();originalBox=svgDoc.documentElement.getAttribute('viewBox').split(/\s+/).map(Number);nodeButtons();focusMap(false,innerWidth<800?active.cases[caseIndex].nodes[0]:null);}catch(e){$('map-caption').textContent='無法聚焦原圖，可使用「另開 SVG」查看完整資料關係。'}};object.data=`ER/NEW/${active.id}.svg`;renderCase();}

function renderOriginal(){
 $('content').innerHTML=`<p class="eyebrow">01 原圖 / ER ${active.id}</p><h1>${active.short}</h1><p>完整呈現已校字的 SVG 關係圖，保留所有節點與連線。可放大查看細節，或對照原始照片。</p><section class="map-panel"><div class="map-tools"><button id="original-fit">完整圖</button><button id="original-minus">− 縮小</button><output id="original-scale">100%</output><button id="original-plus">＋ 放大</button><a href="ER/NEW/${active.id}.svg" target="_blank" rel="noopener">另開原圖</a><a href="ER/NEW/${active.id}.svg" download>下載 SVG</a></div><div class="map-scroll original-scroll"><object id="original-object" data="ER/NEW/${active.id}.svg" type="image/svg+xml" aria-label="完整 ER ${active.id}"></object></div></section><details class="original-photo"><summary>對照原始照片（未修改）</summary><a href="ER/ORG/${active.id}.jpg" target="_blank" rel="noopener"><img src="ER/ORG/${active.id}.jpg" alt="ER ${active.id} 原始照片" loading="lazy"></a></details><p class="related"><a href="?view=questions#${active.id}">前往這張圖的聚焦題目 →</a></p>`;
 let z=1;const o=$('original-object');const resize=()=>{o.style.width=z*100+'%';o.style.height=z*100+'%';$('original-scale').textContent=Math.round(z*100)+'%';};o.onload=()=>{const svg=o.contentDocument?.documentElement;if(svg?.tagName.toLowerCase()==='svg'){svg.setAttribute('width','100%');svg.setAttribute('height','100%');}};$('original-fit').onclick=()=>{z=1;resize()};$('original-plus').onclick=()=>{z=Math.min(6,z+.5);resize()};$('original-minus').onclick=()=>{z=Math.max(1,z-.5);resize()};
}
window.addEventListener('hashchange',render);render();
