'use strict';
const freshChapters=[
 ['architecture','同一個 Giga，不同的新鮮度','先看來源與查詢入口'],
 ['decision','晚十分鐘，會做錯事嗎？','用工作需求選來源'],
 ['ai','案例一：AI 發現異常之後','舊 Step 會導向錯誤決策'],
 ['history','案例二：經過，不等於現在','History 與 Current State'],
 ['join','案例三：表剛刷新，欄位仍舊','追到 Column 的來源時間'],
 ['contract','把判斷寫進 Data Contract','四句話與查詢前檢查']
];
const freshState={source:'native',tolerance:'monitor',decision:'analysis',history:'event',complete:'yes',refreshed:false,quiz:null};
const fresh$=s=>document.querySelector(s);
const rowsTable=(head,rows)=>`<div class="table-scroll" tabindex="0" role="region" aria-label="資料對照表，可橫向捲動"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>`<td data-label="${head[i]}">${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const select=(id,label,options,value)=>`<label class="select-field" for="${id}"><span>${label}</span><select id="${id}">${options.map(([v,t])=>`<option value="${v}" ${value===v?'selected':''}>${t}</option>`).join('')}</select></label>`;
const freshnessViews=freshnessV2;
fresh$('#freshness-root').innerHTML=`<header class="topbar"><a class="brand" href="index.html"><b>M</b><span><small>MES LEARNING LAB</small>從現場認識資料</span></a><div class="course-tabs"><a href="index.html">01 基本物件</a><a href="operations.html">02 設備與現場</a><a href="flow.html">03 Flow 與 Lot</a><a href="freshness.html" aria-current="page">04 資料新鮮度</a></div><button class="button mobile-menu" id="fresh-menu" aria-expanded="false" aria-controls="sidebar">課程目錄</button></header><div class="shell"><aside id="sidebar"><p class="eyebrow">第四部分 · DATA FRESHNESS</p><h2 class="sidebar-title">你查到的是<br>哪個時刻？</h2><nav aria-label="本課章節">${freshChapters.map(([id,title,sub],i)=>`<a href="#${id}" data-chapter="${id}"><span>${String(i+1).padStart(2,'0')}</span><div>${title}<small>${sub}</small></div></a>`).join('')}</nav><div class="aside-foot">架構 → 選擇原則 → 三個案例<br>依你提供的環境條件製作</div></aside><main id="content" tabindex="-1"><div class="crumb">MES 入門教學 ／ 第四部分</div><div class="page-meta"><span class="pill">資料新鮮度</span><span id="fresh-progress"></span></div><article id="fresh-lesson" class="lesson"></article><div class="footer-nav"><button class="button" id="fresh-prev">← 上一段</button><span id="fresh-footer"></span><button class="button primary" id="fresh-next">下一段 →</button></div><p class="page-foot">教學案例為假設資料；未連線或執行真實 MES 查詢與控制。</p></main></div>`;
function updateDecision(){const v=freshState.decision;document.querySelectorAll('[data-level]').forEach(e=>e.classList.toggle('selected',e.dataset.level===v));fresh$('#decision-answer').textContent={analysis:'選 Data Mart：分析期間固定後，檢查資料已收齊。整理過的指標與歷史比當下一筆狀態更合適。',monitor:'先選 SiView Native：需求容許 3 分鐘，但仍須看本次來源時間；管線異常或資料過期時不能只相信 RT1 標籤。',control:'選 TX／核准控制交易：取得當下狀態，並在執行 Auto Hold 時重新驗證。近即時的三分鐘差距可能改變可執行條件。'}[v];}
function updateAI(){const v=freshState.source,control=freshState.tolerance==='control';const r={native:['Giga Report / SiView Native','ETCH','10:00',1],mart:['Giga Report / Data Mart','DEV','09:51',10],tx:['TX → MMDB','ETCH','10:01',0]}[v];fresh$('#query-source').textContent=r[0];fresh$('#query-step').textContent=r[1];fresh$('#query-time').textContent=r[2];fresh$('#query-age').textContent=r[3]+' 分鐘';fresh$('#age-fill').style.width=r[3]*10+'%';fresh$('#age-fill').className=r[3]>3?'old':'';fresh$('#query-step').className=v==='mart'?'old-text':'';fresh$('#ai-answer').textContent=v==='mart'?(control?'這是 09:51 的 DEV，不能當成 10:01 的位置。現在要 Auto Hold，改由 TX／核准控制交易取得當下狀態，並在執行時重驗條件。':'這是 09:51 的 DEV，不能當成 10:01 的位置。改找 Native 或 TX；Mart 的歷史內容本身沒有因此變錯。'):control?(v==='tx'?'TX 在本例回傳 10:01 的 ETCH；Auto Hold 仍須在核准交易執行時重驗條件，不能把查詢當成狀態鎖定。':'這筆 ETCH 是一分鐘前，符合一般監看卻不滿足當下控制要求。改由 TX／核准交易取得並重驗狀態。'):(v==='tx'?'這筆即時資料足以支持本次監看；若需求容許三分鐘，Native 通常更符合一般查詢路徑。':'這筆資料年齡一分鐘，小於本例可容忍的三分鐘，適合這次工程監看；不把此結論延伸為控制授權。');}
function updateHistory(){const complete=freshState.complete==='yes';const coverage=document.querySelector('#coverage-fill');if(coverage)coverage.style.width=complete?'100%':'50%';fresh$('#history-coverage').textContent=complete?'昨日已收齊':'只涵蓋至昨日 14:00';fresh$('#history-record').innerHTML=complete?'<div class="event-row"><time>昨日 14:20</time><b>A123</b><span>DEV · Move Out</span><strong>已收錄</strong></div>':'<div class="event-row incomplete"><b>查無 DEV 事件</b><span>14:20 尚未在已涵蓋期間內</span></div>';fresh$('#history-answer').textContent=freshState.history==='current'?'事件簿只能說明發生過什麼，不能證明現在仍在 DEV。Current State 請改查 Native／TX，並驗證時間。':complete?'可以回答：昨天有經過 DEV；14:20 的事件已收錄。這個答案不表示 A123 現在仍在 DEV。':'不能回答「沒經過」。目前只收至 14:00，14:20 事件可能尚未載入；等待補齊或查核事件來源。';}
function updateJoin(){fresh$('#join-refresh-time').textContent=freshState.refreshed?'10:01':'10:00';fresh$('#join-answer').textContent=freshState.refreshed?'刷新完成只更新載入時間。Hold 的來源仍是 09:51，內容仍舊十分鐘；不能用它證明現在沒有 Hold。':'同一列：Step 是一分鐘前，Hold 是十分鐘前。點「重新刷新」看看：如果上游還沒更新，欄位年齡不會重設。';fresh$('#refresh-table').disabled=freshState.refreshed;}
function renderFresh(){let id=location.hash.slice(1)||'architecture';if(!freshnessViews[id])id='architecture';const i=freshChapters.findIndex(c=>c[0]===id);fresh$('#fresh-lesson').innerHTML=freshnessViews[id]();fresh$('#fresh-progress').textContent=`${i+1} / 6`;fresh$('#fresh-footer').textContent=freshChapters[i][1];fresh$('#fresh-prev').disabled=i===0;fresh$('#fresh-next').textContent=i===5?'回到開頭 ↺':'下一段 →';document.querySelectorAll('[data-chapter]').forEach(a=>{if(a.dataset.chapter===id)a.setAttribute('aria-current','step');else a.removeAttribute('aria-current');});document.title=freshChapters[i][1]+'｜資料新鮮度';fresh$('#sidebar').classList.remove('open');fresh$('#fresh-menu').setAttribute('aria-expanded','false');if(id==='decision')updateDecision();if(id==='ai')updateAI();if(id==='history')updateHistory();if(id==='join')updateJoin();enhanceFreshLesson(id);fresh$('#fresh-prev').onclick=()=>location.hash=freshChapters[Math.max(0,i-1)][0];fresh$('#fresh-next').onclick=()=>location.hash=freshChapters[(i+1)%6][0];}
document.addEventListener('change',e=>{const map={'decision-purpose':['decision',updateDecision],'ai-source':['source',updateAI],'ai-tolerance':['tolerance',updateAI],'history-question':['history',updateHistory],'history-complete':['complete',updateHistory]};if(map[e.target.id]){const [key,fn]=map[e.target.id];freshState[key]=e.target.value;fn();}});
document.addEventListener('click',e=>{if(e.target.id==='refresh-table'){freshState.refreshed=true;updateJoin();}if(e.target.id==='reset-join'){freshState.refreshed=false;updateJoin();}if(e.target.dataset.freshQuiz!==undefined){freshState.quiz=Number(e.target.dataset.freshQuiz);document.querySelectorAll('[data-fresh-quiz]').forEach(b=>b.setAttribute('aria-pressed',String(b===e.target)));fresh$('#quiz-answer').textContent=['合理。先補來源與時間，決策若要求當下狀態，透過 TX／核准交易重驗。增加查核工作，避免用舊狀態控制。','也合理。暫停有時間成本，但在來源時間不明時，比猜測安全；工程確認仍要補足資料來源、時間與交易條件。','不成立。10:01 是整表載入時間，不能證明 Hold 的來源狀態也是 10:01。應追到欄位 lineage。'][freshState.quiz];}});
fresh$('#fresh-menu').onclick=()=>{const open=fresh$('#sidebar').classList.toggle('open');fresh$('#fresh-menu').setAttribute('aria-expanded',String(open));};document.addEventListener('keydown',e=>{if(e.key==='Escape'){fresh$('#sidebar').classList.remove('open');fresh$('#fresh-menu').setAttribute('aria-expanded','false');}});window.addEventListener('hashchange',()=>{renderFresh();window.scrollTo(0,0);fresh$('#content').focus({preventScroll:true});});renderFresh();
