'use strict';
// Each lesson pairs a visual explanation with a decision the learner can inspect.
const freshArt = {
  architecture: ['architecture-desktop-v3.png','architecture-mobile-v3.png','MMDB 經 Reporting 分流到 Native 與 Mart；同一個 Giga 可以查到不同時間的資料。'],
  decision: ['decision-desktop-v2.png','decision-mobile-v2.png','昨天產量、可容忍延遲的監看、當下控制，需要不同的來源與驗證條件。'],
  ai: ['ai-desktop-v2.png','ai-mobile-v2.png','Lot A123 已在 ETCH；10:01 查詢時，Native 是 ETCH@10:00，Mart 仍是 DEV@09:51。'],
  history: ['history-desktop-v3.png','history-mobile-v1.png','A123 昨天離開 DEV 的事件被保留，今天的目前位置已在 ETCH；查無事件還要看涵蓋期間。'],
  join: ['join-desktop-v2.png','join-mobile-v1.png','Step 與 Hold 各自保留來源時間；整表重新載入不會更新尚未改變的上游資料。'],
  contract: ['contract-desktop-v1.png','contract-mobile-v1.png','把查詢結果追到欄位來源、資料時間與用途，再交給下一位工程師。']
};
const freshFigure = id => `<figure class="lesson-art" data-fresh-art="${id}"><picture><source media="(max-width:700px)" srcset="assets/freshness-v2/${freshArt[id][1]}"><img src="assets/freshness-v2/${freshArt[id][0]}" alt="${freshArt[id][2]}" fetchpriority="high"></picture><figcaption><span>AI 教學插畫 · 假設案例</span><button type="button" class="art-expand" data-fresh-zoom="${id}" aria-label="放大${freshChapters.find(c=>c[0]===id)[1]}插畫">檢視完整圖 ↗</button></figcaption></figure>`;
const freshIntro = (k,title,lead) => `<div class="lesson-kicker">${k}</div><h1>${title}</h1><p class="lead">${lead}</p>`;
const activity = (title,description,body) => `<section class="fresh-activity"><div class="activity-heading"><span class="activity-mark" aria-hidden="true">↳</span><div><p class="activity-label">動手看差異</p><h2>${title}</h2></div></div><p class="activity-intro">${description}</p>${body}</section>`;
const detail = (title,body) => `<details class="fresh-detail"><summary>${title}</summary><div class="detail-body">${body}</div></details>`;
const takeaway = text => `<p class="lesson-takeaway">${text}</p>`;
const freshChallenges = {
 architecture:{q:'另一張 Giga 表也有 CURRENT_STEP 欄位，但沒有說明來源。能直接當成 Native 嗎？',a:[['先查這個欄位的 lineage 與來源時間','可以。同名欄位與相同入口，都不能證明來源相同。先確認它是直接承接 SiView，還是經過 Mart 整理。'],['查得到 CURRENT_STEP，就先拿來監看','還缺來源與時間證據。欄位名稱描述內容，不描述刷新路徑；即使值看起來合理，也可能是舊位置。'],['先按約十分鐘使用，之後再補契約','若只是探索分析，可暫記來源未確認；但不能把猜測的十分鐘當保證，也不能据此做現在的決策。']]},
 decision:{q:'Native 通常不到三分鐘，但這次 10:05 查到的來源時間是 10:00。工作只容忍三分鐘，你會怎麼做？',a:[['改查 TX 或暫停這次判斷','合理。本次資料已五分鐘，超出三分鐘條件。若仍需現在做決定，可改經 TX；若可等待，先暫停並確認刷新狀態。'],['保留 Native，因為它有 RT1 標籤','RT1 是來源分類，不是本次結果保證。要比較的是這次資料年齡五分鐘與可容忍三分鐘。'],['換成已整理好的 Mart','Mart 可提供較完整的衍生資料，但不因此更接近現在。若仍要監看現在，也必須驗證其來源時間。']]},
 ai:{q:'你已透過 TX 查到 A123 在 ETCH；準備送出 Auto Hold 時，兩秒過去了。可以直接沿用嗎？',a:[['在核准控制交易執行時重新核對','合理。查詢只描述取得快照的時刻；Lot 可能繼續移動，執行時要重驗身分、Step 與限制。'],['剛才是即時查詢，可以直接沿用','兩秒也可能發生新交易。即時不代表查詢已鎖住後續狀態。'],['先停下來交由工程人員確認','也合理，代價是處置較慢。人工接手仍需確認目前狀態與可執行條件，不能只靠剛才的截圖。']]},
 history:{q:'另一批 B204 在 15:02 Move Out，Mart 只完整收至 15:00。查不到它，報表能判定「未完成」嗎？',a:[['標為資料未涵蓋，等待補齊或查來源','合理。15:02 超出完整涵蓋期間，現在的查無事件不能證明沒有完成。'],['先把它算成未完成，明天再補','只有事先定義暫估口徑並清楚標記才可作暫報；不能呈現為已確認未完成，更不能用來控制目前批次。'],['改查當下位置，就能重建15:02事件','目前位置可幫助查核，但不是該筆 Move Out 事件本身。要回答完成時間，仍需查事件證據。']]},
 join:{q:'合併表的 Step 只有一分鐘舊，Hold 的來源時間不明。這一列能判定「現在可開工」嗎？',a:[['補查所有決策欄位，再由核准交易確認','合理。需要 Step 與 Hold 同時符合條件，就要確認兩者的來源時間與相容狀態；較新的 Step 不能替 Hold 背書。'],['按較新的 Step，整列都採用','同一列不代表同一時刻。Hold 的年齡仍不明，無法證明目前可開工。'],['先用於趨勢分析，暫不作開工依據','可以改變用途，但趨勢分析也要標示未知時間對統計的影響。這仍不能回答現在能否開工。']]},
 contract:{q:'交付 WAFER_HISTORY 時，已填 Source=Mart、Delay≈10min。還缺哪個關鍵條件，才好回答「昨天完成幾片」？',a:[['統計期間、完整涵蓋截止與晚到資料處理','正確。通常延遲並不保證昨天已收齊；要讓接手者能判讀完整性與補數。'],['再加上最後一次 Query 的時間','Query 時間值得保留，但只表示何時取用，不能證明昨天事件已完整載入。'],['把資料改標為 RT0','分類必須符合實際來源與交易條件，改名稱不會改善資料年齡或完整性。']]}
};
function freshChallenge(id){const x=freshChallenges[id];return `<section class="transfer-question" data-challenge="${id}"><p class="activity-label">換個條件，你怎麼選？</p><h2>${x.q}</h2><div class="challenge-choices">${x.a.map(([label],i)=>`<button class="challenge-choice" data-challenge-choice="${i}" aria-pressed="false"><span>${String.fromCharCode(65+i)}</span>${label}</button>`).join('')}</div><p class="challenge-feedback" role="status" hidden></p></section>`;}
const freshnessV2 = {
 architecture(){return freshIntro('先認識資料的路徑','同一個 Giga，<br>也有不同的新鮮度。','先看同一批 A123：為什麼查詢入口相同，一筆已是 ETCH，另一筆卻還停在 DEV？')+freshFigure('architecture')+activity('沿著一個來源，走到查詢結果','點選你要拿的資料，追查它經過哪些處理。',`<div class="route-picker" role="group" aria-label="選擇資料來源"><button data-route="native" aria-pressed="true">SiView Native</button><button data-route="mart" aria-pressed="false">Data Mart</button><button data-route="tx" aria-pressed="false">TX</button></div><div id="route-trace" class="route-trace"></div><p id="route-explain" class="fresh-answer" role="status"></p>`)+detail('完整架構與通常延遲',`<div class="architecture-reference"><strong>MES / MMDB · Source of Truth</strong><ul><li><b>Reporting DB → Giga Report</b><ul><li>SiView Native：承接 SiView 報表資料，通常 &lt;3 min。</li><li>Data Mart：SiView ＋ 其他 Mart／衍生邏輯，整理與刷新後供 Giga 查詢，約10 min。</li></ul></li><li><b>Inline DB</b>：MMDB 的另一個分支；此案未提供刷新條件，另查契約。</li><li><b>TX ↔ MMDB</b>：需要當下狀態時，經 TX 取得。</li></ul></div><p>一般工程師不直接 Query MMDB。Join、Transform、Aggregate 和其他 Mart 的依賴，會影響最終資料時間。這些通常延遲來自本課提供的內部架構；本次新鮮度仍看 Table／Column 的契約與來源時間。</p>`)+freshChallenge('architecture');},
 decision(){return freshIntro('一個選擇原則','晚十分鐘，<br>會不會做錯事？','昨天產量、線上監看、現在 Auto Hold，三種工作需要的時間條件不同。先想用途，再找來源。')+freshFigure('decision')+activity('換一個工作需求，看看選擇為何改變','整理過的歷史有分析價值；當下控制則不能只靠一筆近即時快照。',`${select('decision-purpose','這次要做的事',[['analysis','分析昨天產量／Weekly Yield'],['monitor','線上監看，最多容忍3分鐘'],['control','現在判斷是否 Auto Hold']],freshState.decision)}<div class="level-track"><div data-level="analysis"><small>RT2</small><b>Data Mart</b><span>整理過的歷史</span></div><div data-level="monitor"><small>RT1</small><b>SiView Native</b><span>近即時狀態</span></div><div data-level="control"><small>RT0</small><b>TX → MMDB</b><span>交易層級即時</span></div></div><p id="decision-answer" class="fresh-answer" role="status"></p>`)+detail('查詢前的兩個問題與來源等級',`<ol><li>這個資訊會拿來做「現在」的決策嗎？不會：優先 Mart，驗證期間與完整性。</li><li>會：三分鐘延遲可以接受嗎？可以：先找 Native，再驗這筆年齡；不可以：TX，控制另在核准交易重驗。</li></ol>${rowsTable(['等級','來源','通常延遲','用途'],[['L0 / RT0','TX → MMDB','交易層級即時','關鍵判斷／核准交易'],['L1 / RT1','Giga / SiView Native','&lt;3 min','工程監看'],['L2 / RT2','Giga / Data Mart','約10 min／依排程','分析、統計、報表、AI 訓練']])}<p>Cycle time、Recipe 使用趨勢、Defect 統計與 AI 訓練通常適合 Mart；仍要核對事件時間、標籤對齊與期間完整性。</p>`)+freshChallenge('decision');},
 ai(){return freshIntro('案例一 · Vision AI 與當下決策','AI 發現異常，<br>這批還在 DEV 嗎？','10:00 發現 Wafer 異常；10:01 查 Lot A123。目前已在 ETCH，但較舊的來源仍會回傳 DEV。')+freshFigure('ai')+activity('同一個查詢時刻，換一個來源','現場與查詢時間固定。只有你拿資料的路徑改變。',`<div class="fresh-controls">${select('ai-source','資料來源',[['native','Giga / SiView Native'],['mart','Giga / Data Mart'],['tx','TX → MMDB']],freshState.source)}${select('ai-tolerance','這次用途',[['monitor','工程監看：可容忍3分鐘'],['control','Auto Hold：要求當下狀態']],freshState.tolerance)}</div><div class="live-comparison"><div class="current-anchor"><span class="live-dot"></span><small>本例現場 · 10:01</small><b>ETCH</b><span>Lot A123</span></div><div class="query-window"><div class="window-bar"><strong id="query-source"></strong></div><div class="query-sub">查詢 10:01 · Lot A123</div><div class="query-result"><div><small>回傳 Step</small><strong id="query-step"></strong></div><div><small>來源時間</small><strong id="query-time"></strong></div><div><small>資料年齡</small><strong id="query-age"></strong></div></div><div class="age-track" aria-label="資料年齡零至十分鐘"><span id="age-fill"></span><i>3 min</i></div><div class="axis-ends"><span>0 分鐘</span><span>10 分鐘</span></div></div></div><p id="ai-answer" class="fresh-answer" role="status"></p>`)+freshChallenge('ai')+detail('為什麼 TX 查完仍要重驗？','<p>TX 快照描述查詢當下，不保證操作送出時狀態仍相同。Auto Hold 由核准控制交易在執行時核對 Lot、Step 與限制；教學頁只模擬選擇，不執行真實查詢或控制。</p>');},
 history(){return freshIntro('案例二 · Event 與 Current State','經過 DEV，<br>不等於現在還在 DEV。','昨日 14:20 的 Move Out 是發生過的事；今日 10:01 在哪裡，則要看目前狀態。')+freshFigure('history')+activity('查不到事件，可能只是還沒收齊','切換問題，再縮短 Mart 的涵蓋期間。觀察「有沒有」何時只能回答「還不知道」。',`<div class="fresh-controls">${select('history-question','你想問',[['event','昨天有沒有經過 DEV？'],['current','現在還在 DEV 嗎？']],freshState.history)}${select('history-complete','Mart 完整涵蓋範圍',[['yes','昨日已收齊，包含14:20'],['no','只收至昨日14:00']],freshState.complete)}</div><div class="coverage-track"><span>昨日事件</span><div class="coverage-line"><i id="coverage-fill"></i><b class="cutoff-label">14:00</b><b class="event-dot">14:20</b></div><span>資料持續補入</span></div><div class="event-book"><div class="book-heading"><strong>Data Mart · A123 事件簿</strong><span id="history-coverage"></span></div><div id="history-record"></div></div><p id="history-answer" class="fresh-answer" role="status"></p>`)+freshChallenge('history')+detail('歷史分析還要保存什麼？','<p>保存事件時間、統計起迄、資料涵蓋截止、最新完整批次與晚到資料處理。已發生事件不會因 Lot 前進而消失；Mart 缺少事件也不一定代表事件沒發生。</p>');},
 join(){return freshIntro('案例三 · 同列資料也有時間差','表剛刷新，<br>Hold 也變新了嗎？','Step 來自 Native，Hold 依賴另一個 Mart。兩欄合在一起後，各自的來源時間仍然不同。')+freshFigure('join')+activity('按一次刷新，觀察哪個時間改變','假設上游尚未更新。重新載入會改變表的載入時間，不會憑空產生新的 Hold 狀態。',`<div class="column-lineage"><div class="source-slip"><small>SiView Native</small><strong>Step = ETCH</strong><time>來源 10:00</time><span>↓ 對應 Current Step</span></div><div class="source-slip amber"><small>Hold Mart</small><strong>Hold = N</strong><time>來源 09:51</time><span>↓ 對應 Hold</span></div></div><div class="query-window"><div class="window-bar"><strong>Giga / LOT_PROCESS_SUMMARY</strong></div><div class="refresh-stamp">載入時間 loaded_at <b id="join-refresh-time">10:00</b><span>查詢時間固定10:01</span></div><div class="joined-row"><div><small>Lot</small><strong>A123</strong></div><div><small>Current Step</small><strong>ETCH</strong><span>來源10:00 · 1分鐘前</span></div><div class="older-field"><small>Hold</small><strong>N</strong><span>來源09:51 · 10分鐘前</span></div></div></div><div class="fresh-controls"><button class="button primary" id="refresh-table">重新載入至10:01 ↻</button><button class="button" id="reset-join">重設</button></div><p id="join-answer" class="fresh-answer" role="status"></p>`)+freshChallenge('join')+detail('三種時間，分別回答三個問題',rowsTable(['時間','回答的問題','本例 Hold'],[['source_data_time','內容描述哪個時刻？','09:51'],['loaded_at','何時載入這張表？','10:00 → 10:01'],['queried_at','工程師何時查？','10:01']])+'<p>本例 Hold 資料年齡 = 10:01 − 09:51 = 10分鐘。不能用載入時間取代來源時間。需要 Step 與 Hold 同時成立的決策，要確認相容快照，必要時由 TX／核准交易取得並重驗。</p>');},
 contract(){return freshIntro('交接到日常工作','不只交付欄位，<br>也交付來源與時間。','讓下一位工程師能判斷這份資料適合什麼工作。Table catalog 先有契約，混合來源再追到 Column。')+freshFigure('contract')+activity('把這一列，追到可用的資料契約','這份契約是教學範例。選取欄位，查看它的來源與時間；再決定能否支持你的用途。',`<div class="contract-tabs" role="group" aria-label="檢視欄位契約"><button data-contract-field="step" aria-pressed="true">Current Step</button><button data-contract-field="hold" aria-pressed="false">Hold</button></div><div class="contract-inspector"><div><span id="contract-field"></span><strong id="contract-value"></strong></div><dl id="contract-facts"></dl></div><p class="fresh-answer">此表適合歷史分析；不能只憑這一列判斷現在可開工。若需當下控制，經 TX／核准交易重驗。</p><button class="button" id="download-contract">下載範例 Data Contract ↓</button>`)+freshChallenge('contract')+detail('Table catalog 範例與四句話',`${rowsTable(['Table / 介面','Source','Refresh / Delay','Recommended Usage','Auto Control'],[['LOT_CURRENT_STATUS','SiView Native','RT1 · 通常<3 min','近即時監看','不可只憑快照'],['WAFER_HISTORY','Data Mart','RT2 · 約10 min','歷史分析；查涵蓋期間','No'],['LOT_KPI_DAILY','Data Mart','Batch','每日KPI；查完整批次','No'],['CURRENT_HOLD','SiView Native','RT1 · 通常<3 min','Hold近即時監看','不可只憑快照'],['目前狀態（TX）','MMDB via TX','RT0 · transaction','關鍵決策／核准交易','執行時重驗']])}<ol class="four-lines"><li>MMDB 是 Source of Truth；一般工程師不直接 Query。</li><li>Giga Report 的資料不一定一樣新。</li><li>Native 通常 &lt;3 min；Mart 約10 min，仍驗本次來源時間。</li><li>現在狀態看 Native／TX；歷史分析用 Mart。控制由核准交易重驗。</li></ol>`)+takeaway('選來源前，不只問「有沒有這個欄位」，還要問「這個欄位是多久以前的」。');}
};
const freshRoutes={native:{nodes:['MES / MMDB','Reporting DB','SiView Native','Giga 查詢'],text:'直接承接 SiView 報表來源。通常不到三分鐘；仍要核對本次 source_data_time，不能只看 Native 名稱。'},mart:{nodes:['MES / MMDB','Reporting／SiView','＋其他 Mart → 整理／刷新','Giga 查詢'],text:'最終資料受 Join、Transform、Aggregate、衍生邏輯與上游刷新影響。多一層整理有分析價值，也會帶來不同的時間條件。'},tx:{nodes:['一般工程師','TX 交易介面','MMDB 當下狀態'],text:'需要 MMDB 當下狀態時經 TX，並非開放直接 Query。若拿來執行控制，核准交易仍要在執行時重驗條件。'}};
function showFreshRoute(key){const r=freshRoutes[key];document.querySelectorAll('[data-route]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.route===key)));document.querySelector('#route-trace').innerHTML=r.nodes.map((t,i)=>`${i?'<span class="trace-arrow" aria-hidden="true">→</span>':''}<b>${t}</b>`).join('');document.querySelector('#route-explain').textContent=r.text;}
const contractData={table:'LOT_PROCESS_SUMMARY',example:true,source:'SiView Native + Hold Mart',refresh:'約10分鐘；依實際契約與來源時間',recommended_usage:'Historical analytics; not a current-control snapshot',columns:{current_step:{example_value:'ETCH',source:'SiView Native',source_data_time:'10:00'},hold:{example_value:'N',source:'Hold Mart',source_data_time:'09:51'}},loaded_at:'10:01',queried_at:'10:01',completeness:'填寫完整涵蓋截止、成功批次、晚到資料處理',auto_control:'No; use approved TX/control transaction and revalidate at execution'};
function showContractField(key){const c=key==='step'?contractData.columns.current_step:contractData.columns.hold;document.querySelectorAll('[data-contract-field]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.contractField===key)));document.querySelector('#contract-field').textContent=key==='step'?'Current Step':'Hold';document.querySelector('#contract-value').textContent=c.example_value;document.querySelector('#contract-facts').innerHTML=`<dt>Source</dt><dd>${c.source}</dd><dt>來源時間</dt><dd>${c.source_data_time}</dd><dt>查詢時間</dt><dd>10:01</dd><dt>資料年齡</dt><dd>${key==='step'?'1':'10'} 分鐘</dd>`;document.querySelector('.contract-inspector').classList.toggle('amber',key==='hold');}
function enhanceFreshLesson(id){if(id==='architecture')showFreshRoute('native');if(id==='contract')showContractField('step');}
document.addEventListener('click',e=>{
 const route=e.target.closest('[data-route]');if(route)showFreshRoute(route.dataset.route);
 const field=e.target.closest('[data-contract-field]');if(field)showContractField(field.dataset.contractField);
 const choice=e.target.closest('[data-challenge-choice]');if(choice){const section=choice.closest('[data-challenge]'),index=Number(choice.dataset.challengeChoice);section.querySelectorAll('[data-challenge-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b===choice)));const f=section.querySelector('.challenge-feedback');f.textContent=freshChallenges[section.dataset.challenge].a[index][1];f.hidden=false;}
 const zoom=e.target.closest('[data-fresh-zoom]');if(zoom){let dialog=document.querySelector('#fresh-art-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='fresh-art-dialog';dialog.className='fresh-art-dialog';dialog.setAttribute('aria-label','教學插畫完整圖');dialog.innerHTML='<form method="dialog"><button class="button">關閉 ×</button></form><div class="zoom-scroll"><img alt=""></div>';document.body.append(dialog);}const id=zoom.dataset.freshZoom;const img=dialog.querySelector('img');img.src='assets/freshness-v2/'+freshArt[id][matchMedia('(max-width:700px)').matches?1:0];img.alt=freshArt[id][2];dialog.showModal();}
 if(e.target.closest('#download-contract')){const blob=new Blob([JSON.stringify(contractData,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='LOT_PROCESS_SUMMARY.example.contract.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
});
