const $=id=>document.getElementById(id),esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cases=[
{id:'where',title:'Lot L023 現在在哪裡？',groups:['lot','cast','port','eqp','location','forecast'],intro:'同事要找 L023。預派資料寫 ETCH-03，但這只說明安排；要找實體位置，必須從批次對到載具，再確認當下位置。',steps:[['先認批次與盒子','從 FRLOT、FRCAST_LOT、FRCAST 找批次與裝載關係。L023 與 FOUP F012 是教學示例，兩個 ID 不互換。'],['再看位置對應','2671 描述載具所在與設備；2676 把設備、Port、載具、Lot 放在同一圖。2674 補 Port 與設備位置細節。'],['排除「預派＝已到」','CSFRPREDISPATCH 表示派工系統預先安排 Lot 的目標機台；Frlot_EQP 的「帶到」表示 Lot 在該站點有可用機台。要證明到站，還須當時的載具位置或交接事實。']],answer:'回答應包含「哪批、哪個載具、位置、資料時間」。若只有預派 ETCH-03，就只能回答預計目的地，不能回答正在加工。',limit:'2671 的 Siview.Port 與其他圖的 FRPORT 不直接視為同表；FRCAST 的 schema 省略名稱也需查字典。'},
{id:'ready',title:'這批現在可以在這台設備加工嗎？',groups:['lot','flow','lr','pd','er','eqp','chamber','hold','state'],intro:'L023 準備進入下一站。這是一個多條件判斷：批次進度、配置、設備資源及管制都可能讓結果改變。',steps:[['定義是否對得上','2673 的 Part／Flow／LR 與2677的 PD／ER／設備關係提供配置線索。可對應設備，不表示 Lot 已到可執行的站。'],['批次與設備是否合適','確認 Lot 當前站與 Hold，再看設備及指定 Chamber。2674 補充加工資源層級；主機狀態不能直接代替 Chamber 狀態。'],['執行時還須重驗','依既有教學，Daily MON 逾期會卡 EMS。這項放行資料並未在七圖完整展開，需另接管制來源，並使用符合時效的資料。']],answer:'大圖能列出要查的條件，不能僅憑其中一張配置表就判斷「可以加工」。缺 MON、狀態時間或實際執行條件時，答案仍是不足以判定。',limit:'Future Hold 是未來觸發安排，不一定代表此刻已 Hold；Qtime 的起訖事件與限值需看實際規則。'},
{id:'move',title:'搬了一次 FOUP，就多一次 Move 嗎？',groups:['lot','cast','transfer','move','wip'],intro:'示例：F012 被搬到設備，L023 過站一次，之後重工又過同一站一次。這裡同時出現搬送事件與兩個 Lot 過站事件。',steps:[['先分事件對象','2672 的 Carrier／MCS 歷史描述載具搬送；DM_Move_Step_bth 描述 Lot Move。搬送一次不自動產生一個 Move。'],['依廠內定義計算','同一 Lot 的第一次過站與重工過站各成立一次，所以此例為2次 Move；Lot 身分仍是 L023。'],['再看統計用途','2675 重複引用 Move 與全部動作歷史，是把事件接到報表視角。Join 後重複的資料列不能再加算成新事件。']],answer:'本例可以有1次載具搬送、2次 Lot Move；兩種次數的對象與成立條件不同。要用唯一事件與成立規則計數。',limit:'這是教學假設事件，不是查詢結果。原圖未提供完整事件唯一鍵或撤銷／補送規則。'},
{id:'recipe',title:'配置有 ER，就能知道實際用了什麼嗎？',groups:['flow','lr','pd','er','eqp','lot','move'],intro:'工程師想查 L023 這一次加工用的 Recipe。配方與設備的配置資料，回答的是「有哪些對應」，不是「這次已使用哪個」。',steps:[['把兩張配置圖接起來','2673 由流程與 LCRECIPE_ID 找 LR／設備；2677 由 FRMRCP、FRMRCP_EQP 與 ER 接到 LR／設備關係。'],['保留層次與來源','LR、ER、Physical Recipe 的意義不同。DM_FLOW_LR_EQP_BT 在兩圖出現，是共通線索；schema與基數仍需確認。'],['追該次執行證據','需要 Lot、站點／過站次序、設備／Chamber、加工時間、實際 Recipe 與版本的紀錄。重工時須分清哪一次。']],answer:'七圖能協助理解配方配置，但尚不能直接證明這次 Physical Recipe。缺少執行紀錄的部分在大圖保留邊界，不畫成已證實的對應。',limit:'不假設 LR、ER、Physical Recipe 同名、一對一，也不把 FRMRCP_EQP 當執行 log。'},
{id:'time',title:'現在 UP，為什麼報表不代表現在？',groups:['eqp','state','wip','groups','oee','capacity'],intro:'同一台設備目前 UP；同時有人看星期一07:20的 WIP 與某期間的設備統計。三者不矛盾，因為回答的時間問題不同。',steps:[['當下：設備正在做什麼','依你的廠內定義，UP 是加工、Lost 是閒置。2674／2677提供設備狀態視角；仍須看記錄時間。'],['快照：當時有哪些 Lot','2675 的 KER_WIP_Y_BTH 是星期一07:20的 WIP；不能拿它回答此刻 L023 還在不在原站。'],['期間：哪些設備的比率','2675 把設備與機群、虛擬群組及統計接起來。AVL 是期間 Availability 比率；需先對齊成員與期間。']],answer:'同一設備可以「現在 UP」，但某期間 AVL 並非100%。快照、狀態、統計與 IE WPH 定義，各自回答不同問題。',limit:'不把 OEE、AVL、Eff 當同義字；Eff 公式、AVL 分母與 MON／PM 分類尚未確認。各表 freshness 需獨立契約。'}
];
let data,svg,selected='lot',zoom=1;
const questionMode=new URLSearchParams(location.search).get('view')==='questions';
$('questions').hidden=!questionMode;$(questionMode?'question-tab':'original-tab').setAttribute('aria-current','page');
function highlight(ids){if(!svg)return;svg.querySelectorAll('.node').forEach(n=>{n.style.opacity=ids.includes(n.id)?'1':'.3';n.querySelector('rect').style.strokeWidth=ids.includes(n.id)?'6':'3'});svg.querySelectorAll('.relationship').forEach(e=>e.style.opacity=ids.includes(e.dataset.a)&&ids.includes(e.dataset.b)?'1':'.2');}
function whole(){if(!svg)return;svg.setAttribute('viewBox','0 0 2780 1780');svg.querySelectorAll('.node,.relationship').forEach(n=>n.style.opacity='1');zoom=1;resize();$('map-status').textContent='完整大圖：可切換閱讀尺寸、橫向捲動，或用下方主題按鈕逐點閱讀。';}
function resize(){const o=$('map');o.style.width=zoom*100+'%';o.style.height=zoom*100+'%';}
function topic(id,focus=true){selected=id;const g=data.groups.find(x=>x.id===id);$('detail').innerHTML=`<p class="eyebrow">共同主題 · ${g.refs.length} 個原圖節點</p><h2>${esc(g.title)}</h2><p>${esc(g.meaning)}。以下是同一主題下不同來源的資料與關係，保留原始文字，不將它們當成相同表。</p><div class="source-grid">${g.refs.map(r=>`<div class="source-card"><a href="data-map.html?view=original#${r.source}">原圖 ${r.source} · ${esc(r.node)}</a>${r.labels.map(l=>`<code>${esc(l)}</code>`).join('')}</div>`).join('')}</div>`;document.querySelectorAll('[data-topic]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.topic===id));if(focus&&svg){highlight([id]);const n=svg.getElementById(id).getBBox();svg.setAttribute('viewBox',`${n.x-30} ${n.y-30} ${n.width+60} ${n.height+60}`);zoom=1;resize();$('map-status').textContent=`目前局部：${g.title}。點「完整大圖」回到整體關係。`;}}
function quickTopics(ids){$('quick-topics').innerHTML=ids.map(id=>`<button data-quick="${id}">${data.groups.find(g=>g.id===id).title}</button>`).join('');document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>topic(b.dataset.quick));}
function showCase(id){const c=cases.find(x=>x.id===id)||cases[0];document.querySelectorAll('[data-case]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.case===c.id));topic(c.groups[0],false);quickTopics(c.groups);const refs=[...new Set(c.groups.flatMap(id=>data.groups.find(g=>g.id===id).refs.map(r=>r.source)))].sort();$('case').innerHTML=`<h2>${c.title}</h2><p>${c.intro}</p><div class="steps">${c.steps.map(([t,s],i)=>`<div><strong>${i+1}. ${t}</strong><p>${s}</p></div>`).join('')}</div><p class="answer">${c.answer}</p><p class="small">${c.limit}</p><div class="refs">${refs.map(r=>`<a href="data-map.html?view=original#${r}">原圖 ${r}</a>`).join('')}</div><p class="small">大圖中著色的是本題涉及的主題。點下方主題可逐點檢視來源。</p>`;if(svg){whole();highlight(c.groups);$('map-status').textContent='本題涉及：'+c.groups.map(id=>data.groups.find(g=>g.id===id).title).join('、');}}
async function start(){data=await fetch('ER/INTEGRATED/map.json').then(r=>{if(!r.ok)throw Error('來源索引讀取失敗');return r.json()});$('topics').innerHTML=data.groups.map(g=>`<button data-topic="${g.id}">${g.title}</button>`).join('');document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>topic(b.dataset.topic));$('question-list').innerHTML=cases.map(c=>`<button data-case="${c.id}">${c.title}</button>`).join('');document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{location.hash=b.dataset.case;showCase(b.dataset.case)});$('source-index').innerHTML=Array.from({length:7},(_,i)=>String(2671+i)).map(s=>`<details><summary>原圖 ${s}</summary>${data.sourceEdges.filter(e=>e.source===s).map(e=>`<p><code>${esc(e.a)} ↔ ${esc(e.b)}</code> · ${data.groups.find(g=>g.id===e.groupA).title} ↔ ${data.groups.find(g=>g.id===e.groupB).title}</p>`).join('')}</details>`).join('');topic('lot',false);quickTopics(data.groups.map(g=>g.id));if(questionMode)showCase(location.hash.slice(1));attach();}
function attach(){const doc=$('map').contentDocument;if(!doc||doc.documentElement.tagName.toLowerCase()!=='svg')return;svg=doc.documentElement;svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.querySelectorAll('.node').forEach(n=>{n.onclick=()=>topic(n.id);n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();topic(n.id)}}});whole();if(questionMode&&data)showCase(location.hash.slice(1));}
$('map').onload=()=>{if(data)attach()};$('fit').onclick=whole;$('read').onclick=()=>{whole();zoom=Math.max(1,2200/$('viewport').clientWidth);resize();$('map-status').textContent='閱讀尺寸：可水平及垂直捲動查看整張大圖。'};$('plus').onclick=()=>{zoom=Math.min(8,zoom+.5);resize()};$('minus').onclick=()=>{zoom=Math.max(1,zoom-.5);resize()};window.addEventListener('hashchange',()=>{if(data&&questionMode)showCase(location.hash.slice(1))});start().catch(e=>{$('map-status').textContent=e.message;});
