(()=>{'use strict';const C=window.MES_CATALOG;if(!C)return;const base=new URL('.',document.querySelector('script[src*="site-shell.js"]').src),local=p=>new URL(p,base).href,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const read=(key,fallback)=>{try{return JSON.parse(sessionStorage.getItem(key))||fallback}catch{return fallback}},write=(key,value)=>{try{sessionStorage.setItem(key,JSON.stringify(value))}catch{}};
 const file=location.pathname.split('/').pop();document.body.classList.add('mes-unified');if(['advanced.html','support.html'].includes(file))document.body.classList.add('legacy-extra');
 const bar=document.createElement('header');bar.id='mes-sitebar';bar.innerHTML=`<a class="mes-brand" href="${local('learning.html')}">MES · 製造資料學習</a><nav aria-label="全站導覽"><a href="${local('learning.html')}">課程總覽</a><a href="${local('tasks.html')}">現場問題</a><a href="${local('learning.html?view=reference')}">主題與資料參考</a><a href="${local('er-atlas.html')}">完整 ER</a><a href="${local('learning.html?view=instructor')}">導師資源</a></nav>`;document.body.prepend(bar);
 const context=document.createElement('nav');context.id='mes-context';context.setAttribute('aria-label','課程位置與來源');bar.after(context);
 const footer=document.createElement('nav');footer.id='mes-sequence';footer.setAttribute('aria-label','課綱閱讀順序');document.body.append(footer);
 let sequence={};
 function current(){return C.locate(location.href)}
 function refresh(){const u=current(),params=new URLSearchParams(location.search),from=read('mes-from:'+params.get('mesFrom'),null);context.innerHTML=`<a href="${local('learning.html')}">課程總覽</a>${u?`<a href="${local('learning.html?unit='+u.id)}">單元 ${u.id} · ${esc(u.title)}</a>`:`<span>${file==='tasks.html'?'現場問題':file.includes('er')||file==='data-map.html'?'資料與 ER 參考':'學習與參考'}</span>`}`;
  if(from&&from.url){const a=document.createElement('a');a.id='mes-return';a.dataset.mesBack='true';const back=new URL(from.url,location.href);if(back.origin===location.origin){back.searchParams.set('mesRestore',params.get('mesFrom'));a.href=back.href;a.textContent='← 返回：'+from.title;context.prepend(a)}}
  if(u&&u.lessons.length){const outline=document.createElement('details');outline.innerHTML='<summary>本單元目錄</summary><ol>'+u.lessons.map(l=>`<li><a href="${local(l.href)}">${esc(l.label)}</a></li>`).join('')+'</ol>';context.append(outline)}
  if(u){const crumb=document.querySelector('#content .crumb');if(crumb)crumb.textContent='MES 教學 ／ 單元 '+u.id+' · '+u.title;const source=document.querySelector('#sidebar>.eyebrow,.shell>aside>.eyebrow');if(source)source.textContent='來源教材 · 可依本單元順序閱讀';}
  footer.hidden=['learning.html','tasks.html'].includes(file);if(!u){footer.innerHTML=`<a href="${local('learning.html?view=reference')}">回主題與資料參考</a><a class="mes-next" href="${local('tasks.html')}">帶著問題練習 →</a>`;sequence={};return}
  const here=new URL(location.href);let i=u.lessons.findIndex(x=>{const v=new URL(x.href,base);return v.pathname===here.pathname&&v.hash.split('?')[0]===here.hash.split('?')[0]&&(file!=='topic.html'||v.searchParams.get('topic')===here.searchParams.get('topic'))});if(i<0)i=u.lessons.findIndex(x=>new URL(x.href,base).pathname===here.pathname);const prev=i>0?u.lessons[i-1]:{href:'learning.html?unit='+u.id,label:'本單元導讀'},next=i>=0&&i<u.lessons.length-1?u.lessons[i+1]:{href:C.nextUnit(u.id)?'learning.html?unit='+C.nextUnit(u.id).id:'tasks.html',label:C.nextUnit(u.id)?'下一單元：'+C.nextUnit(u.id).title:'綜合任務'};sequence={prev,next};
  footer.innerHTML=`<p>課綱順序 · 單元 ${u.id}　${esc(u.title)}</p><a href="${local(prev.href)}">← ${esc(prev.label)}</a><a href="${local('learning.html?unit='+u.id)}">回本單元</a><a class="mes-next" href="${local(next.href)}">${esc(next.label)} →</a>`;
  for(const id of ['next','fresh-next']){const b=document.getElementById(id);if(b){b.textContent=next.label+' →';b.disabled=false}}
  for(const id of ['previous','prev','fresh-prev']){const b=document.getElementById(id);if(b){b.textContent='← '+prev.label;b.disabled=false}}
  try{if(!['learning.html'].includes(file))localStorage.setItem('mes-last-reading',JSON.stringify({href:location.href,title:document.title,unit:u.id}))}catch{}
 }
 function save(){write('mes-scroll:'+location.pathname+location.search+location.hash,{y:scrollY});}
 const allowed=new Set(['learning.html','topic.html','tasks.html','index.html','operations.html','flow.html','freshness.html','advanced.html','support.html','er-atlas.html','subject-er.html','data-map.html','integrated-map.html']);
 function navigate(href){const u=new URL(href,base);if(u.origin!==location.origin)return;save();const token=Date.now().toString(36)+Math.random().toString(36).slice(2,8),source=new URL(location.href);source.searchParams.delete('mesRestore');write('mes-from:'+token,{url:source.href,title:document.title,y:scrollY});u.searchParams.set('mesFrom',token);location.href=u.href}
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&['next','fresh-next','previous','prev','fresh-prev'].includes(b.id)&&sequence.next){e.preventDefault();e.stopImmediatePropagation();navigate(sequence[['next','fresh-next'].includes(b.id)?'next':'prev'].href);return}const a=e.target.closest('a[href]');if(!a||a.dataset.mesBack||a.hasAttribute('download')||a.target==='_blank'||e.ctrlKey||e.metaKey||e.shiftKey)return;const u=new URL(a.href,location.href);if(u.origin!==location.origin||!allowed.has(u.pathname.split('/').pop())||u.pathname===location.pathname&&u.search===location.search)return;const isHome=a.closest('#mes-sitebar');if(isHome)return;save();const token=Date.now().toString(36)+Math.random().toString(36).slice(2,8),source=new URL(location.href);source.searchParams.delete('mesRestore');write('mes-from:'+token,{url:source.href,title:document.title,y:scrollY});u.searchParams.set('mesFrom',token);a.href=u.href;},true);
 window.addEventListener('hashchange',()=>setTimeout(refresh,0));window.addEventListener('popstate',()=>setTimeout(refresh,0));window.addEventListener('pagehide',save);
 const restore=new URLSearchParams(location.search).get('mesRestore');if(restore){const v=read('mes-from:'+restore,null);if(v){setTimeout(()=>scrollTo(0,v.y||0),150);setTimeout(()=>scrollTo(0,v.y||0),500)}}
 refresh();setTimeout(refresh,300);window.MES_SITE={refresh,navigate};
})();
