'use strict';
const lessons=[['cw','CW｜三種晶圓用途'],['subroute','Sub Route｜加量與返回'],['move','Move｜Lot 過站事件'],['monitor','MON、PM 與 EMS']];
const s={cw:'monitor',route:0,events:[],serial:101,phase:0,pm:true,other:false};
const esc=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const head=(tag,h,p)=>`<div class="lesson-head"><span class="pill">${tag}</span><h1>${h}</h1><p class="lead">${p}</p></div>`;
const take=t=>`<div class="takeaway">${t}</div>`;
const art=(id,text)=>`<details class="concept-illustration" ${innerWidth>760?'open':''}><summary>情境插畫 · ${text}</summary><figure class="variant-art"><img src="assets/mes-010/${id}.png" alt="${text}，教學示意" data-zoom="assets/mes-010/${id}.png"><figcaption><span>圖像為工作概念示意；下方可操作同一案例。</span><button class="btn" data-zoom="assets/mes-010/${id}.png">放大完整圖</button></figcaption></figure></details>`;
const table=(h,rows)=>`<table class="field-table"><thead><tr>${h.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
const quiz=(id,q,options,answers)=>`<section class="quiz" data-quiz="${id}"><p class="eyebrow">換個情境想一想</p><h3>${q}</h3>${options.map((o,i)=>`<button data-answer="${i}" aria-pressed="false">${o}</button>`).join('')}<div class="answer" role="status" data-feedback="${esc(JSON.stringify(answers))}"></div></section>`;
const cwJobs={
monitor:{name:'Monitor Wafer',sub:'取得監控結果',question:'想知道這次膜厚、粒子或蝕刻結果是否符合要求。',action:'使用適用的監控晶圓與 MON 作業，取得量測結果，再依規格判讀。',limit:'有跑晶圓不等於有合格結果；要能對上設備、作業與有效的判定。',html:'<div class="wafer"></div>',evidence:'觀察重點：量測探頭 → 晶圓 → 可判讀的結果。'},
dummy:{name:'Dummy Wafer',sub:'補位／提供負載',question:'適用的批次作業需要配置非產品晶圓，滿足裝載或負載條件。',action:'依指定的位置、材質、規格與使用條件放入 Dummy Wafer。這裡用藍色標出兩個補位角色。',limit:'不能把任何空片都當 Dummy，也不能推論所有設備都需要補滿。',html:'<div class="boat" aria-label="示意七個裝載位置，其中兩個藍色標示 Dummy 角色"><i></i><i class="dummy"></i><i></i><i></i><i class="dummy"></i><i></i><i></i></div>',evidence:'觀察重點：產品位置旁，藍色晶圓提供規範要求的補位／負載。'},
seasoning:{name:'Seasoning Wafer',sub:'調整腔體條件',question:'設備需要建立或恢復指定的加工環境，例如適用的清潔、保養後調整。',action:'依核准程序使用 Seasoning Wafer 調整腔體條件。圖中藍色內壁表示被調整的環境。',limit:'Seasoning 做完不等於 MON 已通過；是否需要後續驗證，依該設備規範。',html:'<div class="chamber"><div class="wafer"></div></div>',evidence:'觀察重點：晶圓參與調整作業；被建立或恢復的是腔體加工條件。'}
};
function cw(){return head('01 / CONTROL WAFER','CW：同屬控制晶圓，用途不一樣','在你們廠內，Monitor Wafer、Dummy Wafer、Seasoning Wafer 都歸在 CW。先看這次要完成什麼工作，再理解晶圓扮演的角色。')+
`<div class="confirmed">已確認的廠內分類：三者都算 CW（Control Wafer）。MON 則是作業類型，並不是另一種晶圓。</div>`+art('cw','監控結果、補位負載、腔體調整')+
`<div class="visual"><p class="visual-label">同屬 CW · 依工作目的比較</p><h2>這次需要晶圓幫忙做什麼？</h2><div class="job-choice">${Object.entries(cwJobs).map(([k,v])=>`<button data-cw="${k}" aria-pressed="${s.cw===k}"><b>${v.name}</b><small>${v.sub}</small></button>`).join('')}</div><div id="cw-scene"></div>${take('都屬 CW；用途不同，不能只看外觀或把三者任意互換。')}</div>`+
table(['用途','工作結果','接手時確認'],[['Monitor','取得膜厚／粒子／蝕刻等監控結果','量測記錄、規格、判定與適用設備'],['Dummy','滿足指定的裝載／負載條件','材質、位置、使用條件與設備規範'],['Seasoning','建立或恢復腔體加工環境','核准程序、完成條件與必要的後續驗證']])+
`<section class="section"><h2>三種用途，不一定是三種互斥的物料</h2><p>實際上 Dummy Wafer 也可能被用來做 seasoning。這裡分的是主要工作用途，不是宣告三者有不同顏色、固定材質或完全不能交集。能否重用、何時退役、可用在哪台機台，都需要看管理規範。</p><p class="note">圖中的藍色、位置與腔體內壁高亮，只用來指示角色；不是晶圓的外觀辨識規則，也不是實際裝載配方。</p></section>`+
quiz('cw','設備做完 seasoning，現在要判斷粒子結果是否合格，還缺哪一類工作？',['直接以 seasoning 完成視為合格','依規範執行監控並檢查結果'],['Seasoning 是調整條件，不等於已取得粒子合格的證據。','正確。要取得適用的監控結果並判讀；使用哪種晶圓與 MON 作業依設備規範。'])+
`<p class="source">本廠 CW 分類：使用者確認。通用用途參考：<a href="https://patents.google.com/patent/WO2003077303A1/en" target="_blank" rel="noopener">使用 Dummy Wafer 進行 seasoning，並檢查加工結果的技術示例</a>。此來源不代表所有設備採同一方法。</p>`;}
function updateCw(){const v=cwJobs[s.cw];document.querySelectorAll('[data-cw]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.cw===s.cw)));document.querySelector('#cw-scene').innerHTML=`<div class="cw-scene"><div><div class="cw-physical ${s.cw}" role="img" aria-label="${v.evidence}">${v.html}</div><p class="method-label">${v.evidence}</p></div><div class="cw-detail"><span class="visual-label">${v.sub}</span><h3>${v.name}</h3><p><b>工作問題：</b>${v.question}</p><p><b>接著做：</b>${v.action}</p><div class="result warn">${v.limit}</div></div></div>`;}
function subroute(){return head('02 / TEMPORARY ROUTE','Sub Route：出去加量，回原站接續','Lot 暫時離開主 Route，去另一條 Route 做追加量測。完成後回到原來離開的位置；返回原站與原站過站完成，是兩件事。')+
`<div class="confirmed">已確認：「加量」指追加量測；Sub Route 從哪裡出去，就回哪裡。</div>`+art('subroute','S50 出發、追加量測、返回同一 S50')+
`<div class="visual"><p class="visual-label">LOT L023 · 教學 Route 與站點</p><h2>先記住返回位置，再切換目前路徑</h2><div class="anchor"><span>返回錨點始終保留</span><strong>F-DEMO v1 / S50</strong></div><div class="route-loop"><div id="main-node" class="loop-node"><span>主 Route</span><h3>F-DEMO v1 / S50</h3><p>原本的量測站</p></div><div class="loop-arrow">→<small>去程</small></div><div id="sub-node" class="loop-node"><span>Sub Route</span><h3>SR-ADD v1</h3><p>追加量測</p></div><div class="loop-return">回程：SR-ADD v1 → F-DEMO v1 / S50</div></div><div class="status-record"><div><small>LotId</small><b>L023</b></div><div><small>目前 Route</small><b id="route-current"></b></div><div><small>目前位置／狀態</small><b id="route-position"></b></div></div><div class="actions"><button id="route-next"></button><button id="route-wrong">嘗試直接回 S60</button><button id="route-reset">重演</button></div><div id="route-feedback" class="result" role="status"></div><ol id="route-log" class="audit-list"></ol>${take('離開位置要留得住；返回同一站，不代表這站已經完成。')}</div>`+
table(['要區分的資料','本例','為什麼需要'],[['主 Route','F-DEMO v1','知道原本要走的流程'],['目前 Route／位置','SR-ADD v1／追加量測，或主 Route S50','不能永遠只查主路徑欄位'],['返回 Route／Step','F-DEMO v1 / S50','避免回錯版本或下一站'],['進出與量測記錄','L023 的去程、追加量測、回程','串回同一批的完整工作歷程']])+
`<p class="spec">路徑切換記錄不直接當成 Move。只有符合廠內定義、已成立的 Lot 過站事件才計 Move；不能看到「出去一次、回來一次」就自行加二。</p>`+
quiz('subroute','追加量測完成後，系統回到原 S50。是否可以直接把 S50 記成完成？',['可以，因為已經回來了','仍須確認原 S50 的完成條件與過站事件'],['返回只說明位置；原站是否完成仍需其作業與過站證據。','正確。Sub Route 返回原站，不會自動替原站建立完成事件，也不能因此跳至 S60。'])+
`<p class="source">Sub Route 往返規則與加量含義：使用者確認。RouteId、版本、LotId、站點均為教學示例。</p>`;}
function updateRoute(message=''){const p=s.route,route=p===1||p===2?'SR-ADD v1':'F-DEMO v1';document.querySelector('#route-current').textContent=route;document.querySelector('#route-position').textContent=['S50／尚未離開','追加量測中','量測完成／待返回','S50／返回，未自動過站'][p];document.querySelector('#main-node').className='loop-node'+(p===0||p===3?' current':'');document.querySelector('#sub-node').className='loop-node'+(p===1?' current':p>=2?' done':'');const next=document.querySelector('#route-next');next.textContent=['進入 Sub Route','完成追加量測','返回原 S50','已回原站'][p];next.disabled=p===3;document.querySelector('#route-wrong').disabled=p!==2;const r=document.querySelector('#route-feedback');r.className='result'+(message?' warn':'');r.textContent=message||['返回位置已記下；尚未改變主 Route 的原站狀態。','目前執行的是子流程；L023 的身分與返回位置仍保留。','追加量測完成，接著依返回記錄回到原 S50。','已回 F-DEMO v1 / S50。接下來依原站規則完成，不自動前進 S60。'][p];const logs=['記下返回位置：F-DEMO v1 / S50','去程：L023 → SR-ADD v1／追加量測','追加量測完成：保留量測結果與關聯','回程：L023 → F-DEMO v1 / S50'];document.querySelector('#route-log').innerHTML=logs.slice(0,p+1).map((t,i)=>`<li><small>示例記錄 ${i+1}</small>${t}</li>`).join('');}
const initialEvents=()=>[{id:'E101',lot:'L023',step:'S40',kind:'正常'},{id:'E102',lot:'L023',step:'S40',kind:'重工'},{id:'E103',lot:'L023',step:'S50',kind:'正常'}];
s.events=initialEvents();s.serial=104;
function move(){return head('03 / LOT MOVE','Move：計的是 Lot 進機事件','單位是 Lot，重工也計入。同一批 Lot 可以產生多個 Move；它和晶圓片數、不同 Lot 的批數、FOUP 搬運次數都不同。')+
`<div class="confirmed">已確認：Move 計算 Lot 進機事件；機台與 Lot 每發生一次進機事件，就記錄一筆，重工再次進機也計入。按廠區與日期統計可觀察每日製造表現；依 Lot 查 DM_MOVE_STEP 可追查經過哪些站點。Move 筆數不直接等於晶圓產出數或理論最大產能。</div>`+art('move','一批 Lot，三筆進機，包含一次重工')+
`<div class="visual"><p class="visual-label">已成立的進機事件 · 所有示例都是 L023</p><h2>同一批走了幾次有效進機？</h2><div class="countboard"><div><span>Lot Move</span><b id="move-count"></b><small>進機事件數</small></div><div><span>不同 Lot</span><b id="lot-count"></b><small>批次身分數</small></div><div><span>其中重工</span><b id="rework-count"></b><small>已包含於 Move</small></div></div><ul id="move-ledger" class="ledger"></ul><p class="led-key">淡黃色標示重工事件；每筆已成立的不同事件各計 +1。</p><div class="actions"><button id="move-normal">新增正常進機</button><button id="move-rework">新增重工進機</button><button id="move-duplicate">重送最後同一事件</button><button id="move-reset">還原三筆示例</button></div><div id="move-feedback" class="result" role="status"></div>${take('3 個 Lot Move 可以來自同一批 Lot；重工不是另一批，但仍是另一次進機。')}</div>`+
table(['看起來相近的量','本例','與 Move 的差異'],[['Lot Move','E101、E102、E103，共 3','計不同的已成立進機事件'],['不同 Lot 數','只有 L023，共 1 批','去重 LotId 不會得到 Move 數'],['Wafer 數','本例未指定','不把每次進機乘上晶圓數'],['搬運次數','本例未指定','FOUP 換位置不等於進機成立']])+
`<section class="section"><h2>重工要計；同一筆資料重送不能再計一次</h2><p>E102 是另一筆真正成立的重工進機，所以計入。若 E102 因資料重送出現第二次，它仍是同一筆事件。查詢應依來源的事件唯一鍵與有效狀態處理，不能只數每次收到幾列資料。</p><p class="note">示例中的 E101 等為教學事件 ID，不宣稱實際資料表具有相同欄位。取消、沖銷及具體交易的計入規則仍依廠內定義。</p></section>`+
quiz('move','L023 正常進機一次、重工進機一次；同一重工事件又被重送。應計多少？',['3，收到三筆資料就計三次','2，正常與重工各一次；重送不新增事件'],['重送不是新的進機；要先辨識同一事件。','正確。重工計入，但同一事件的重複傳送不再增加 Move。'])+
`<p class="source">Lot 單位、進機事件與重工計入：使用者確認。事件唯一性為本教學的資料查詢注意事項，實際事件鍵與沖銷規則待廠內資料定義。</p>`;}
function updateMove(message=''){document.querySelector('#move-count').textContent=s.events.length;document.querySelector('#lot-count').textContent=new Set(s.events.map(x=>x.lot)).size;document.querySelector('#rework-count').textContent=s.events.filter(x=>x.kind==='重工').length;document.querySelector('#move-ledger').innerHTML=s.events.map(e=>`<li class="${e.kind==='重工'?'rework':''}"><span class="event-id">${e.id}</span><div class="event-body"><b>${e.lot} / ${e.step}</b><small>${e.kind} · 進機成立</small></div><span class="event-count">+1</span></li>`).join('');const out=document.querySelector('#move-feedback');out.className='result'+(message.includes('重送')?' warn':'');out.textContent=message||`${s.events.length} 筆不同進機事件＝${s.events.length} Lot Move；不同 Lot 仍為 ${new Set(s.events.map(x=>x.lot)).size} 批。`;}
function monitor(){return head('04 / MONITORING & INTERLOCK','Daily MON 逾期，會卡 EMS','PM 是保養工作，MON 是監控作業。設備已保養完成，並不能取代有效的 Daily MON；逾期時 EMS 會阻擋生產加工。')+
`<div class="confirmed">已確認：MON 是作業類型；Daily MON 逾期不能加工，會卡 EMS（EQM Monitor System）。</div>`+art('monitor','PM 完成，但監控逾期仍阻擋加工')+
`<div class="three section"><article class="paper"><span class="num">MAINTENANCE</span><h3>PM</h3><p>Preventive Maintenance，預防性保養。清潔、檢查、更換零件等作業依設備規範安排，目的是維持設備條件。</p></article><article class="paper"><span class="num">MONITORING</span><h3>MON</h3><p>監控設備或製程表現的作業類型。例如確認膜厚、粒子或蝕刻結果是否符合要求；使用的 Monitor Wafer 則屬 CW。</p></article><article class="paper"><span class="num">VALIDITY</span><h3>Daily MON</h3><p>例行監控作業。不能只看曾經做過，還要確認是否仍有效；逾期時 EMS 會阻擋生產加工。</p></article></div>`+
`<div class="visual"><p class="visual-label">EQP-01 · 逾期阻擋與補做流程示例</p><h2>保養完成了，現在就能開始生產嗎？</h2><div class="ems-grid"><div id="pm-card" class="ems-node"><span class="visual-label">保養工作</span><h3 id="pm-state"></h3><p>PM 完成只代表這項工作完成。</p></div><div id="mon-card" class="ems-node"><span class="visual-label">Daily MON 作業／結果</span><h3 id="mon-state"></h3><p id="mon-detail"></p></div><div id="ems-card" class="ems-node"><span class="visual-label">EMS · EQM Monitor System</span><h3 id="ems-state"></h3><p id="ems-detail"></p></div></div><div class="control"><label class="checkline"><input type="checkbox" id="pm-done" checked> PM 已完成</label><label class="checkline"><input type="checkbox" id="other-hold"> 另有一筆有效 Hold</label><div class="actions"><button id="mon-next"></button><button id="mon-reset">重演逾期</button></div><p class="note">補做 MON 與生產加工是不同作業。此處不把生產阻擋解讀成禁止執行恢復所需的監控。</p></div><div class="process-request"><button class="btn primary" id="try-process">檢查生產加工條件</button><div id="process-result" class="result" role="status"></div></div>${take('MON 做完、結果被接受、EMS 條件更新，要分開確認。')}</div>`+
table(['不要混為一談','要看的證據'],[['PM 完成 vs. MON 合格','保養完成記錄；監控結果與適用規格分別核對'],['MON 完成 vs. 仍在有效期','作業／結果記錄；有效性與到期條件'],['MON 結果被接受 vs. EMS 已更新','不能只看到量測結果就假設阻擋已解除'],['EMS 此項通過 vs. 所有加工條件通過','還需核對其他 Hold、設備資格、產品與配方等條件']])+
`<p class="spec">本輪沒有指定 Daily MON 是每曆日、每班或固定幾小時，因此不預設 24 小時週期。補做、結果接受與 EMS 更新的細節依廠內流程；此互動只是將這些證據分開呈現。</p>`+
quiz('monitor','Daily MON 已補做，但 EMS 仍顯示逾期阻擋。現在怎麼判斷？',['MON 做完就視為可以生產','確認結果是否被接受、EMS 條件是否更新'],['做完作業不代表結果已被接受，也不代表系統中的阻擋已解除。','正確。先核對有效結果與 EMS 條件；即使此項解除，其他加工限制也要確認。'])+
`<p class="source">MON 類型、PM 含義、Daily MON 逾期與 EMS 阻擋：使用者確認。設備、補做階段與操作為教學示例，不代表真實系統 API。</p><p class="future-topics">尚待廠內定義：AAA 正式縮寫、EFF 公式與指標彙總方式；已確認 AVL 為期間 Availability、設備 Lost 為閒置、UP 為加工中。Port 的 UP／LOST 則表示有貨／沒有貨，須依對象判讀。</p>`;}
function updateMon(){document.querySelector('#pm-done').checked=s.pm;document.querySelector('#other-hold').checked=s.other;document.querySelector('#pm-state').textContent=s.pm?'PM 已完成':'PM 尚未完成';document.querySelector('#pm-card').className='ems-node '+(s.pm?'good':'bad');document.querySelector('#mon-state').textContent=['Daily MON 已逾期','MON 補做完成','結果已被接受','有效結果已更新'][s.phase];document.querySelector('#mon-detail').textContent=['曾經做過，不代表目前有效。','本例尚待結果判定；不直接解除阻擋。','本例尚待 EMS 條件更新。','本例 EMS 已反映有效的監控結果。'][s.phase];document.querySelector('#mon-card').className='ems-node '+(s.phase>=2?'good':'bad');document.querySelector('#ems-state').textContent=s.phase===3?'此項監控條件通過':'EMS 阻擋生產';document.querySelector('#ems-detail').textContent=s.phase===3?'不等於其他加工限制全部解除。':'Daily MON 條件尚未恢復有效。';document.querySelector('#ems-card').className='ems-node '+(s.phase===3?'good':'bad');const next=document.querySelector('#mon-next');next.textContent=['示例：補做 MON','示例：結果被接受','示例：EMS 更新有效結果','此項監控已更新'][s.phase];next.disabled=s.phase===3;document.querySelector('#process-result').textContent='';}
function attempt(){const issues=[];if(!s.pm)issues.push('PM 尚未完成');if(s.phase!==3)issues.push('EMS 的 Daily MON 條件尚未恢復有效');if(s.other)issues.push('另有有效 Hold');const r=document.querySelector('#process-result');r.className='result '+(issues.length?'bad':'');r.textContent=issues.length?'不能生產加工：'+issues.join('；')+'。':'本例 PM、Daily MON／EMS 與 Hold 檢查已通過。仍須核對設備、產品與配方等其他進站條件；此演示不會啟動機台。';}
function render(){const key=location.hash.slice(1)||'cw',idx=lessons.findIndex(([k])=>k===key);if(idx<0){location.replace('#cw');return;}document.title=lessons[idx][1]+'｜MES 教學';document.querySelector('#lesson-nav').innerHTML=lessons.map(([id,label])=>`<a href="#${id}" ${id===key?'aria-current="page"':''}>${label}</a>`).join('');document.querySelector('#content').innerHTML=({cw,subroute,move,monitor}[key])()+`<div class="footer-nav">${idx?`<a href="#${lessons[idx-1][0]}">← ${lessons[idx-1][1]}</a>`:'<a href="advanced.html#qtime">← 時間與配方</a>'}${idx<3?`<a href="#${lessons[idx+1][0]}">${lessons[idx+1][1]} →</a>`:'<a href="freshness.html">資料新鮮度 →</a>'}</div>`;({cw:updateCw,subroute:updateRoute,move:updateMove,monitor:updateMon}[key])();window.scrollTo(0,0);}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-zoom]');if(!b)return;if(b.dataset.cw){s.cw=b.dataset.cw;updateCw();}if(b.id==='route-next'&&s.route<3){s.route++;updateRoute();}if(b.id==='route-wrong')updateRoute('返回位置不符：本例必須回 F-DEMO v1 / S50，不能直接回 S60。');if(b.id==='route-reset'){s.route=0;updateRoute();}if(b.id==='move-normal'||b.id==='move-rework'){const rework=b.id==='move-rework',id='E'+s.serial++;s.events.push({id,lot:'L023',step:rework?'S40':'S50',kind:rework?'重工':'正常'});updateMove(`${id} 過站成立：${rework?'重工仍計入':'正常過站'}，Lot Move +1。`);}if(b.id==='move-duplicate'){const last=s.events.at(-1);updateMove(`重送 ${last.id} 是同一筆事件，沒有新增過站；Move 維持 ${s.events.length}。`);}if(b.id==='move-reset'){s.events=initialEvents();s.serial=104;updateMove();}if(b.id==='mon-next'&&s.phase<3){s.phase++;updateMon();}if(b.id==='mon-reset'){s.phase=0;updateMon();}if(b.id==='try-process')attempt();if(b.dataset.answer!==undefined){const q=b.closest('.quiz'),out=q.querySelector('.answer');q.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));out.className='answer result'+(Number(b.dataset.answer)===0?' warn':'');out.textContent=JSON.parse(out.dataset.feedback)[Number(b.dataset.answer)];}if(b.dataset.zoom){document.querySelector('#zoom-image').src=b.dataset.zoom;document.querySelector('#original-link').href=b.dataset.zoom;document.querySelector('#image-dialog').showModal();}if(b.id==='close-image')document.querySelector('#image-dialog').close();});
document.addEventListener('change',e=>{if(e.target.id==='pm-done'){s.pm=e.target.checked;updateMon();}if(e.target.id==='other-hold'){s.other=e.target.checked;updateMon();}});
window.addEventListener('hashchange',render);render();
