(() => {'use strict';
const cases=[
{id:'not-running',title:'Lot 為什麼尚未進機？',object:'Lot L023／EQP-A／LP1',time:'教學日 09:00',intro:'預派到 EQP-A，LP1 顯示 UP，但 Lot 仍是 Q。這些資訊能否直接解釋未進機原因？',micro:'Lot Q 是等待加工，R 才是加工中。Port UP 只代表上面有貨。可用機台、預派安排、實際位置、進機事件是不同的證據。',rows:[['08:50','Lot L023','預派 EQP-A'],['08:58','EQP-A / LP1','UP：有貨'],['09:00','Lot L023','Q：等待加工']],steps:['先核對同一 Lot、當前站點與各資料時間。Port 有貨還要核對 FOUP／Lot 裝載關係，不能假定就是 L023。','依當前站查看可用機台與預派目標，再核對實際載具位置。安排不等於搬送完成。','查 Lot 管制、QTime、Recipe／Tool 許可及設備／Chamber 狀態。這些是需要查的證據，本題未提供全部結果。','查該次 Lot 進機事件與資料更新時間；在證據不足時記錄待查項目，不能直接斷言機台故障或解除 Hold。'],topics:['lotstatus','portmode','available','prehistory','chamber'],route:'predispatch',question:'情境變化：LP1 仍為 UP，但核對後發現放的是另一個 Lot。哪個判斷成立？',answers:['L023 已加工，只是狀態延遲。','LP1 有貨不能證明 L023 到位；應繼續查 L023 的載具與執行事件。','只要預派完成，就不必查位置。'],correct:1,why:'Port 的狀態是位置上的有貨／無貨；必須把載具、Lot 與時間對上，才知道這份證據是否屬於 L023。'},
{id:'find-carrier',title:'FOUP 在那個時間到底在哪裡？',object:'FOUP F012',time:'教學日 10:02',intro:'想回查 F012 在 10:02 的位置，也想知道它當時裝了哪些 Wafer。',micro:'MCS 是原始傳送歷史；Macro 描述 E2E，Micro 可細到軌道轉彎。MFG_Carrier_Te_Ut 是 presum 過的傳送。內容物歷史另記 FOUP 在各時間點裝了哪些 Wafer。',rows:[['10:00','F012','命令：Stocker → EQP-A'],['10:02','F012','Micro 事件：轉彎點 B'],['10:04','F012','到達 EQP-A 的事件']],steps:['以 Carrier 與查詢時間找相關工作，分清命令目標及實際事件。','在 10:02 的示例只看截至該時點已有的事件：有轉彎點 B 的紀錄，尚不能說已到 EQP-A。','要查當時 Wafer，另查同一 FOUP 的內容物歷史；Split／Merge 會更新內容，不能拿現在的裝載回填過去。','使用 presum 結果時核對其時間範圍與整理粒度；不能假定已保留每一筆 Micro。'],topics:['mcs','transfer','contents','load'],route:'transfer',question:'情境變化：只有 10:00 的目的地命令，沒有後續位置事件。能說什麼？',answers:['已到達 EQP-A。','只能確認安排往 EQP-A，實際到達需事件證據。','F012 的所有 Wafer 都屬於同一 Lot。'],correct:1,why:'命令描述搬送安排，實際到達要用事件核對；FOUP 裝載也不能從目的地推論。'},
{id:'lot-history',title:'Lot 做過什麼？哪些算 Move？',object:'Lot L023',time:'教學日 08:00–12:00',intro:'同一批有 Hold、搬送、進機和重工。請分清批貨歷史與 Move 計數。',micro:'批貨歷史記錄 Lot 的各種動作。依本廠定義，每次 Lot 與機台發生進機事件記一筆 Move；重工進機也計入。搬送、Hold 本身不是 Move。',rows:[['08:10','L023','Hold'],['08:30','F012','搬送'],['09:00','L023 / S20','進機'],['11:00','L023 / S20','重工進機']],steps:['用 Lot 和查詢區間整理批貨歷史，保留動作種類與時間。','以 DM_MOVE_STEP 的進機事件追站點：示例 S20 出現两次，不能只保留不同站號而抹去重工。','本例有兩次進機，所以是兩筆 Move；Hold 與搬送不加入。','若資料連接後一筆事件變多列，核對事件識別與粒度，不能把重複列當成新 Move。每日廠區比較也要對齊統計期間。'],topics:['actions','move','lotstep'],route:'move',question:'情境變化：09:00 的進機事件接到兩筆群組關係後變成兩列；11:00 仍一列。本例有幾次 Move？',answers:['3 次，因為有三列。','1 次，同一站只能算一次。','2 次，兩次真正進機；連接複製不增加事件。'],correct:2,why:'統計單位是進機事件，既不能用 Join 後列數灌大，也不能按不同站點去重而刪掉重工。'},
{id:'product-hold',title:'為什麼同產品的 Lot 到站被攔住？',object:'Product P100／Lot L023、L024',time:'教學日 14:00',intro:'PID 為 P100 設定在 S50 暫置，方便後續統一處理。不同進度的 Lot 會如何判讀？',micro:'Product Hold 依產品與特定站點管制，Lot 屬於該產品且到達適用站點時被攔住。設定存在、條件符合、實際 Hold 紀錄要分開核對。',rows:[['14:00','P100','S50 Product Hold 設定'],['14:00','L023 / P100','到 S50，有對應攔截紀錄'],['14:00','L024 / P100','仍在 S40']],steps:['先確認 Lot 的 Product／PART 歸屬及當前站點。','查適用的 Product Hold 設定與相關時間，核對產品與站點。','L023 已到 S50 且有攔截紀錄；L024 尚在 S40，不能僅由同產品推定此刻已被這條 S50 規則攔截。','後續統一處理要依現場流程；這個練習只學查證，不提供解除管制操作。'],topics:['producthold','part','future','lotstatus'],route:'hold',question:'情境變化：L024 走到 S50，但目前只看得到規則設定，沒有狀態／事件更新。最合理的下一步？',answers:['規則存在，所以可宣稱已攔截完成。','核對規則仍適用與實際 Hold 紀錄、資料更新時間。','把 S50 視為所有產品都會 Hold。'],correct:1,why:'適用條件說明預期管制；宣稱實際發生仍需要對應 Lot 的狀態或事件及時間證據。'},
{id:'group-report',title:'KER 報表代表哪個機群、哪個時點？',object:'機群 G1／EQP-A',time:'教學日 09:10',intro:'報表有最近更新、每小時歷史，以及每天 07:20 的版本。能否直接拿來描述現在？',micro:'KER 是 Key EQP Report。同機台可屬多群，Chamber 也能獨立分群。ker_dm_bt 是最近更新；機群與機台歷史每小時一次；KER_WIP_Y_BTH 是每日 07:20 快照。',rows:[['最近一次更新','ker_dm_bt','機群指標，需核對實際更新時間'],['每小時','Ker_Dm_Hourly_Bth / Ker_Eqp_Aaa_Oee_Ut','機群／機台歷史'],['每日 07:20','KER_WIP_Y_BTH','機群狀況與 KPI 快照']],steps:['先決定對象是機台、Chamber、一般機群或 User SQL 虛擬群，記錄群組定義。','依問題選最近更新、每小時歷史或每日快照，核對實際資料時間與統計期間。','同機台可跨群。跨群合計機台數時先查重複成員；指標不可自行平均或加總，EFF 與彙總公式本教材不推定。','若要比較時點，保持群組範圍及時間口徑一致。07:20 的快照不能直接當 09:10 即時狀況。'],topics:['group','virtual','oee','wip'],route:'wip',question:'情境變化：EQP-A 同時屬 G1、G2，而 G2 另有 EQP-B。跨兩群共有幾台不同機台？',answers:['3 台，兩群列數相加。','2 台，EQP-A 只算一台；這不代表 KPI 可以直接平均。','無法知道任何機台數。'],correct:1,why:'兩群有三筆成員關係，但只有 EQP-A、EQP-B 兩台不同機台。機台去重與 KPI 彙總公式是不同問題。'}
];
const labels={lotstatus:'Lot 狀態',portmode:'Port 有貨／無貨',available:'可用機台',prehistory:'預派歷史',chamber:'Chamber',mcs:'MCS 原始傳送',transfer:'傳送歷史',contents:'FOUP 內容物歷史',load:'Lot／FOUP 裝載',actions:'批貨歷史',move:'Move 進機事件',lotstep:'Lot Step',producthold:'Product Hold',part:'PART／Flow',future:'Future Hold',group:'機台與機群',virtual:'SQL 虛擬機群',oee:'KER 目前與歷史',wip:'每日 07:20 快照'};
const key='mes054-task-work-v1';let saved={};let storageOK=true;try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch(e){storageOK=false}if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const write=()=>{try{localStorage.setItem(key,JSON.stringify(saved));return true}catch(e){storageOK=false;return false}};
let current;
function render(){current=cases.find(x=>x.id===location.hash.slice(1))||cases[0];const c=current;const state=saved[c.id]||{};document.getElementById('task-list').innerHTML=cases.map((x,i)=>`<a href="#${x.id}" ${x===c?'aria-current="page"':''}>${i+1}. ${x.title}</a>`).join('');
document.getElementById('task-work').innerHTML=`<p class="task-kicker">任務 ${cases.indexOf(c)+1} / ${cases.length} · 教學示例</p><h1 class="task-title">${c.title}</h1><p>${c.intro}</p><p class="progress" id="task-progress"></p><section class="task-step"><h3>1. 定義要查的對象與時間</h3><p>可改寫成你的練習查詢；下方事件維持固定教學示例，不會依輸入查詢真實資料。</p><div class="task-inputs"><label>對象<input name="object" value="${escape(state.object??c.object)}"></label><label>查詢時點／區間<input name="time" value="${escape(state.time??c.time)}"></label></div><p class="micro"><strong>先備微解說：</strong>${c.micro}</p></section><section class="task-step"><h3>2. 沿證據判讀</h3><div class="table-wrap"><table><caption>固定教學資料</caption><thead><tr><th>時間／頻率</th><th>對象／來源</th><th>觀察</th></tr></thead><tbody>${c.rows.map(r=>'<tr>'+r.map(v=>`<td>${v}</td>`).join('')+'</tr>').join('')}</tbody></table></div><ol class="evidence-list">${c.steps.map(x=>`<li>${x}</li>`).join('')}</ol><p>需要補概念時開啟主題；需要對照資料關係時進入 ER。</p><div class="evidence-links">${c.topics.map(x=>`<a href="topic.html?topic=${x}" data-topic-link="${x}">${x}</a>`).join('')}<a href="er-atlas.html?erRoute=${c.route}">在 ER 看這條關係</a></div></section><section class="task-step"><h3>3. 資料變了，你的判斷會改嗎？</h3><fieldset><legend>${c.question}</legend>${c.answers.map((x,i)=>`<label><input type="radio" name="answer" value="${i}" ${Number(state.answer)===i&&state.answer!==undefined?'checked':''}>${x}</label>`).join('')}</fieldset><div class="action-row"><button id="check-answer" type="button">檢查判斷與原因</button></div><p class="feedback" id="answer-feedback" role="status"></p></section><section class="task-step"><h3>4. 留下可交接的結論</h3><p>用自己的話寫出證據、限制與下一步。填寫紀錄會保留，但不會自動替自由回答評分。</p><div class="summary-grid">${[['known','已知：哪份證據支持什麼？'],['missing','不足：還缺哪個對象／時間／事件？'],['next','下一步：要查什麼來改變判斷？']].map(([k,label])=>`<label>${label}<textarea name="${k}">${escape(state[k]||'')}</textarea></label>`).join('')}</div><div class="action-row"><button id="save-summary" type="button">儲存交接摘要</button><button id="download-summary" type="button">下載本題 Markdown</button></div><p id="save-status" role="status"></p></section>`;
document.querySelectorAll('[data-topic-link]').forEach(a=>{a.textContent=labels[a.dataset.topicLink]||a.dataset.topicLink});
document.querySelectorAll('#task-work input,#task-work textarea').forEach(el=>el.addEventListener('input',()=>{const s=saved[c.id]||(saved[c.id]={});s[el.name]=el.value;if(el.name==='answer')s.checked=false;if(['known','missing','next'].includes(el.name))s.summarySaved=false;if(!write())document.getElementById('save-status').textContent='瀏覽器無法保存；請下載本題 Markdown。';updateProgress();if(el.name==='answer')document.getElementById('answer-feedback').textContent='';}));
document.getElementById('check-answer').onclick=()=>{const s=saved[c.id]||(saved[c.id]={});if(s.answer===undefined){document.getElementById('answer-feedback').textContent='先選一個判斷，再檢查原因。';return}s.checked=true;write();showAnswer();updateProgress()};
document.getElementById('save-summary').onclick=()=>{const s=saved[c.id]||(saved[c.id]={});s.object=document.querySelector('[name=object]').value;s.time=document.querySelector('[name=time]').value;s.summarySaved=['known','missing','next'].every(k=>String(s[k]||'').trim());const ok=write();document.getElementById('save-status').textContent=!ok?'瀏覽器無法保存；請下載本題 Markdown。':s.summarySaved?'交接摘要已保存。自由回答尚待自己或導師檢視。':'草稿已保存；請補齊已知、不足、下一步。';updateProgress()};
document.getElementById('download-summary').onclick=()=>{const s=saved[c.id]||{};const body=`# ${c.title}\n\n教學練習，非真實 MES 查詢\n\n對象：${s.object??c.object}\n時間：${s.time??c.time}\n\n## 已知\n${s.known||'未填'}\n\n## 不足\n${s.missing||'未填'}\n\n## 下一步\n${s.next||'未填'}\n\n判斷題：${s.checked&&Number(s.answer)===c.correct?'答對':'尚未答對'}\n自由回答：待檢視\n`;const url=URL.createObjectURL(new Blob([body],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=c.id+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
if(state.checked)showAnswer();updateProgress();document.title=c.title+'｜MES 現場問題';}
function showAnswer(){const s=saved[current.id]||{};document.getElementById('answer-feedback').textContent=(Number(s.answer)===current.correct?'判斷正確。':'再想一想。')+current.why}
function updateProgress(){const s=saved[current.id]||{};document.getElementById('task-progress').textContent=`判斷題：${s.checked&&Number(s.answer)===current.correct?'答對':'尚未答對'} ／ 交接摘要：${s.summarySaved?'已填寫，待檢視':'草稿／尚未完成'}${storageOK?'':' ／ 本機保存不可用'}`}
window.addEventListener('hashchange',()=>{render();document.getElementById('task-work').scrollIntoView({block:'start'})});render();
document.getElementById('count-mode').onchange=e=>document.getElementById('count-result').textContent=e.target.value==='tools'?'2 台不同機台：EQP-A、EQP-B。機台去重不會決定 KPI 彙總方式。':'3 筆對應關係；EQP-A 在兩個機群各出現一次。';
})();
