from pathlib import Path
import json,html
r=Path(__file__).resolve().parents[2]
w=r/'workitems/mes-008'
p=r/'AGENTS.md';s=p.read_text(encoding='utf-8');s=s.replace('新鮮度尚在製作，使用者審閱 pending。','MES-008六節與12張主圖已更新，逐頁評比見 workitems/mes-008/REVIEW.md、review.json。驗證 python tests/check_freshness_v2.py；封存一致性 python tools/verify_mes008_evidence.py。使用者審閱 pending。');p.write_text(s,encoding='utf-8')
p=r/'WORKITEMS.md';s=p.read_text(encoding='utf-8');s=s.replace('狀態：製作中；使用者未驗收。','狀態：六節／12張主圖已更新，18版面與190操作驗證通過；逐頁評比見 workitems/mes-008/REVIEW.md。使用者未驗收。',1);p.write_text(s,encoding='utf-8')
p=r/'TEACHING_REVIEW_LOG.md';s=p.read_text(encoding='utf-8');s=s.replace('新鮮度製作中，未評分，user_acceptance: pending。','六节与12張主圖已更新；18種版面、190項操作驗證通過。實看手機後再重製architecture與decision大字版本。逐頁／逐圖分項及退回紀錄見 [REVIEW](workitems/mes-008/REVIEW.md)，啟用圖片在 assets/freshness-v2。作者評比不代表真人學習效果，user_acceptance: pending。',1);p.write_text(s,encoding='utf-8')
p=r/'README.md';s=p.read_text(encoding='utf-8');s=s.replace('`freshness.html/js/css` 為第四部分。','第四部分入口是 `freshness.html`；`freshness-v2.js/css` 管六節內容與互動，`freshness.js` 管導覽與時間狀態。舊 `freshness.css` 不再被頁面引用。');s=s.replace('## 視覺與維護','''## 視覺與維護

MES-008 已重製資料新鮮度六節，啟用12張桌面／手機圖位於 `assets/freshness-v2/`。每節有主圖、互動與換條件自測；契約頁可檢视逐欄時間及下載示例JSON。製作前brief、退回稿與逐頁評比見 [MES-008 PLAN](workitems/mes-008/PLAN.md)、[REVIEW](workitems/mes-008/REVIEW.md)、[實圖比較](workitems/mes-008/review.html)。MES-007新鮮度高分已撤回；新版作者評比與使用者認可分開，使用者審閱仍 pending。
''',1);s=s.replace('## 驗證','''## 驗證

目前資料新鮮度：`python tests/check_freshness_v2.py`（18版面、190操作），`python tools/verify_mes008_evidence.py`（資產／證據／評分加總一致，無自動品質判斷）。MES-007 manifest為歷史版本，新freshness檔案已由MES-008取代；不要重寫歷史hash讓舊檢查假裝適用。
''',1);p.write_text(s,encoding='utf-8')
p=w/'PLAN.md';p.write_text(p.read_text(encoding='utf-8')+'''
## 實作與驗證結果

六節、12張主圖（六桌面／六手機）、六互動區、六題18項回饋及契約下載已接回網頁。先經AI原型，再逐張檢查與修正。桌面1440、平板800、手機360共18版面及190操作通過；手機實看發現過小標籤後再重製兩圖並重跑。見 REVIEW.md、review.json、evidence-manifest.json。使用者審閱pending，沒有真人學習測試。
''',encoding='utf-8')
reviews=json.loads((w/'review.json').read_text(encoding='utf-8'))
desktops={x['id'].split('/')[0]:x['asset'] for x in reviews['images'] if '/desktop-' in x['id']}
mobiles={x['id'].split('/')[0]:x['asset'] for x in reviews['images'] if '/mobile-' in x['id']}
names={'architecture':'架構','decision':'選擇原則','ai':'AI案例','history':'歷史與現在','join':'同列時間差','contract':'Data Contract'}
data=[{'id':i,'title':n,'desktop':'../../'+desktops[i],'mobile':'../../'+mobiles[i],'old':f'../../tests/evidence/mes-007/freshness-{i}-1440.png'} for i,n in names.items()]
gallery='''<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MES-008｜實圖比較</title><style>body{font:16px/1.7 'Segoe UI','Microsoft JhengHei',sans-serif;background:#f2f6fa;color:#15314e;margin:0}main{max-width:1200px;margin:auto;padding:25px}h1{font-size:28px}nav,.controls{display:flex;gap:9px;flex-wrap:wrap;margin:20px 0}button,a{font:inherit;color:#155daa}button{border:1px solid #bed0e2;background:white;border-radius:7px;padding:8px 14px;cursor:pointer}button[aria-pressed=true]{background:#155daa;color:white}figure{margin:0;padding:12px;background:white;border:1px solid #d1deeb;border-radius:12px}img{display:block;width:100%;height:auto}figure.phone{max-width:360px}figcaption{padding:10px;font-size:13px;color:#506b86}.note{border-left:4px solid #dca538;background:#fff4cc;padding:15px 20px}.links{display:flex;gap:20px}button:focus-visible,a:focus-visible{outline:3px solid #e4ab28;outline-offset:3px}@media(max-width:600px){main{padding:16px}}</style><main><h1>資料新鮮度：參考與新舊畫面</h1><p>第一課是使用者指出的較好參考。舊版高分已撤回；新版有逐圖退回與實際頁面檢查，尚未獲使用者驗收。</p><p class="links"><a href="../../freshness.html">開啟教學</a><a href="REVIEW.md">分項與修正紀錄</a></p><nav aria-label="選擇章節">'''+''.join(f'<button data-chapter="{i}" aria-pressed="{str(j==0).lower()}">{n}</button>' for j,(i,n) in enumerate(names.items()))+'''</nav><div class="controls" role="group" aria-label="比較畫面"><button data-mode="desktop" aria-pressed="true">新版桌面主圖</button><button data-mode="mobile" aria-pressed="false">新版手機主圖</button><button data-mode="old" aria-pressed="false">上版完整頁</button><button data-mode="reference" aria-pressed="false">第一課參考</button></div><p class="note" id="caption"></p><figure id="figure"><img id="art" alt=""><figcaption id="file"></figcaption></figure></main><script>const data='''+json.dumps(data,ensure_ascii=False)+''';let id='architecture',mode='desktop';function render(){const r=data.find(x=>x.id===id);const src=mode==='reference'?'../../examples/fab-physical-data-v01.png':r[mode];document.querySelector('#art').src=src;document.querySelector('#art').alt=r.title+'比較畫面';document.querySelector('#file').textContent=src;document.querySelector('#caption').textContent=mode==='reference'?'參考：設備→同載具局部→資料欄位，三者有可追蹤對應。':r.title+'｜'+({desktop:'新版主圖。原圖與實际頁面另有1440/800/360截圖。',mobile:'手機版以360px展示；必要標籤須直接可讀。',old:'MES-007歷史畫面。原始評分已撤回，不代表現在版本。'}[mode]);document.querySelector('#figure').classList.toggle('phone',mode==='mobile');document.querySelectorAll('[data-chapter]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.chapter===id));document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===mode));}document.addEventListener('click',e=>{if(e.target.dataset.chapter)id=e.target.dataset.chapter;if(e.target.dataset.mode)mode=e.target.dataset.mode;render();});render();</script></html>'''
(w/'review.html').write_text(gallery,encoding='utf-8')
