const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes=[
{id:'load',title:'Lot 裝在哪個 FOUP？',refs:['2671:lot','2671:cast-link','2671:cast'],meaning:'LOT 是生產批次，FOUP 是實體載具；中間的「放在／FRCAST_LOT」保留裝載對應。兩個物件的身分不相同。'},
{id:'slot',title:'Slot 與裝載關係',refs:['2671:lot','2671:slot','2671:cast'],meaning:'「在 Slot／fhwlths」與「放在／FRCAST_LOT」是原圖中分開的兩條關係。不能因為都描述裝載就把資料對象合併。'},
{id:'location',title:'FOUP 位於哪台設備？',refs:['2671:cast','2671:location','2671:eqp'],meaning:'「位於／CSFHDOPHS」連接載具與設備，是原圖提供的位置關係。這條線本身不證明晶圓正在加工，還須核對資料時間與執行紀錄。'},
{id:'predispatch',title:'FOUP 預派到哪台設備？',refs:['2671:cast','2671:predispatch','2671:eqp'],meaning:'預派描述安排，與「位於」是兩條不同關係。即使端點都是 FOUP 與設備，也不能把兩條線合併。'},
{id:'lot-pre',title:'Lot 預到哪台設備？',refs:['2671:lot','2671:lot-eqp','2671:eqp'],meaning:'這裡起點是 Lot，關係表是 FRLOT_EQP；FOUP 預派則使用另一個關係表。批次安排與載具安排各自保留。'},
{id:'port',title:'Lot 與 Port 的交接關係',refs:['2671:lot','2671:port-link','2671:port','2671:has','2671:eqp'],meaning:'原圖保留「EI 在／FREQP_LOT」及設備擁有 Port 的關係。EI 沿用廠內文字；不自行展開縮寫，也不把 Siview.Port 等同未確認的 FRPORT。'},
{id:'flow',title:'Lot 如何接到 Flow？',refs:['2673:lot','2673:flow-link','2673:flow'],meaning:'同一個 FRLOT 匯集不同原圖的關係。這條支線經 Part／Mainpd_id 指向流程定義；Lot 當前進度仍是另一個問題。'},
{id:'lr',title:'Flow 與 LR 的關係',refs:['2673:flow','2673:lr-eqp-link','2673:lr-eqp'],meaning:'Flow 透過 LCRECIPE_ID 關係連到 LR／設備對應表。同表另一個出現位置也匯集在這個實體上，但兩種原始關係都保留。'},
{id:'pd',title:'PD 與設備配對',refs:['2677:pd','2677:pd-key','2677:pd-eqp','2677:eqp-id','2677:eqp'],meaning:'FRPD、SYSTEMKEY、FRPD_EQP 與 EQP_ID 分別保留。這個 SYSTEMKEY 屬於此路徑，不能與 Recipe 的 SYSTEMKEY 合併。'},
{id:'recipe',title:'ER 配置與機台',refs:['2677:recipe','2677:recipe-key','2677:recipe-eqp','2677:eqp-id','2677:eqp'],meaning:'FRMRCP 經 SYSTEMKEY 與 FRMRCP_EQP 接到設備；這是配置關係，不能當作某個 Lot 已使用某份 Physical Recipe 的證據。'},
{id:'chamber',title:'EQP 與 Chamber',refs:['2674:eqp','2674:chamber-link','2674:chamber','2674:detail-link','2674:chamber-detail'],meaning:'設備、Chamber 狀況及 Chamber 細部資料分開存在。原框內同列兩張表時，保留原框，不擅自補出兩表間的 Join。'},
{id:'hold',title:'Lot 的 Future Hold',refs:['2673:lot','2673:future-link','2673:future'],meaning:'Future Hold 是未來條件的管制安排，不表示此刻已經 Hold；不得與 Product Hold 或 Qtime 歷史合成同一個實體。'},
{id:'move',title:'Lot Move 與 WIP 的共同歷史',refs:['2672:lot','2672:move-link','2672:move','2675:move-link','2675:lot'],meaning:'兩圖的 Move 歷史表匯集到同一實體，兩側各保留自己的關係。FRLOT 與 KER_WIP_BT 都描述批次，但不是同一張表。重工過站計入 Move；Join 後重複列不算新事件。'},
{id:'transfer',title:'FOUP 的搬送歷史',refs:['2672:cast','2672:mcs-transfer','2672:mcs-history'],meaning:'Carrier_id／transfer_job_id 的搬送歷史以載具為對象。它與 Lot 過站不同，一次搬送不自動等於一次 Move。'},
{id:'qtime',title:'Step 與 Qtime 歷史',refs:['2672:step','2672:qtime-link','2672:qtime'],meaning:'原圖透過 Lot_ID／Ope_no 從 Step 歷史連到 Qtime 歷史。起訖事件、限值與超時處置仍需按實際規則判讀。'},
{id:'wip',title:'WIP 與固定時間快照',refs:['2675:lot','2675:wip-link','2675:wip-history'],meaning:'這張歷史 WIP 標明星期一07:20的快照。歷史 Lot_ID 關係不能讓這份快照變成現在的狀態。'},
{id:'oee',title:'機台與期間 OEE',refs:['2675:eqp','2675:eqp-oee-link','2675:eqp-oee'],meaning:'這裡保留機台與 OEE 歷史表的 EQP_ID 關係。UP 是加工狀態，AVL 是期間比率；不把 OEE、AVL、Eff 當同義字。'}
];
const questions=[
{id:'where',title:'預派到 ETCH-03，就代表已到了嗎？',routes:['load','predispatch','location','lot-pre'],text:'先分清批次與載具，再比較同一 FOUP 到設備的「預派」與「位於」兩條關係。',answer:'不能。預派是安排；位置需要另一條關係的資料與時間證據。也不能由位置直接推論正在加工。'},
{id:'ready',title:'現在能在這台設備加工嗎？',routes:['flow','lr','hold','chamber'],text:'從 Lot 的流程定義，走到配方配置，再查批次管制及指定加工資源。',answer:'只有設備對應不夠。還需當前站、Hold、設備／Chamber與MON等條件；Daily MON逾期卡EMS是已確認廠內規則，但七圖沒有完整放行schema。'},
{id:'recipe',title:'哪份 Recipe 才是這次實際使用的？',routes:['lr','pd','recipe'],text:'分別沿 LR、PD、ER 配置路徑閱讀。相同 SYSTEMKEY 字樣保留在各自路徑，不做全域合併。',answer:'配置不等於執行紀錄。真正的 Physical Recipe 仍須對到該次 Lot、設備、時間及版本，七圖尚未完整提供這段。'},
{id:'move',title:'搬一次 FOUP，是不是多一次 Move？',routes:['transfer','move'],text:'比較 Carrier／MCS 搬送路徑與 Lot Move 路徑，觀察兩者起點與中介鍵的差異。',answer:'不是。搬送對象是載具；Move是Lot過站事件，重工計入。示例一批過站後重工再過站，共2次Move，不能用搬送次數代替。'},
{id:'time',title:'現在 UP，報表能直接當現在嗎？',routes:['wip','oee'],text:'從 WIP 的固定時間快照，切到設備 OEE 期間資料；留意不同的表與關係。',answer:'不能。UP是加工狀態，AVL是一定期間的Availability比率。固定快照、事件與統計各有時間範圍；逐表延遲仍需資料契約。'}
];
let model,svg,allBox,view,activeRoute='load',nodes,edges,drag=null,moved=false,startNode=null;const pointers=new Map();let pinch=null;let walkIds=[],walkEdges=[],walkIndex=0;

let displayMode='overview',activeEntity=null,framedIds=[];
const teaching={
overview:{image:'examples/fab-physical-data-v01.png',alt:'機台、FOUP、Slot、Wafer 與 Lot 資料對照',caption:'左側是現場，右側是資料。Lot 是生產批次；FOUP 是承載晶圓的實體容器。',link:'index.html#fab'},
lot:{title:'Lot：生產批次',refs:['2671:lot','2676:lot'],color:'#176ac2',image:'examples/fab-physical-data-v01.png',alt:'現場物件與右側 Lot L023 的資料對照',caption:'看右側 lot_id = L023：Lot 將這批晶圓組織成生產與追蹤單位。',meaning:'藍框標出 Lot 資料實體。Lot 本身不是盒子；沿著「放在」關係，才會找到承載它的 FOUP。不同 schema 證據的節點仍各自保留。',link:'index.html#lot'},
carrier:{title:'FOUP：承載晶圓的容器',refs:['2671:cast','2676:cast'],color:'#008775',image:'examples/fab-physical-data-v01.png',alt:'FOUP F012 內的 Slot 07 與 Wafer W07',caption:'看中間剖面：FOUP 內有 Slot，晶圓放在對應位置。',meaning:'綠框標出 FOUP 資料實體。FRCAST 描述載具，FRCAST_LOT 表達與 Lot 的裝載關係；兩者不是同一個物件。',link:'index.html#foup'},
equipment:{title:'EQP：執行作業的設備',refs:['2671:eqp','2676:eqp','2677:eqp'],color:'#b26018',image:'examples/fab-physical-data-v01.png',alt:'FOUP F012 放在 ETCH-03 設備的 LP1',caption:'看左側 ETCH-03 與 LP1：設備、Port、FOUP 有不同身分。',meaning:'橘框標出 EQP 資料實體。設備可與 Port、Chamber、派工及 Recipe 配置相連；「預派」不能直接證明載具已經到達。',link:'operations.html#port'},
flow:{title:'Flow：批次遵循的製程路徑',refs:['2673:flow'],color:'#7756af',image:'assets/mes-v3/stage-v2.png',alt:'三個 Stage、六個 Step，以及目前在 S50 的 Lot',caption:'整條是 Flow；每段是 Stage；每一站是 Step。Lot 有自己的執行進度。',meaning:'紫框標出 Flow 資料對象。從 Lot 的 Part／Mainpd_id 關係找到流程定義，再區分「路徑如何定義」與「這批目前走到哪裡」。',link:'flow.html#stage'},
recipe:{title:'Recipe：從邏輯要求到設備配置',refs:['2673:lr-eqp','2677:recipe'],color:'#7756af',image:'assets/mes-009/recipes.png',alt:'LR、ER 與實際加工 Physical Recipe 的教學對照',caption:'示意值用來理解三層概念；實際名稱與映射仍以廠內定義為準。',meaning:'紫框分別指出 LR 與 ER 相關資料。ER 連線呈現配置關係；要知道某批實際用了哪個 Physical Recipe，還需要該次執行紀錄及版本證據。',link:'advanced.html#recipes'}
};
function teachingForNode(id){
 for(const key of ['recipe','equipment','carrier','lot','flow'])if(teaching[key].refs.some(ref=>model.mapping[ref]===id))return key;
 const recipeRefs=['2677:recipe-key','2677:recipe-eqp','2677:pd','2677:pd-key','2677:pd-eqp','2673:lr-eqp-link'];
 if(recipeRefs.some(ref=>model.mapping[ref]===id))return 'recipe';
 return 'overview';
}
function showTeaching(key){const t=teaching[key]||teaching.overview;$('teaching-image').src=t.image;$('teaching-image').alt=t.alt;$('teaching-caption').textContent=t.caption;$('teaching-link').href=t.link;}
function clearFrames(){framedIds=[];activeEntity=null;svg?.querySelector('#entity-frames')?.remove();$('entity-targets').replaceChildren();document.querySelectorAll('[data-entity]').forEach(b=>b.setAttribute('aria-pressed','false'));}
function drawFrames(){svg.querySelector('#entity-frames')?.remove();if(!framedIds.length)return;const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.id='entity-frames';g.style.pointerEvents='none';const scale=Math.min($('canvas').clientWidth/view[2],$('canvas').clientHeight/view[3]);const pad=7/scale;for(const id of framedIds){const b=box(id),r=document.createElementNS(ns,'rect');for(const [k,v] of Object.entries({x:b.x-pad,y:b.y-pad,width:b.w+2*pad,height:b.h+2*pad,rx:4/scale,fill:'none',stroke:teaching[activeEntity].color,'stroke-width':3/scale}))r.setAttribute(k,v);g.append(r);}svg.append(g);}
function frameEntity(key){overview();const t=teaching[key];activeEntity=key;displayMode='entity';framedIds=[...new Set(t.refs.map(r=>model.mapping[r]).filter(Boolean))];drawFrames();showTeaching(key);inspect(framedIds,t.title,t.meaning);$('entity-targets').innerHTML='<h3>框選位置 · 點一下放大</h3>'+framedIds.map((id,i)=>`<button data-target="${id}">${i+1}. ${nodes.get(id).labels.map(esc).join(' / ')} ↗</button>`).join('');document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{fitIds([b.dataset.target],true);$('status').textContent='已放大框選物件。按「全圖總覽」回到完整 ER。'});document.querySelector(`[data-entity="${key}"]`).setAttribute('aria-pressed','true');$('status').textContent=`已框選 ${framedIds.length} 個 ${t.title.split('：')[0]} 資料位置；全部 ${model.nodes.length} 個節點與 ${model.edges.length} 條連線仍保留。`;}
document.querySelectorAll('[data-entity]').forEach(b=>b.onclick=()=>{if(model)frameEntity(b.dataset.entity)});
$('clear-entity').onclick=()=>{if(svg)overview()};
$('open-teaching').onclick=()=>{$('teaching-large').src=$('teaching-image').src;$('teaching-large').alt=$('teaching-image').alt;$('teaching-large-caption').textContent=$('teaching-caption').textContent;$('teaching-dialog').showModal()};

const mode=new URLSearchParams(location.search).get('view')==='questions';
$('question-panel').hidden=!mode;$(mode?'question-mode':'original-mode').setAttribute('aria-current','page');
function setView(v){view=v;svg.setAttribute('viewBox',v.join(' '));$('zoom-label').textContent=Math.round($('canvas').clientWidth/v[2]*100)+'%';if(svg)drawFrames();}
function zoom(f,cx=.5,cy=.5){const w=view[2]*f,h=view[3]*f;if(w<140||w>allBox[2]*2)return;setView([view[0]+(view[2]-w)*cx,view[1]+(view[3]-h)*cy,w,h]);}
function box(id){const g=svg.getElementById(id),b=g.getBBox(),m=svg.getCTM().inverse().multiply(g.getCTM());const p=new DOMPoint(b.x,b.y).matrixTransform(m),q=new DOMPoint(b.x+b.width,b.y+b.height).matrixTransform(m);return {x:p.x,y:p.y,w:q.x-p.x,h:q.y-p.y};}
function fitIds(ids,allowTiny=false){const bs=ids.map(box),x=Math.min(...bs.map(b=>b.x)),y=Math.min(...bs.map(b=>b.y)),r=Math.max(...bs.map(b=>b.x+b.w)),bt=Math.max(...bs.map(b=>b.y+b.h));const cw=$('canvas').clientWidth,ch=$('canvas').clientHeight;let w=Math.max(r-x+80,cw/1.2),h=Math.max(bt-y+80,ch/1.2);if(w/h<cw/ch)w=h*cw/ch;else h=w*ch/cw;if(!allowTiny&&cw/w<.8){focusStep(Math.min(1,walkIds.length-1));return false;}setView([x+(r-x-w)/2,y+(bt-y-h)/2,w,h]);return true;}
function focusStep(i){if(!walkIds.length)return;walkIndex=Math.max(0,Math.min(walkIds.length-1,i));const id=walkIds[walkIndex],b=box(id),cw=$('canvas').clientWidth,ch=$('canvas').clientHeight;const scale=.9,w=cw/scale,h=ch/scale;setView([b.x+b.w/2-w/2,b.y+b.h/2-h/2,w,h]);$('step-label').textContent=`${walkIndex+1} / ${walkIds.length} · ${nodes.get(id).labels[0]}`;$('status').textContent='沿線閱讀：'+nodes.get(id).labels.join(' / ')+'。保留90%可讀尺寸；超出畫面的相鄰節點可用上一點／下一點定位。';document.querySelectorAll('[data-inspect]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.inspect===id));}
function setupWalk(ids,es){walkEdges=es;const adjacent=(a,b)=>edges.some(e=>es.includes(e.id)&&((e.a===a&&e.b===b)||(e.a===b&&e.b===a)));if(ids.every((id,i)=>i===0||adjacent(ids[i-1],id)))walkIds=ids;else{walkIds=[];const visited=new Set();function visit(id){visited.add(id);walkIds.push(id);for(const next of ids){if(!visited.has(next)&&adjacent(id,next)){visit(next);walkIds.push(id)}}}visit(ids[0]);}walkIndex=0;$('step-label').textContent=`${ids.length} 個節點 · 可沿線逐點讀`;}

function mark(ids,edgeIds){svg.querySelectorAll('[data-node]').forEach(g=>g.style.opacity=ids.includes(g.id)?'1':'.14');svg.querySelectorAll('[data-edge]').forEach(g=>{const on=edgeIds.includes(g.id);g.style.opacity=on?'1':'.08';g.querySelectorAll('path').forEach(p=>{p.style.stroke=on?'#244c6b':'#7c8c9c';p.style.strokeWidth=on?'3':'1.7'})});}
function inspect(ids,title,meaning){$('selection-title').textContent=title;$('meaning').textContent=meaning;const actual=edges.filter(e=>ids.includes(e.a)&&ids.includes(e.b));$('path-list').innerHTML=actual.map(e=>`<div class="edge-pair"><button data-inspect="${e.a}">${nodes.get(e.a).labels.map(esc).join('<br>')}</button><span>— 原圖連線 —</span><button data-inspect="${e.b}">${nodes.get(e.b).labels.map(esc).join('<br>')}</button></div>`).join('');$('sources').innerHTML=ids.map(id=>{const n=nodes.get(id);return `<article><strong>${n.labels.map(esc).join(' / ')}</strong>${n.schema_missing?'<p>原圖未列 schema；保留此來源的獨立節點。</p>':''}${n.refs.map(r=>`<p><a href="data-map.html?view=original#${r.source}">來源 ${r.source}</a> · ${esc(r.node)}<br>${r.labels.map(esc).join('<br>')}</p>`).join('')}</article>`}).join('')+(model.sourceNotes||[]).filter(note=>ids.some(id=>nodes.get(id).refs.some(r=>r.source===note.source))).map(note=>`<p>${esc(note.text)}</p>`).join('');document.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=()=>{const i=walkIds.indexOf(b.dataset.inspect);i>=0?focusStep(i):selectNode(b.dataset.inspect)});}

function route(id){clearFrames();displayMode='route';document.querySelector('.walk-tools').hidden=false;showTeaching(({load:'lot',slot:'carrier',location:'equipment',predispatch:'equipment','lot-pre':'equipment',port:'equipment',flow:'flow',lr:'recipe',pd:'recipe',recipe:'recipe',chamber:'equipment',hold:'lot',move:'lot',transfer:'carrier',qtime:'flow',wip:'lot',oee:'equipment'})[id]||'lot');const r=routes.find(r=>r.id===id)||routes[0];activeRoute=r.id;const ids=r.refs.map(ref=>model.mapping[ref]);const edgeIds=[];for(let i=1;i<ids.length;i++){const e=edges.find(e=>(e.a===ids[i-1]&&e.b===ids[i])||(e.b===ids[i-1]&&e.a===ids[i]));if(!e)throw Error('路徑缺少原始連線 '+r.id);edgeIds.push(e.id)}mark(ids,edgeIds);setupWalk(ids,edgeIds);inspect(ids,r.title,r.meaning);$('status').textContent=r.title+' · '+ids.length+' 個節點／'+edgeIds.length+' 條原始關係';fitIds(ids);document.querySelectorAll('[data-route]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.route===r.id));}
function selectNode(id){clearFrames();displayMode='node';document.querySelector('.walk-tools').hidden=false;showTeaching(teachingForNode(id));if(teachingForNode(id)==='overview')document.getElementById('teaching-caption').textContent='現場物件基礎參考，非此節點專屬示意。請搭配上方節點說明及原始關係閱讀。';const n=nodes.get(id);let es=edges.filter(e=>e.a===id||e.b===id);if(n.kind==='rect'){const rel=es.find(e=>nodes.get(e.a===id?e.b:e.a).kind==='diamond')||es[0];if(rel){const other=rel.a===id?rel.b:rel.a;es=edges.filter(e=>e.a===other||e.b===other)}}const ids=[...new Set([id,...es.flatMap(e=>[e.a,e.b])])];mark(ids,es.map(e=>e.id));setupWalk(ids,es.map(e=>e.id));inspect(ids,n.labels[0],n.kind==='diamond'?'這個菱形保留原圖的關係／鍵。沿著實際連線查看兩端資料，不推定箭頭方向、PK/FK 或基數。':n.kind==='circle'?'這個橢圓保留原圖的概念／屬性註記；不直接當作已確認的資料表或欄位。':'這是原圖的資料對象。相同完整表名的重複出現匯集於此，其他表與關係仍分開保留。');$('status').textContent='已定位：'+n.labels.join(' / ');fitIds(ids);}
function overview(){clearFrames();displayMode='overview';document.querySelector('.walk-tools').hidden=true;walkIds=[];document.querySelectorAll('[data-route]').forEach(b=>b.setAttribute('aria-pressed','false'));inspect([],'完整 ER × 現場物件','先用左側大圖認識資料之間的關係，再按上方物件按鈕。彩色框指出資料位置；教學插圖說明它在現場代表什麼。');showTeaching('overview');setView(allBox.slice());svg.querySelectorAll('[data-node],[data-edge]').forEach(g=>g.style.opacity='1');svg.querySelectorAll('[data-edge] path').forEach(p=>{p.style.stroke='#7c8c9c';p.style.strokeWidth='1.7'});$('status').textContent='全圖：121 個節點、128 條關係都在圖上。請搜尋或選一段關係放大閱讀。';}
function question(id){const q=questions.find(q=>q.id===id)||questions[0];$('question-copy').innerHTML=`<strong>${q.title}</strong><p>${q.text}</p><div class="choices">${q.routes.map(id=>`<button data-route="${id}">${routes.find(r=>r.id===id).title}</button>`).join('')}</div><p class="answer">${q.answer}</p>`;bindRoutes();document.querySelectorAll('[data-question]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.question===q.id));route(q.routes[0]);}
function bindRoutes(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));}
async function start(){const [m,text]=await Promise.all([fetch('ER/INTEGRATED/er-model-v2.json').then(r=>r.json()),fetch('ER/INTEGRATED/fab-er-v2.svg').then(r=>r.text())]);model=m;nodes=new Map(m.nodes.map(n=>[n.id,n]));edges=m.edges;const parsed=new DOMParser().parseFromString(text,'image/svg+xml');svg=document.importNode(parsed.documentElement,true);$('canvas').replaceChildren(svg);svg.setAttribute('width','100%');svg.setAttribute('height','100%');allBox=svg.getAttribute('viewBox').split(/\s+/).map(Number);$('counts').textContent=`${m.nodes.length} 個可見節點 · ${m.edges.length} 條關係`;svg.querySelectorAll('[data-node]').forEach(g=>{g.addEventListener('click',()=>{if(!moved)selectNode(g.id)});g.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();selectNode(g.id)}})});$('routes').innerHTML=routes.map(r=>`<button data-route="${r.id}">${r.title}</button>`).join('');bindRoutes();$('questions').innerHTML=questions.map(q=>`<button data-question="${q.id}">${q.title}</button>`).join('');document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{history.replaceState(null,'','#'+b.dataset.question);question(b.dataset.question)});mode?question(location.hash.slice(1)):overview();window.ER_ATLAS={model,frameEntity,route,overview,selectNode,box,getView:()=>view.slice(),focusStep,getWalk:()=>walkIds.slice()};}
$('path-overview').onclick=()=>{fitIds(walkIds,true);$('status').textContent='本段全貌：用來辨識路徑結構；按沿線上一點／下一點回到可讀尺寸。'};$('step-prev').onclick=()=>focusStep(walkIndex-1);$('step-next').onclick=()=>focusStep(walkIndex+1);
$('overview').onclick=()=>overview();$('core').onclick=()=>route('load');$('zoom-in').onclick=()=>zoom(.8);$('zoom-out').onclick=()=>zoom(1.25);
$('find').oninput=()=>{if(!model)return;const q=$('find').value.trim().toLowerCase();$('search-results').innerHTML=q?model.nodes.filter(n=>n.labels.some(s=>s.toLowerCase().includes(q))).slice(0,12).map(n=>`<button data-result="${n.id}">${n.labels.map(esc).join(' · ')}</button>`).join('')||'<p>沒有符合的節點</p>':'';document.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>{selectNode(b.dataset.result);$('search-results').innerHTML='';$('canvas').focus()})};
const canvas=$('canvas');canvas.addEventListener('wheel',e=>{if(!svg||!e.ctrlKey)return;e.preventDefault();const r=canvas.getBoundingClientRect();zoom(e.deltaY>0?1.1:1/1.1,(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height)},{passive:false});
canvas.addEventListener('pointerdown',e=>{if(!svg)return;moved=false;startNode=e.target.closest('[data-node]')?.id;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,v:view.slice()};if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),v:view.slice()}}});
canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&pinch){const [a,b]=[...pointers.values()],f=pinch.distance/Math.hypot(a.x-b.x,a.y-b.y);setView([pinch.v[0]+pinch.v[2]*(1-f)/2,pinch.v[1]+pinch.v[3]*(1-f)/2,pinch.v[2]*f,pinch.v[3]*f]);moved=true}else if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>4)moved=true;setView([drag.v[0]-dx*drag.v[2]/canvas.clientWidth,drag.v[1]-dy*drag.v[3]/canvas.clientHeight,drag.v[2],drag.v[3]])}});
function end(e){if(e.type==='pointerup'&&!moved&&startNode)selectNode(startNode);pointers.delete(e.pointerId);pinch=null;drag=null;startNode=null;}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);canvas.addEventListener('keydown',e=>{if(!svg)return;const k={ArrowLeft:[-.12,0],ArrowRight:[.12,0],ArrowUp:[0,-.12],ArrowDown:[0,.12]}[e.key];if(k){e.preventDefault();setView([view[0]+k[0]*view[2],view[1]+k[1]*view[3],view[2],view[3]])}});window.addEventListener('resize',()=>{if(svg&&['overview','entity'].includes(displayMode))setView(allBox.slice())});start().catch(e=>{$('loading')?$('loading').textContent='載入失敗：'+e.message:$('status').textContent='載入失敗：'+e.message;console.error(e)});
