'use strict';
const freshChapters=[
 ['architecture','同一個 Giga，不同的新鮮度','先看來源與查詢入口'],
 ['decision','晚十分鐘，會做錯事嗎？','用工作需求選來源'],
 ['ai','案例一：AI 發現異常之後','舊 Step 會導向錯誤決策'],
 ['history','案例二：經過，不等於現在','History 與 Current State'],
 ['join','案例三：表剛刷新，欄位仍舊','追到 Column 的來源時間'],
 ['contract','把判斷寫進 Data Contract','四句話與查詢前檢查']
];
const freshState={source:'native',tolerance:'monitor',decision:'analysis',history:'event',complete:'yes',refreshed:false,quiz:null};
const fresh$=s=>document.querySelector(s);
const verdict=t=>`<figcaption class="fresh-verdict">${t}</figcaption>`;
const arrow=t=>`<div class="data-arrow">↓ <span>${t}</span></div>`;
const note=(title,text)=>`<section class="fresh-note"><h2>${title}</h2><p>${text}</p></section>`;
const rowsTable=(head,rows)=>`<div class="table-scroll" tabindex="0" role="region" aria-label="資料對照表，可橫向捲動"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>`<td data-label="${head[i]}">${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const select=(id,label,options,value)=>`<label class="select-field" for="${id}"><span>${label}</span><select id="${id}">${options.map(([v,t])=>`<option value="${v}" ${value===v?'selected':''}>${t}</option>`).join('')}</select></label>`;
function architecture(){return `<h1>同一個 Giga Report，<br>資料也不一定一樣新。</h1><p class="lead">查詢入口只告訴你在哪裡拿資料。要判斷能不能拿來做現在的決策，還要知道資料從哪裡來、停在哪個時間。</p>
<figure class="fresh-figure" data-fresh-art="architecture"><h2>MMDB 是源頭，Giga 是查詢入口</h2><div class="source-core"><div class="database"><b>MES / MMDB</b><span>線上 Source of Truth</span></div><p>一般工程師不直接 Query MMDB</p></div><div class="source-fork" aria-hidden="true"></div><div class="architecture-branches">
<section class="reporting-path"><p class="path-label">分支 A · MMDB → Reporting</p><div class="db-slab"><strong>Reporting DB</strong><small>承接 SiView 資料</small></div>${arrow('供應查詢資料')}<div class="giga-boundary"><div class="window-bar"><i></i><i></i><i></i><strong>Giga Report</strong></div><p class="boundary-note">同一個查詢入口，包含兩類來源</p><div class="native-lane"><b>SiView Native</b><span class="age-tag">RT1 · 通常 &lt; 3 min</span><small>直接承接報表來源</small></div><div class="mart-line">SiView ＋ 其他 Mart／衍生資料<br><span>↓ Join · Transform · Aggregate · Refresh</span></div><div class="mart-lane"><b>Data Mart</b><span class="age-tag warm">RT2 · 約 10 min</span><small>多來源整理後供查詢</small></div></div></section>
<section class="inline-path"><p class="path-label">分支 C · MMDB → Inline</p><div class="db-slab"><strong>Inline DB</strong><small>本架構的獨立分支</small></div><p>目前未提供刷新與存取條件；不能替它猜一個延遲等級。</p></section>
<section class="tx-path"><p class="path-label">分支 B · MMDB ↔ TX</p><div class="db-slab"><strong>TX</strong><small>連到 MMDB 的交易介面</small></div>${arrow('Real-time Query')}<div class="tx-result"><b>RT0</b><strong>Transaction Real-time</strong><p>需要當下狀態時，<br>由 TX 取得。</p></div><p>這裡畫的是資料取得關係；工程師不因此獲得直接查 MMDB 的權限。</p></section></div>${verdict('判斷新鮮度，要看 Table／Column 的 Data Lineage，不能只看 Query 在哪裡。')}</figure>
${note('為什麼 Mart 可能較晚？','同一份資料經過 Join、Transform、Aggregate 與衍生邏輯，還可能等待其他 Mart 或排程刷新。最終欄位的時間受上游依賴影響；多一層處理不代表資料品質差，只代表用途與時間條件不同。')}
<div class="source-note">來源：依你提供的內部架構與通常延遲製作。&lt;3 分鐘／約10分鐘不是每次查詢的 SLA 保證；實際 Table／Column 仍以其 Data Contract 與時間欄位為準。</div>`;}
function decision(){return `<h1>「這個答案晚十分鐘，<br>會不會做錯事？」</h1><p class="lead">先決定你要做的事，再決定資料需要多新。分析昨天的產量，和判斷現在是否 Auto Hold，需要的證據不同。</p><figure class="fresh-figure" data-fresh-art="decision"><h2>依工作決定容許延遲</h2><div class="decision-root">資訊會用於「現在」的決策嗎？</div><div class="decision-tree"><div><span class="branch-answer">不會</span><div class="decision-leaf" data-level="analysis"><b>RT2 · Data Mart</b><p>History / Analytics</p><small>檢查統計期間與資料完整性</small></div></div><div class="decision-now"><span class="branch-answer">會 → 三分鐘延遲可接受嗎？</span><div class="decision-pair"><div><span class="branch-answer">三分鐘可接受</span><div class="decision-leaf" data-level="monitor"><b>RT1 · SiView Native</b><p>Near Real-time</p><small>再看本次來源時間</small></div></div><div><span class="branch-answer">三分鐘不可接受</span><div class="decision-leaf" data-level="control"><b>RT0 · TX → MMDB</b><p>Transaction Real-time</p><small>控制交易要再次驗證條件</small></div></div></div></div></div><div class="fresh-controls">${select('decision-purpose','換一個工作需求',[['analysis','昨天產量／Weekly Yield'],['monitor','允許最多 3 分鐘的線上監看'],['control','現在就要判斷是否 Auto Hold']],freshState.decision)}</div><div id="decision-answer" class="fresh-answer" role="status"></div>${verdict('先定義可容忍延遲，再驗證這次資料的時間。')}</figure>
${rowsTable(['等級','資料來源','通常新鮮度','合適用途'],[['L0 / RT0','TX → MMDB','交易層級即時','即時狀態、關鍵判斷；控制另依交易規則'],['L1 / RT1','Giga / SiView Native','&lt;3 min','工程查詢、近即時監看'],['L2 / RT2','Giga / Data Mart','約10 min 或依排程','分析、統計、報表、AI 訓練資料']])}
${note('較新不一定比較適合','Weekly Yield、Recipe 使用趨勢、Tool performance、Cycle time、Defect 統計與 AI 訓練通常需要整理過的歷史資料。用 Mart 可省下重做衍生邏輯與 Join 的工作；用於訓練時，還要檢查標籤與事件時間對齊。查「現在在哪個 Step／是否 Hold／是否 Move Out」則先考慮 Native，時間要求更嚴格時用 TX。')}`;}
function ai(){return `<h1>AI 發現異常，<br>這批真的還在 DEV 嗎？</h1><p class="lead">10:00，Vision AI 發現 Wafer 異常；10:01，你查 Lot A123 的 Current Step。下面是同一批、同一個查詢時刻的教學快照。</p><figure class="fresh-figure" data-fresh-art="ai"><h2>同一批 A123，不同來源停在不同時點</h2><div class="time-story"><div><time>09:51</time><b>DEV</b><span>A123 在這一站</span></div><span class="time-connector">→</span><div><time>10:00</time><b>ETCH</b><span>已到下一站 · AI 發現異常</span></div><span class="time-connector">→</span><div><time>10:01</time><b>現在查詢</b><span>本例線上仍在 ETCH</span></div></div><div class="fresh-controls">${select('ai-source','你查哪一類資料？',[['native','Giga / SiView Native'],['mart','Giga / Data Mart'],['tx','TX → MMDB']],freshState.source)}${select('ai-tolerance','答案拿來做什麼？',[['monitor','工程監看：可容忍 3 分鐘'],['control','Auto Hold：要求當下狀態']],freshState.tolerance)}</div><div class="query-window"><div class="window-bar"><i></i><i></i><i></i><strong id="query-source"></strong></div><div class="query-sub">查詢時間固定 10:01 · Lot A123</div><div class="query-result"><div><small>Current Step</small><strong id="query-step"></strong></div><div><small>Source data time</small><strong id="query-time"></strong></div><div><small>這筆內容的年齡</small><strong id="query-age"></strong></div></div><div class="age-track" aria-label="資料年齡：零至十分鐘"><span id="age-fill"></span><i>3 min</i></div><div class="axis-ends"><span>0 分鐘</span><span>10 分鐘</span></div></div><div id="ai-answer" class="fresh-answer" role="status"></div>${verdict('Data Mart 沒錯，只是你問錯問題。')}</figure>
${note('即時查到，也不等於之後不會改變','Native 的 ETCH@10:00 比 Mart 的 DEV@09:51 新，但仍是一分鐘前的狀態。若要立即 Auto Hold，應由核准 TX／控制交易在執行時重新核對 Lot、Step 與限制；單次 Query 不能保證後續操作時狀態仍相同。')}`;}
function history(){return `<h1>「有沒有經過 DEV」<br>和「現在在哪」是兩個問題。</h1><p class="lead">同一筆歷史事件可以完整而正確，卻不能直接回答目前位置。問「沒有紀錄」之前，也要先確認資料是否已收齊。</p><figure class="fresh-figure" data-fresh-art="history"><h2>A123 的昨天與現在</h2><div class="history-ribbon"><div><small>昨日 14:20</small><b>DEV · Move Out</b><span>事件被保留</span></div><div class="history-arrow">→ 經過其他站 →</div><div><small>今日 10:01</small><b>ETCH · Current</b><span>本例的線上狀態</span></div></div><div class="fresh-controls">${select('history-question','你問的是哪一種問題？',[['event','昨天有沒有經過 DEV？'],['current','現在還在 DEV 嗎？']],freshState.history)}${select('history-complete','Mart 的涵蓋條件',[['yes','昨日事件已收齊，包含 14:20'],['no','只收至昨日 14:00，後續待補']],freshState.complete)}</div><div class="event-book"><div class="book-heading"><strong>Data Mart · A123 事件簿</strong><span id="history-coverage"></span></div><div id="history-record"></div><p class="book-caption">事件時間 ≠ 查詢時間；已發生事件不會因 Lot 前進而消失。</p></div><div id="history-answer" class="fresh-answer" role="status"></div>${verdict('History 適合 Mart，仍要檢查期間、涵蓋截止與晚到資料。')}</figure>
${note('分析需要的是可解釋的期間','昨天產量或 Weekly Yield 的取數，先固定起迄時間、統計口徑、最後完整批次與補數方式。Mart 沒找到 DEV 事件，可能是沒發生，也可能尚未載入；缺少資料完整性證據時，不能直接判「沒經過」。')}`;}
function join(){return `<h1>表剛刷新，<br>每個欄位都變新了嗎？</h1><p class="lead">同一列也可能混合不同時間：Current Step 來自 SiView，Hold 欄位依賴另一個 Mart。只看整表刷新成功，會把較舊欄位一起誤認為即時。</p><figure class="fresh-figure" data-fresh-art="join"><h2>A123 的一列資料，兩個來源時間</h2><div class="join-sources"><div class="native-lane"><b>SiView Native</b><strong>Step = ETCH</strong><time>來源狀態：10:00</time></div><div class="mart-lane"><b>另一個 Mart</b><strong>Hold = N</strong><time>來源狀態：09:51</time></div></div><div class="join-arrows">↘ <span>依 Lot A123 合併</span> ↙</div><div class="query-window"><div class="window-bar"><i></i><i></i><i></i><strong>Giga Report / LOT_PROCESS_SUMMARY</strong></div><div class="query-sub">查詢時刻：10:01 · 表刷新時間：<b id="join-refresh-time">10:00</b></div><div class="joined-row"><div><small>Lot</small><strong>A123</strong></div><div><small>Current Step</small><strong>ETCH</strong><span>來源 10:00 · 1 分鐘前</span></div><div class="older-field"><small>Hold</small><strong>N</strong><span>來源 09:51 · 10 分鐘前</span></div></div></div><div class="fresh-controls"><button class="button" id="refresh-table">模擬整表重新刷新至 10:01</button><button class="button" id="reset-join">重設</button></div><div id="join-answer" class="fresh-answer" role="status"></div>${verdict('表剛刷新，不代表每個欄位都剛更新。')}</figure>
${note('Lineage 要追到你準備使用的欄位','這列的 Step 可以支持一分鐘延遲的監看，卻不能因 Step 較新，就把 Hold=N 當成「現在沒有 Hold」。若這次決策需要 Step 與 Hold 同時成立，要核對兩欄來源時間及相容的快照，必要時透過 TX 取得並在控制交易重驗。')}`;}
function contract(){return `<h1>不要讓下一位工程師<br>再猜一次資料有多新。</h1><p class="lead">在 Table catalog 寫清來源、刷新／延遲和用途；混合來源的欄位，再補 Column lineage。以下名稱是教學範例，請以實際資料目錄為準。</p>
${rowsTable(['Table / 介面','Source','Refresh / Delay','Recommended Usage','Auto Control'],[['LOT_CURRENT_STATUS','SiView Native','RT1 · 通常 &lt;3 min','近即時監看','不可只憑此快照'],['WAFER_HISTORY','Data Mart','RT2 · 約10 min','歷史分析；驗證涵蓋期間','No'],['LOT_KPI_DAILY','Data Mart','Batch；按排程','每日 KPI；驗證批次完整','No'],['CURRENT_HOLD','SiView Native','RT1 · 通常 &lt;3 min','近即時 Hold 監看','不可只憑此快照'],['目前真實狀態（TX）','MMDB via TX','RT0 · transaction level','關鍵決策／核准交易','依核准交易，執行時重驗']])}
<div class="contract-example"><h2>一份能直接用的範例契約</h2><dl><dt>Table Name</dt><dd>LOT_PROCESS_SUMMARY（示例）</dd><dt>Source</dt><dd>SiView Native ＋ Hold Mart</dd><dt>Refresh / Delay</dt><dd>RT2 · 約10分鐘；逐欄保留來源時間</dd><dt>Recommended Usage</dt><dd>Analytics only；不作當下自動控制依據</dd><dt>Column Lineage</dt><dd>Current Step → SiView；Hold → Hold Mart</dd><dt>時間欄位</dt><dd>source_data_time、loaded_at、queried_at 各自保存</dd><dt>完整性</dt><dd>資料涵蓋截止、最新成功批次、晚到資料處理</dd></dl></div>
<section class="fresh-note"><h2>四句話帶走</h2><ol class="four-lines"><li>MMDB 是線上 Source of Truth；一般工程師透過 TX，不直接 Query。</li><li>Giga Report 是入口，不代表每份資料 freshness 相同。</li><li>SiView Native 通常 &lt;3 min；Data Mart 約10 min，實際仍看契約與來源時間。</li><li>現在的狀態看 Native／TX；歷史分析用 Mart。控制需由核准交易重驗。</li></ol></section>
<section class="fresh-quiz"><h2>最後換你判斷</h2><p>10:01 查到某表刷新時間是 10:01，但未記錄 Hold 欄位的來源時間。現在要 Auto Hold，該怎麼做？</p><button class="button" data-fresh-quiz="0">先補查 Hold 的來源與時間，再選 TX／核准控制交易</button><button class="button" data-fresh-quiz="1">先停止自動動作，交由工程確認</button><button class="button" data-fresh-quiz="2">刷新時間相同，就直接採用這筆 Hold</button><div id="quiz-answer" class="fresh-answer" role="status">選一個做法，看它成立的條件與代價。</div></section><div class="fresh-verdict">選 Data Source 前，不只問「有沒有這個欄位」，還要問「這個欄位是多久以前的」。</div>`;}
const freshnessViews={architecture,decision,ai,history,join,contract};
fresh$('#freshness-root').innerHTML=`<header class="topbar"><a class="brand" href="index.html"><b>M</b><span><small>MES LEARNING LAB</small>從現場認識資料</span></a><div class="course-tabs"><a href="index.html">01 基本物件</a><a href="operations.html">02 設備與現場</a><a href="flow.html">03 Flow 與 Lot</a><a href="freshness.html" aria-current="page">04 資料新鮮度</a></div><button class="button mobile-menu" id="fresh-menu" aria-expanded="false" aria-controls="sidebar">課程目錄</button></header><div class="shell"><aside id="sidebar"><p class="eyebrow">第四部分 · DATA FRESHNESS</p><h2 class="sidebar-title">你查到的是<br>哪個時刻？</h2><nav aria-label="本課章節">${freshChapters.map(([id,title,sub],i)=>`<a href="#${id}" data-chapter="${id}"><span>${String(i+1).padStart(2,'0')}</span><div>${title}<small>${sub}</small></div></a>`).join('')}</nav><div class="aside-foot">架構 → 選擇原則 → 三個案例<br>依你提供的環境條件製作</div></aside><main id="content" tabindex="-1"><div class="crumb">MES 入門教學 ／ 第四部分</div><div class="page-meta"><span class="pill">資料新鮮度</span><span id="fresh-progress"></span></div><article id="fresh-lesson" class="lesson"></article><div class="footer-nav"><button class="button" id="fresh-prev">← 上一段</button><span id="fresh-footer"></span><button class="button primary" id="fresh-next">下一段 →</button></div><p class="page-foot">教學案例為假設資料；未連線或執行真實 MES 查詢與控制。</p></main></div>`;
function updateDecision(){const v=freshState.decision;document.querySelectorAll('[data-level]').forEach(e=>e.classList.toggle('selected',e.dataset.level===v));fresh$('#decision-answer').textContent={analysis:'選 Data Mart：分析期間固定後，檢查資料已收齊。整理過的指標與歷史比當下一筆狀態更合適。',monitor:'先選 SiView Native：需求容許 3 分鐘，但仍須看本次來源時間；管線異常或資料過期時不能只相信 RT1 標籤。',control:'選 TX／核准控制交易：取得當下狀態，並在執行 Auto Hold 時重新驗證。近即時的三分鐘差距可能改變可執行條件。'}[v];}
function updateAI(){const v=freshState.source,control=freshState.tolerance==='control';const r={native:['Giga Report / SiView Native','ETCH','10:00',1],mart:['Giga Report / Data Mart','DEV','09:51',10],tx:['TX → MMDB','ETCH','10:01',0]}[v];fresh$('#query-source').textContent=r[0];fresh$('#query-step').textContent=r[1];fresh$('#query-time').textContent=r[2];fresh$('#query-age').textContent=r[3]+' 分鐘';fresh$('#age-fill').style.width=r[3]*10+'%';fresh$('#age-fill').className=r[3]>3?'old':'';fresh$('#query-step').className=v==='mart'?'old-text':'';fresh$('#ai-answer').textContent=v==='mart'?(control?'這是 09:51 的 DEV，不能當成 10:01 的位置。現在要 Auto Hold，改由 TX／核准控制交易取得當下狀態，並在執行時重驗條件。':'這是 09:51 的 DEV，不能當成 10:01 的位置。改找 Native 或 TX；Mart 的歷史內容本身沒有因此變錯。'):control?(v==='tx'?'TX 在本例回傳 10:01 的 ETCH；Auto Hold 仍須在核准交易執行時重驗條件，不能把查詢當成狀態鎖定。':'這筆 ETCH 是一分鐘前，符合一般監看卻不滿足當下控制要求。改由 TX／核准交易取得並重驗狀態。'):(v==='tx'?'這筆即時資料足以支持本次監看；若需求容許三分鐘，Native 通常更符合一般查詢路徑。':'這筆資料年齡一分鐘，小於本例可容忍的三分鐘，適合這次工程監看；不把此結論延伸為控制授權。');}
function updateHistory(){const complete=freshState.complete==='yes';fresh$('#history-coverage').textContent=complete?'昨日已收齊':'只涵蓋至昨日 14:00';fresh$('#history-record').innerHTML=complete?'<div class="event-row"><time>昨日 14:20</time><b>A123</b><span>DEV · Move Out</span><strong>已收錄</strong></div>':'<div class="event-row incomplete"><b>查無 DEV 事件</b><span>14:20 尚未在已涵蓋期間內</span></div>';fresh$('#history-answer').textContent=freshState.history==='current'?'事件簿只能說明發生過什麼，不能證明現在仍在 DEV。Current State 請改查 Native／TX，並驗證時間。':complete?'可以回答：昨天有經過 DEV；14:20 的事件已收錄。這個答案不表示 A123 現在仍在 DEV。':'不能回答「沒經過」。目前只收至 14:00，14:20 事件可能尚未載入；等待補齊或查核事件來源。';}
function updateJoin(){fresh$('#join-refresh-time').textContent=freshState.refreshed?'10:01':'10:00';fresh$('#join-answer').textContent=freshState.refreshed?'刷新完成只更新載入時間。Hold 的來源仍是 09:51，內容仍舊十分鐘；不能用它證明現在沒有 Hold。':'同一列：Step 是一分鐘前，Hold 是十分鐘前。點「重新刷新」看看：如果上游還沒更新，欄位年齡不會重設。';fresh$('#refresh-table').disabled=freshState.refreshed;}
function renderFresh(){let id=location.hash.slice(1)||'architecture';if(!freshnessViews[id])id='architecture';const i=freshChapters.findIndex(c=>c[0]===id);fresh$('#fresh-lesson').innerHTML=freshnessViews[id]();fresh$('#fresh-progress').textContent=`${i+1} / 6`;fresh$('#fresh-footer').textContent=freshChapters[i][1];fresh$('#fresh-prev').disabled=i===0;fresh$('#fresh-next').textContent=i===5?'回到開頭 ↺':'下一段 →';document.querySelectorAll('[data-chapter]').forEach(a=>{if(a.dataset.chapter===id)a.setAttribute('aria-current','step');else a.removeAttribute('aria-current');});document.title=freshChapters[i][1]+'｜資料新鮮度';fresh$('#sidebar').classList.remove('open');fresh$('#fresh-menu').setAttribute('aria-expanded','false');if(id==='decision')updateDecision();if(id==='ai')updateAI();if(id==='history')updateHistory();if(id==='join')updateJoin();fresh$('#fresh-prev').onclick=()=>location.hash=freshChapters[Math.max(0,i-1)][0];fresh$('#fresh-next').onclick=()=>location.hash=freshChapters[(i+1)%6][0];}
document.addEventListener('change',e=>{const map={'decision-purpose':['decision',updateDecision],'ai-source':['source',updateAI],'ai-tolerance':['tolerance',updateAI],'history-question':['history',updateHistory],'history-complete':['complete',updateHistory]};if(map[e.target.id]){const [key,fn]=map[e.target.id];freshState[key]=e.target.value;fn();}});
document.addEventListener('click',e=>{if(e.target.id==='refresh-table'){freshState.refreshed=true;updateJoin();}if(e.target.id==='reset-join'){freshState.refreshed=false;updateJoin();}if(e.target.dataset.freshQuiz!==undefined){freshState.quiz=Number(e.target.dataset.freshQuiz);document.querySelectorAll('[data-fresh-quiz]').forEach(b=>b.setAttribute('aria-pressed',String(b===e.target)));fresh$('#quiz-answer').textContent=['合理。先補來源與時間，決策若要求當下狀態，透過 TX／核准交易重驗。增加查核工作，避免用舊狀態控制。','也合理。暫停有時間成本，但在來源時間不明時，比猜測安全；工程確認仍要補足資料來源、時間與交易條件。','不成立。10:01 是整表載入時間，不能證明 Hold 的來源狀態也是 10:01。應追到欄位 lineage。'][freshState.quiz];}});
fresh$('#fresh-menu').onclick=()=>{const open=fresh$('#sidebar').classList.toggle('open');fresh$('#fresh-menu').setAttribute('aria-expanded',String(open));};document.addEventListener('keydown',e=>{if(e.key==='Escape'){fresh$('#sidebar').classList.remove('open');fresh$('#fresh-menu').setAttribute('aria-expanded','false');}});window.addEventListener('hashchange',()=>{renderFresh();window.scrollTo(0,0);fresh$('#content').focus({preventScroll:true});});renderFresh();
