'use strict';
const STEPS = [
  {id:'S10',name:'清洗',stage:'A',op:'CLEAN',recipe:'CLN-A/v1',group:'CLEAN'},
  {id:'S20',name:'成膜',stage:'A',op:'DEPOSIT',recipe:'DEP-A/v1',group:'CVD'},
  {id:'S30',name:'微影',stage:'B',op:'PHOTO',recipe:'PHO-A/v1',group:'PHOTO'},
  {id:'S40',name:'蝕刻',stage:'B',op:'ETCH',recipe:'ETCH-DEMO/v2',group:'ETCH'},
  {id:'S50',name:'量測',stage:'C',op:'MEASURE',recipe:'MET-A/v1',group:'METRO'},
  {id:'S60',name:'結案',stage:'C',op:'REVIEW',recipe:'不適用',group:'資料審核'}
];
const stageNames={A:'準備',B:'圖形',C:'確認'};
const article=(title,body)=>`<section class="article"><h2>${title}</h2>${body}</section>`;
const two=(a,b)=>`<div class="two"><div>${a}</div><div>${b}</div></div>`;
const take=t=>`<div class="takeaway"><b aria-hidden="true">☀</b><span>${t}</span></div>`;
const detail=(title,body)=>`<details><summary>${title}</summary><div>${body}</div></details>`;
const strip=items=>`<div class="strip">${items.map((x,i)=>`${i?'<span aria-hidden="true">→</span>':''}<div><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('')}</div>`;
const table=(heads,rows)=>`<div class="table-wrap" tabindex="0" role="region" aria-label="比較表；手機依紀錄逐項排列"><table><thead><tr>${heads.map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<td data-label="${heads[i]}">${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const record=rows=>`<dl class="record">${rows.map((r,i)=>`<div${i===rows.length-1?' class="wide"':''}><dt>${r[0]}</dt><dd>${r[1]}</dd></div>`).join('')}</dl>`;
function flowMap(current='S40',done=[],other='',lot='L023',flow='F-DEMO v1'){
 const steps=flow.endsWith('v2')?[...STEPS.slice(0,4),{id:'S45',name:'新增檢查',stage:'C',op:'INSPECT'},...STEPS.slice(4)]:STEPS;
 return `${other?'<p class="subtle">圖例：綠色勾號是 L023 的已完成紀錄；●／◆ 分別標出兩批目前位置，L024 在 S10 尚未開工。</p>':''}<div class="flow-map" aria-label="${flow} 作業位置">${Object.keys(stageNames).map(s=>`<section class="stage"><h3>Stage ${s} · ${stageNames[s]}</h3>${steps.filter(x=>x.stage===s).map(x=>`<div class="node ${x.id===current?'current':done.includes(x.id)?'done':''}"><small>${x.id} · ${x.op}</small>${x.name}${x.id===current?`<span class="marker">● ${lot} 目前位置</span>`:done.includes(x.id)?'<span class="marker">✓ 已完成</span>':''}${x.id===other?'<span class="marker">◆ L024 目前位置</span>':''}</div>`).join('')}</section>`).join('')}</div>`;
}
function art(name,alt,caption){const mobile=name==='flow-v3'?'flow-v4-mobile':`${name}-mobile`;return `<figure class="art"><button class="open-art" data-src="assets/mes-v2/${name}.png" aria-label="放大：${alt}"><picture><source media="(max-width:560px)" srcset="assets/mes-v2/${mobile}.png"><img src="assets/mes-v2/${name}.png" alt="${alt}" width="1672" height="941"></picture></button><figcaption><span>${caption}</span><span>點圖放大 ↗</span></figcaption></figure>`;}
const scope=`<p class="subtle">本課以 P-DEMO／F-DEMO v1 的簡化旅程教概念，ID、條件與例外皆為教學設定。不是完整晶片製程，也不是特定 Fab 的操作規範。</p>`;
const sources=`<details><summary>名詞與來源：本課的定義範圍</summary><div class="source-list"><p>Flow／Route：版本化的作業路徑。Stage：本課用來組織共同目的作業的分組。Step：在該路徑中的一次作業位置。各 MES 對 Stage、Operation、Step、Track-in／Track-out 的名稱及交易邊界不同，應對照公司的資料模型。</p><p>廠商資料支持本課使用的能力類型，具體6站路線與情境規則由本課設計：<a href="https://www.criticalmanufacturing.com/industries/semiconductor-manufacturing/" target="_blank" rel="noopener">Critical Manufacturing：物料路徑、配方及例外交易</a>；<a href="https://www.ibm.com/products/siview" target="_blank" rel="noopener">IBM SiView：Lot、Wafer、FOUP 與設備管理</a>；<a href="https://www.brooks.com/solutions/" target="_blank" rel="noopener">Brooks：晶圓搬送與設備自動化</a>；<a href="https://www.daifuku.com/pro/cr/" target="_blank" rel="noopener">Daifuku：潔淨室搬送與暫存</a>。</p><p>設備圖是 AI 生成教學示意，省略安全互鎖與完整機構；不是現場照片或施工圖。狀態練習在瀏覽器內模擬。</p></div></details>`;
const operationLessons=[
 {id:'tool',nav:'從載具到腔體',sub:'先看懂實體交接',title:'同一片晶圓，怎麼進入設備？',lead:'FOUP 是載具，Load Port 是交接位置，Chamber 才是執行製程的腔體。跟著晶圓看一次，三者就不容易混在一起。',body:()=>art('equipment-v2','FOUP 經 Load Port、搬送手臂與 Load lock 交接到 Chamber','看箭頭上的晶圓路徑；局部放大是位置說明。')+article('沿著晶圓走，辨認三個角色',strip([['FOUP 停靠','F012 在 ETCH03 的 LP1 上；整個載具不進入腔體。'],['晶圓交接','搬送手臂取出一片。此真空設備例透過 Load lock 交接壓力環境。'],['Chamber 加工','晶圓放到製程位置，依核准配方加工，再交接返回。']])+`<p>Tool／Equipment 是整台設備的管理單位；它可以有多個 Port 與多個 Chamber。其他設備可能沒有真空腔體或 Load lock，不能把這張剖面套成所有機台。</p>`)+take('載具的位置、晶圓的位置與設備的狀態，要分開記錄。')},
 {id:'transport',nav:'搬送與暫存',sub:'位置變了，流程未必變',title:'FOUP 到站，Lot 就完成過站了嗎？',lead:'先把「物料移動」和「製程推進」分開。搬送系統把載具送到目的地；MES 還要確認它能不能做下一個作業。',body:()=>art('transport-v2','同一 F012 由 Stocker 經 OHT 到 Load Port 的三個時刻','同一個 F012 的三個時刻，不是三個載具。')+article('搬送前後，哪些欄位真的改變？',table(['紀錄','出發前','到站後'],[['載具位置','STK01','ETCH03／LP1'],['Lot／Wafer','L023／W06、W07、W08','相同成員'],['Current Step','S40 蝕刻，等待','仍是 S40，等待開工'],['製程完成證據','尚未產生','仍未產生']])+`<p>AMHS 是自動物料搬送系統；OHT 是其中的天車搬送方式；Stocker 是暫存設備。搬送完成訊息只能證明到位，接著還有身分、配方與設備條件的確認。</p>`)+take('到站是位置事件；過站需要製程與資料條件成立。')},
 {id:'port',nav:'到站與身分核對',sub:'數量相同也可能錯片',title:'眼前這個 FOUP，真的是這批料嗎？',lead:'開工前把載具、槽位與晶圓身分對回預期資料。只看到「三片」還不夠。',body:()=>article('同樣是三片，為什麼不能直接放行？',two(`<h3>預期資料</h3>${record([['Lot','L023'],['FOUP','F012'],['Slot 06','W06'],['Slot 07','W07'],['Slot 08','W08']])}`,`<h3>本次讀取</h3>${record([['Lot','待核對'],['FOUP','F012'],['Slot 06','W06'],['Slot 07','<span class="bad">W99</span>'],['Slot 08','W08']])}`)+`<div class="decision">片數都是 3，但 Slot 07 的身分不一致。應保留差異、重新確認讀取與實物；不能把預期 W07 改成 W99 來消除警告。</div>`)+article('交接訊息各自證明什麼？',strip([['到位','目的 Port 已收到載具。'],['讀取／Mapping','取得本次讀值；讀值仍需核對。'],['資格確認','預期與讀值一致，才繼續檢查配方與設備。']])+`<p>槽位存在檢查與 Wafer ID 讀取不是同一能力；實機能讀哪些欄位，取決於感測器及整合方式。本例假設兩者都可取得。</p>`)+take('核對的是「哪一片在什麼位置」，不只是總共幾片。')},
 {id:'recipe',nav:'設備與配方資格',sub:'閒置不代表能做這站',title:'Step 決定要做什麼，Recipe 決定怎麼做',lead:'S40 要做蝕刻，但不是每台閒置設備、每個叫做「蝕刻」的配方都可以用。',body:()=>article('一次開工，核對三種不同的身分',strip([['流程位置','F-DEMO v1／S40：這批此刻應做蝕刻。'],['設備能力','ETCH03／CH-A：本例已取得此作業資格，且可用。'],['配方版本','ETCH-DEMO／v2：與本批本站的要求相符。']])+table(['候選','表面上看起來','本例判斷'],[['ETCH03 + v2','設備 Ready、資格有效、配方吻合','可進入本例的開工程序'],['ETCH03 + v1','名稱相同但版本舊','拒絕；不能把名稱相同當內容相同'],['CVD02 + v2','設備空著，也取得一個配方名稱','拒絕；成膜設備不是已核准的蝕刻設備']]))+detail('再深入：MES Step 與 Recipe Step 的層級',`<p>MES 的 S40 是批次流程中的作業位置。機台 Recipe 內部還可能包含抽氣、穩定、加工、吹掃等子步驟；那些是設備程序，不能直接當成這批 Lot 的 S40→S50。</p><p>配方內容也可能依產品、設備、腔體與版本決定；本課只以明示的版本字串驗證，不示範真實製程參數。</p>`)+take('「這台能不能做」與「要執行哪個版本」都要對上 Lot 的當前 Step。')},
 {id:'chamber',nav:'逐片加工與整批完成',sub:'一片完成不等於一批完成',title:'W06 做完時，L023 還沒做完',lead:'Lot 有三片。單片設備逐一處理，批次的完成條件要涵蓋本次預定加工的全部晶圓。',body:()=>article('把同一批的中間狀態攤開',table(['時刻','FOUP 內','CH-A','本次完成'],[['剛開始','W07、W08；Slot 06 空','W06 加工中','0／3'],['第一片返回','W06、W07、W08','空閒，準備下一片','1／3'],['第二片加工','W06、W08；Slot 07 空','W07 加工中','1／3'],['全部返回','W06、W07、W08','空','3／3，待本站資料確認']])+`<p>在兩片之間，Chamber 可能暫時 Idle，但 Lot 的本次作業還沒結束。不能把 Chamber 的瞬間狀態當成整批狀態。</p>`)+article('守住一個可核對的不變量',`<p class="number">FOUP 內的片 ＋ 交接／腔體內的片 ＝ 本次三片</p><p>同一個 Wafer ID 在同一時刻只能有一個有效位置。取出 W07 時，Slot 07 要顯示空；返回後才能重新顯示 W07。</p>`)+take('逐片紀錄回答誰做完；Lot 的本站結果回答這次作業是否完整。')},
 {id:'state',nav:'加工狀態與 Hold',sub:'誰被擋住？為什麼？',title:'設備可用，Lot 仍可能不能開工',lead:'狀態一定要帶上對象。設備 Ready、Lot Hold、Wafer In-process 可以同時成立，不能縮成一個紅綠燈。',body:()=>article('同一現場，同時有三個判斷',table(['對象','問題','例子'],[['Equipment','設備能不能接受工作？','ETCH03 Ready；CH-A 資格有效'],['Lot','這批現在允不允許執行？','L023 Hold：等待量測複核'],['Wafer／Run','本次作業做到哪裡？','W06 完成，W07 中斷，W08 未開始']])+`<p>Hold 是執行限制，不是載具位置。解除 Hold 也不是自動開工，更不會把失敗的加工結果改成成功。</p>`)+article('兩個 Hold 原因，就要分別處理',strip([['Q01 品質待判','品質人員複核後可解除此原因。'],['E02 工程確認','Q01 清除後，本原因仍然有效。'],['全部解除後','回到可準備執行；仍需確認當前 Step、設備與配方。']]))+take('先問「誰的狀態」，再問「哪一項條件阻止下一個動作」。')},
 {id:'handoff',nav:'從機台完成到 MES 過站',sub:'資料確認是交接的一部分',title:'機台報 Done，MES 為什麼還不往下走？',lead:'晶圓加工完成只是其中一個證據。本例還要核對三片結果、收齊必要資料，再完成本站的 MES 交易。',body:()=>article('一個完整的交接',strip([['開始本次作業','驗證前置條件，建立 S40 第1次 visit。'],['機台完成','收回三片；取得 Run 結果與結束事件。'],['MES 完成本站','檢查完整性；記錄 S40 結果，才推進 S50。']])+`<div class="event-example"><b>10:00</b><span>S40 Track-in；Recipe v2，3片。</span><b>10:06</b><span>機台 Done；W08 結果尚未回傳。</span><b>10:07</b><span>收到 W08；3片結果齊全。</span><b>10:08</b><span>Track-out 成功；目前位置變為 S50。</span></div><p>這裡採用「驗證成功的 Track-out 同時推進」作為教學交易。其他 MES 可能把 Complete、Track-out、Move-next 分開；應看實際資料契約。</p>`)+take('只有完成本站的必要證據與交易，Lot 才能取得下一站位置。')},
 {id:'lab',nav:'六個現場情境',sub:'搬送、錯片、配方、加工、故障、Hold',title:'把設備現場的判斷，實際做一次',lead:'選擇情境後操作。右側會保留每次事件與拒絕原因；每個情境都可獨立重設。',body:()=>`<div id="scenario-lab"></div>`}
];
const flowLessons=[
 {id:'flow',nav:'Flow：整條製造路徑',sub:'先看全局，再放大一站',title:'Flow 是一份有規則的製造路徑',lead:'它描述這個產品要經過哪些作業、依什麼順序，以及哪些條件可以分流或重工。不是把機台名稱串成一排。',body:()=>art('flow-v3','三個 Stage 六個 Step 與兩批 Lot 的不同流程位置','流程箭頭代表作業順序；Lot 標記代表各批次的執行位置。')+article('這堂課追蹤哪一段旅程？',scope+flowMap('S40',['S10','S20','S30'],'S10')+`<p>兩批都套用 F-DEMO v1，L023 已到 S40，L024 還在 S10。Flow 定義可以共用，批次進度各自保存。</p><p>實際晶圓製造會反覆進入成膜、微影、蝕刻、清洗及量測等作業。本課把一段旅程縮成六站，讓層級與交易容易看清楚。</p>`)+take('Flow 管「應該怎麼走」，Lot 執行紀錄管「實際走到哪裡」。')},
 {id:'stage',nav:'Stage：有目的的分組',sub:'分組不等於一次加工',title:'Stage 把相關 Step 組成一段工作',lead:'先用「準備、圖形、確認」看懂目的，再展開每個 Step。Stage 完成與整條 Flow 完成，是兩個不同範圍。',body:()=>article('由外往內讀這個結構',`<div class="hierarchy"><h3>Flow F-DEMO · v1</h3><p class="subtle">外框是同一流程版本；色帶是 Stage 的分組邊界。</p>${flowMap('S40',['S10','S20','S30'])}</div>`)+article('L023 做完 S40 之後',two(`<h3>Stage B 已完成</h3><p>S30 與 S40 的必要作業都完成，可以離開「圖形」階段。</p><p class="good">本階段 2／2 已完成。</p>`,`<h3>Flow 還沒完成</h3><p>仍須做 Stage C 的 S50 量測與 S60 結案。</p><p class="bad">全流程只有 4／6 站完成。</p>`)+`<p>本課把 Stage 當作業分組，完成條件由其必要 Step 決定。某些 MES 的 Stage 可能是更正式的執行或排程單位，不能直接以本例推定。</p>`)+take('Stage 幫助理解一段工作的目的；真正要檢查的是其中哪些 Step 已完成。')},
 {id:'step',nav:'Step：精確的流程位置',sub:'Operation、Recipe、Tool 分開看',title:'Step 是「這條路上的這一次作業」',lead:'同一種清洗可能在不同位置出現。只記「清洗做過了」，還不足以知道這批完成了哪一個 Step。',body:()=>article('把 S40 拆開看',record([['Flow 版本','F-DEMO v1'],['Stage','B · 圖形'],['Step occurrence','S40'],['Operation','ETCH · 蝕刻'],['設備群','ETCH'],['Recipe','ETCH-DEMO/v2'],['下一個正常位置','S50 · 量測']])+`<p class="subtle">Occurrence 指一次「出現位置」。S40 是本流程中的位置 ID；不是通用蝕刻作業的唯一 ID。</p>`)+article('為什麼不能只用 Operation 當識別？',strip([['S10 · CLEAN','準備階段的第一次清洗。'],['其他製程','表面狀態已被前面的作業改變。'],['R10 · CLEAN','核准重工支線中的再清洗；不是 S10 的舊紀錄。']])+`<p>Operation 可重用，Flow 位置與本次 visit 必須區分。Recipe 內部的 Step 又是另一層設備動作。</p>`)+take('完整定位至少要看流程版本與作業位置；重跑時再加上本次 visit。')},
 {id:'lot-flow',nav:'Lot 如何套用 Flow',sub:'定義與執行實例的連結',title:'套用 Flow，是替 Lot 建立一條可追蹤的旅程',lead:'依產品與核准版本選定流程，為這一批建立起始位置和執行狀態。之後推進的是這批的紀錄。',body:()=>article('先選定義，再建立批次的執行資料',strip([['產品要求','P-DEMO 對應核准 F-DEMO v1。'],['套用到 L023','保留 Flow ID、版本及起始 occurrence S10。'],['獨立推進','L023 與 L024 可以停在不同 Step，互不改寫。']])+two(`<h3>流程定義</h3>${record([['Flow','F-DEMO'],['Version','v1'],['Release','已核准'],['起點','S10'],['路徑','S10→S20→S30→S40→S50→S60']])}`,`<h3>Lot 執行實例</h3>${record([['Lot','L023'],['Product','P-DEMO'],['FlowRef','F-DEMO v1'],['Current','S40'],['RunState','Queued · 尚未開始 S40']])}`))+article('FOUP 是位置，不是流程的擁有者',`<p>L023 從 F012 換到 F018，流程版本與當前 Step 不因此改變。相反地，拆批會建立新的 Lot 身分與追溯關係，即使晶圓暫時還在同一個載具，也要各自管理執行資料。</p>`)+detail('工程資料示例：本課欄位，不是既有 ER 的表名',`<p><code>FlowVersion(flowId, version, releaseState)</code></p><p><code>StepOccurrence(flowId, version, occurrenceId, stageId, operationRef, nextRule)</code></p><p><code>LotExecution(lotId, productId, flowRef, currentOccurrence, runState)</code></p><p><code>Visit(lotId, occurrenceId, visitNo, recipeRef, startAt, endAt, result)</code></p><p>另存 Hold 原因、Wafer 成員、Carrier 位置與 genealogy。實際關聯鍵與交易必須依公司 schema 調整。</p>`)+take('套用的是核准的流程版本；每個 Lot 保有自己的位置、狀態與歷程。')},
 {id:'execution',nav:'過站與歷程',sub:'指標移動要有完成證據',title:'從 S40 到 S50，中間不是只改一個欄位',lead:'確認可開工、建立 visit、接收結果、驗證完成，最後才更新目前位置。每一步都留下事件。',body:()=>article('定義保持原樣，L023 的執行資料改變',`<div class="swim"><b>Flow v1</b><div>S30 → <strong>S40</strong> → S50；規則始終相同。</div><b>開始前</b><div>Current = S40；RunState = Queued；Visit #1 尚未開始。</div><b>加工中</b><div>Current = S40；RunState = Processing；記錄設備、配方、開始時間。</div><b>完成後</b><div>S40 Visit #1 = Pass；Current = S50；RunState = Queued。</div></div><p>如果結果缺漏，留在 S40 的待確認狀態。若品質不合格，依規則 Hold／分流，不能把指標直接加一。</p>`)+article('前次事件為什麼不能覆寫？',`<div class="event-example"><b>Visit #1</b><span>S50 第一次量測，結果 Fail。</span><b>處置</b><span>工程師評估，核准重工支線 R10。</span><b>Visit #2</b><span>回到 S50 複測；新 Visit、新結果，前次仍可查。</span></div>`)+take('目前位置是一個摘要；歷程才說明它為什麼能走到這裡。')},
 {id:'branching',nav:'條件分流與 Hold',sub:'結果決定下一步',title:'Flow 可以有分支，但要有明確判斷依據',lead:'量測後未必每一批都走同一條路。條件應讀取有效的結果與規則，不能讓操作者隨意挑下一站。',body:()=>article('S50 量測之後的兩個去向',`<div class="branch-map"><div class="branch-node"><h3>S50 · 量測結果</h3><p>資料完整，先判斷是否在本例允收範圍。</p></div><div class="fork">⇉</div><div class="branch-dest"><div class="branch-node pass"><h3>合格 → S60</h3><p>保留量測結果，前往結案確認。</p></div><div class="branch-node review"><h3>不合格 → Hold</h3><p>保留 S50 位置；先工程評估，不自動重工。</p></div></div></div>`+`<p>缺資料不等於不合格，也不等於合格；要先補足判斷的證據。Hold 表示等待處置，處置結果可能是重工、報廢或其他核准路徑。</p>`)+take('分支條件來自可核對的結果；Hold 保留問題，不能用來假裝完成。')},
 {id:'rework',nav:'Rework：核准的返回路徑',sub:'回去做，不抹掉前次失敗',title:'重工不是把 Current Step 隨便往回改',lead:'要知道為什麼重工、走哪段路、回到哪裡、允許幾次，以及回來後要再驗什麼。',body:()=>article('同一批 L023 的重工路徑',strip([['S50 不合格','保存量測結果，套用品質 Hold。'],['核准 R10 清洗','工程處置指定重工路徑，最多1次。'],['回到 S50 複測','建立 Visit #2，合格才可前往 S60。']])+`<div class="decision"><strong>教學設定：</strong>R10 是可重用 CLEAN 作業的重工 occurrence。是否真的能清洗修復某種不合格，必須由實際製程規範判定；此處只教路徑與追溯。</div>`)+article('要保留的五個關聯',table(['關聯','本例'],[['原始失敗','S50 Visit #1 = Fail'],['批准紀錄','RW-001，指定 R10→S50'],['迴圈限制','最多1次；再失敗需重新處置'],['返回點','S50，不能直接跳 S60'],['新結果','S50 Visit #2，與前次結果並存']]))+take('重工新增一段受控歷程；它不會讓原始失敗從紀錄中消失。')},
 {id:'split-merge',nav:'拆批與合批',sub:'成員改變，追溯不能斷',title:'只有 W08 需要處理，整批一定要一起走嗎？',lead:'可以依核准規則拆批，讓子批各自執行。但成員數量、晶圓身分與父子關係都必須對得回來。',body:()=>article('拆批改的是管理身分',strip([['拆批前 L023','W06、W07、W08，共3片。'],['拆成兩個子批','L023-A：W06、W07；L023-B：W08。'],['各自執行','A留在S50；B走R10；原L023保留譜系，停止作為活躍批次。']])+`<p class="number">{W06, W07} ∪ {W08} ＝ {W06, W07, W08}</p><p>兩個集合不能重疊。拆批不會複製晶圓，也不一定立刻發生物理換載具。</p>`)+article('合批前，先核對能否站在同一個位置',table(['必要比較（本例）','為什麼'],[['Product、Flow、Version','不能把不同產品或不同作業要求當成一批'],['Current occurrence、執行狀態','A在S50、B在R10時，不能假装進度相同'],['Hold、品質處置','未解除的限制不能藉合批消失'],['成員、譜系與位置資料','合批後仍可反查每片從哪個子批來']])+`<p>本例讓 B 完成 R10 後回到 S50，兩個子批都等待量測且無 Hold，才核准合成 L023-M。實際規則可能更嚴格。</p>`)+take('拆合批可以改變批次組合，不能改寫每片晶圓真正走過的歷程。')},
 {id:'versions',nav:'版本、跳站與等待時間',sub:'流程變更也要有契約',title:'發布新版，不代表所有在製 Lot 立刻換路線',lead:'流程定義、批次套用與批次遷移，是三個不同事件。例外變更還要檢查過站資格與時間條件。',body:()=>article('v2 新增檢查，誰需要做？',two(`<h3>L023 已套用 v1</h3><p>仍依 v1 執行。發布 v2 不會自行改掉它的流程參照或歷程。</p>`,`<h3>L024 新投入</h3><p>依產品設定套用已核准 v2，包含新增 S45 檢查。</p>`)+`<p>若工程師決定把 L023 遷到 v2，需核對目前位置映射、已做作業是否等效、新增檢查是否應補做，並留下批准紀錄。本例在 S40 完成後，從 v1/S50 映到 v2/S45；沒有模糊地「升版完成」。</p>`)+article('兩種常見的流程捷徑',table(['想做的動作','應先確認'],[['直接跳過 S50 量測','是否有核准且滿足替代證據？本課的必要量測不可跳過。'],['等待超時，把開始時間重設','時間約束依指定事件計時；重設顯示不會消除已經暴露的時間。']])+`<p>情境的 Q-time 以 S20 完成到 S30 開始最多30分鐘示範；暫停或 Hold 不自動停止這個時鐘。30分鐘是教學門檻，實廠會依製程、事件與批准處置決定。</p>`)+take('流程改版與例外需要批准、位置映射與追溯；不能只改畫面上的下一站。')},
 {id:'lab',nav:'十個 Flow 情境',sub:'從套用一路走到例外',title:'讓 Lot 真正沿著 Flow 走一次',lead:'正常旅程可以從 S10 走到 S60；其餘情境各自從一個明示的中間狀態開始。操作後看位置、版本、成員與事件如何改變。',body:()=>`<div id="scenario-lab"></div>`}
];
const COURSES={operations:{label:'第二部分',title:'設備與現場作業',short:'現場作業',lessons:operationLessons,next:'flow.html',nextText:'接著看第三部分：Flow 與 Lot'},flow:{label:'第三部分',title:'Flow 與 Lot 的旅程',short:'Flow 深入',lessons:flowLessons,next:'index.html',nextText:'回到第一部分：基本物件'}};
