from pathlib import Path
p=Path('er-atlas.html');s=p.read_text(encoding='utf-8').replace('?v=2','?v=3')
s=s.replace('<section class="workspace">','''<section class="entity-tools" aria-label="在完整 ER 框選物件"><div><strong>先看全圖，再找物件</strong><span>框選保留所有連線；需要讀表名時，再放大。</span></div><div class="choices"><button data-entity="lot">框選 Lot</button><button data-entity="carrier">框選 FOUP</button><button data-entity="equipment">框選 EQP</button><button data-entity="flow">框選 Flow</button><button data-entity="recipe">框選 Recipe</button><button id="clear-entity">清除框選／全圖</button></div></section><section class="workspace">''')
s=s.replace('<div id="meaning"></div>','''<div id="meaning"></div><figure class="teaching-figure"><button id="open-teaching" aria-label="放大教學插圖"><img id="teaching-image" alt=""><span>放大教學插圖 ↗</span></button><figcaption id="teaching-caption"></figcaption></figure><a id="teaching-link">閱讀完整教學 →</a><div id="entity-targets"></div>''')
s=s.replace('</main>','''</main><dialog id="teaching-dialog"><form method="dialog"><button aria-label="關閉教學插圖">關閉 ×</button></form><img id="teaching-large" alt=""><p id="teaching-large-caption"></p></dialog>''')
p.write_text(s,encoding='utf-8')
p=Path('er-atlas.js');s=p.read_text(encoding='utf-8')
s=s.replace("function route(id){", "function route(id){clearFrames();displayMode='route';document.querySelector('.walk-tools').hidden=false;showTeaching(({load:'lot',slot:'carrier',location:'equipment',predispatch:'equipment','lot-pre':'equipment',port:'equipment',flow:'flow',lr:'recipe',pd:'recipe',recipe:'recipe',chamber:'equipment',hold:'lot',move:'lot',transfer:'carrier',qtime:'flow',wip:'lot',oee:'equipment'})[id]||'lot');")
s=s.replace("function selectNode(id){", "function selectNode(id){clearFrames();displayMode='node';document.querySelector('.walk-tools').hidden=false;showTeaching(nodes.get(id).category in teaching?nodes.get(id).category:'lot');")
s=s.replace("function overview(){", "function overview(){clearFrames();displayMode='overview';document.querySelector('.walk-tools').hidden=true;walkIds=[];document.querySelectorAll('[data-route]').forEach(b=>b.setAttribute('aria-pressed','false'));inspect([],'完整 ER × 現場物件','先用左側大圖認識資料之間的關係，再按上方物件按鈕。彩色框指出資料位置；教學插圖說明它在現場代表什麼。');showTeaching('overview');")
s=s.replace("mode?question(location.hash.slice(1)):route('load')", "mode?question(location.hash.slice(1)):overview()")
s=s.replace("if(svg)route(activeRoute)", "if(svg&&['overview','entity'].includes(displayMode))setView(allBox.slice())")
s=s.replace("+'%';}", "+'%';if(svg)drawFrames();}",1)
s=s.replace("window.ER_ATLAS={model,route,overview", "window.ER_ATLAS={model,frameEntity,route,overview")
insert='''
let displayMode='overview',activeEntity=null,framedIds=[];
const teaching={
overview:{image:'examples/fab-physical-data-v01.png',alt:'機台、FOUP、Slot、Wafer 與 Lot 資料對照',caption:'左側是現場，右側是資料。Lot 是生產批次；FOUP 是承載晶圓的實體容器。',link:'index.html#fab'},
lot:{title:'Lot：生產批次',refs:['2671:lot','2676:lot'],color:'#176ac2',image:'examples/fab-physical-data-v01.png',alt:'現場物件與右側 Lot L023 的資料對照',caption:'看右側 lot_id = L023：Lot 將這批晶圓組織成生產與追蹤單位。',meaning:'藍框標出 Lot 資料實體。Lot 本身不是盒子；沿著「放在」關係，才會找到承載它的 FOUP。不同 schema 證據的節點仍各自保留。',link:'index.html#lot'},
carrier:{title:'FOUP：承載晶圓的容器',refs:['2671:cast','2676:cast'],color:'#008775',image:'examples/fab-physical-data-v01.png',alt:'FOUP F012 內的 Slot 07 與 Wafer W07',caption:'看中間剖面：FOUP 內有 Slot，晶圓放在對應位置。',meaning:'綠框標出 FOUP 資料實體。FRCAST 描述載具，FRCAST_LOT 表達與 Lot 的裝載關係；兩者不是同一個物件。',link:'index.html#foup'},
equipment:{title:'EQP：執行作業的設備',refs:['2671:eqp','2676:eqp','2677:eqp'],color:'#b26018',image:'examples/fab-physical-data-v01.png',alt:'FOUP F012 放在 ETCH-03 設備的 LP1',caption:'看左側 ETCH-03 與 LP1：設備、Port、FOUP 有不同身分。',meaning:'橘框標出 EQP 資料實體。設備可與 Port、Chamber、派工及 Recipe 配置相連；「預派」不能直接證明載具已經到達。',link:'operations.html#port'},
flow:{title:'Flow：批次遵循的製程路徑',refs:['2673:flow'],color:'#7756af',image:'assets/mes-v3/stage-v2.png',alt:'三個 Stage、六個 Step，以及目前在 S50 的 Lot',caption:'整條是 Flow；每段是 Stage；每一站是 Step。Lot 有自己的執行進度。',meaning:'紫框標出 Flow 資料對象。從 Lot 的 Part／Mainpd_id 關係找到流程定義，再區分「路徑如何定義」與「這批目前走到哪裡」。',link:'flow.html#stage'},
recipe:{title:'Recipe：從邏輯要求到設備配置',refs:['2673:lr-eqp','2677:recipe'],color:'#7756af',image:'assets/mes-009/recipes.png',alt:'LR、ER 與實際加工 Physical Recipe 的教學對照',caption:'示意值用來理解三層概念；實際名稱與映射仍以廠內定義為準。',meaning:'紫框分別指出 LR 與 ER 相關資料。ER 連線呈現配置關係；要知道某批實際用了哪個 Physical Recipe，還需要該次執行紀錄及版本證據。',link:'advanced.html#recipes'}
};
function showTeaching(key){const t=teaching[key]||teaching.overview;$('teaching-image').src=t.image;$('teaching-image').alt=t.alt;$('teaching-caption').textContent=t.caption;$('teaching-link').href=t.link;}
function clearFrames(){framedIds=[];activeEntity=null;svg?.querySelector('#entity-frames')?.remove();$('entity-targets').replaceChildren();document.querySelectorAll('[data-entity]').forEach(b=>b.setAttribute('aria-pressed','false'));}
function drawFrames(){svg.querySelector('#entity-frames')?.remove();if(!framedIds.length)return;const ns='http://www.w3.org/2000/svg',g=document.createElementNS(ns,'g');g.id='entity-frames';g.style.pointerEvents='none';const scale=Math.min($('canvas').clientWidth/view[2],$('canvas').clientHeight/view[3]);const pad=7/scale;for(const id of framedIds){const b=box(id),r=document.createElementNS(ns,'rect');for(const [k,v] of Object.entries({x:b.x-pad,y:b.y-pad,width:b.w+2*pad,height:b.h+2*pad,rx:4/scale,fill:'none',stroke:teaching[activeEntity].color,'stroke-width':3/scale}))r.setAttribute(k,v);g.append(r);}svg.append(g);}
function frameEntity(key){overview();const t=teaching[key];activeEntity=key;displayMode='entity';framedIds=[...new Set(t.refs.map(r=>model.mapping[r]).filter(Boolean))];drawFrames();showTeaching(key);inspect(framedIds,t.title,t.meaning);$('entity-targets').innerHTML='<h3>框選位置 · 點一下放大</h3>'+framedIds.map((id,i)=>`<button data-target="${id}">${i+1}. ${nodes.get(id).labels.map(esc).join(' / ')} ↗</button>`).join('');document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{fitIds([b.dataset.target],true);$('status').textContent='已放大框選物件。按「全圖總覽」回到完整 ER。'});document.querySelector(`[data-entity="${key}"]`).setAttribute('aria-pressed','true');$('status').textContent=`已框選 ${framedIds.length} 個 ${t.title.split('：')[0]} 資料位置；全部 ${model.nodes.length} 個節點與 ${model.edges.length} 條連線仍保留。`;}
document.querySelectorAll('[data-entity]').forEach(b=>b.onclick=()=>{if(model)frameEntity(b.dataset.entity)});
$('clear-entity').onclick=()=>{if(svg)overview()};
$('open-teaching').onclick=()=>{$('teaching-large').src=$('teaching-image').src;$('teaching-large').alt=$('teaching-image').alt;$('teaching-large-caption').textContent=$('teaching-caption').textContent;$('teaching-dialog').showModal()};
'''
s=s.replace("const mode=new URLSearchParams",insert+"\nconst mode=new URLSearchParams")
p.write_text(s,encoding='utf-8')
p=Path('er-atlas.css');p.write_text(p.read_text(encoding='utf-8')+'''
/* MES-015: full ER and physical meaning remain visible together. */
.entity-tools{padding:18px 20px;margin:18px 0;background:#fff;border:1px solid #cbdce9;border-radius:12px}.entity-tools strong{font-size:19px}.entity-tools span{display:inline-block;margin:0 0 12px 16px;font-size:14px;color:#536d83}.entity-tools [data-entity]{border-left:4px solid #176ac2}.entity-tools [data-entity=carrier]{border-left-color:#008775}.entity-tools [data-entity=equipment]{border-left-color:#b26018}.entity-tools [data-entity=flow],.entity-tools [data-entity=recipe]{border-left-color:#7756af}.workspace{grid-template-columns:minmax(0,1fr) minmax(340px,30%)}.teaching-figure{margin:18px 0 8px}.teaching-figure button{display:block;width:100%;padding:0;overflow:hidden}.teaching-figure img{display:block;width:100%;height:auto}.teaching-figure button span{display:block;padding:7px;background:#edf5ff;font-size:13px}.teaching-figure figcaption{font-size:14px;margin-top:10px}#entity-targets button{display:block;width:100%;text-align:left;overflow-wrap:anywhere;margin:8px 0}#teaching-dialog{width:min(1500px,95vw);max-height:95vh;padding:18px;border:1px solid #b4cadd;border-radius:12px}#teaching-dialog::backdrop{background:#102b42bb}#teaching-dialog form{text-align:right;margin-bottom:12px}#teaching-large{display:block;width:100%;height:auto}button:disabled{opacity:.45;cursor:default}@media(max-width:950px){.workspace{grid-template-columns:1fr}.entity-tools span{display:block;margin:6px 0 12px}.teaching-figure{max-width:680px}} 
''',encoding='utf-8')
